/**
 *
 * @file NVIC_RegisterDefines_Set1_ICPR.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET1_NVIC_REGISTERDEFINES_SET1_ICPR_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET1_NVIC_REGISTERDEFINES_SET1_ICPR_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_Set/RegisterDefines_Set_Generic/NVIC_RegisterDefines_Set_Generic.h>

/********************************************************************************************/
/************************************* ICPR1 ***********************************************/
/********************************************************************************************/

/*----------*/
#define NVIC_ICPR1_NVIC_I2C1_ER_MASK    NVIC_ICPR_NVIC_PERIPHERAL0_MASK
#define NVIC_ICPR1_NVIC_I2C1_ER_DIS    NVIC_ICPR_NVIC_PERIPHERAL0_DIS
#define NVIC_ICPR1_NVIC_I2C1_ER_ENA    NVIC_ICPR_NVIC_PERIPHERAL0_ENA

#define NVIC_ICPR1_R_NVIC_I2C1_ER_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_ICPR1_R_NVIC_I2C1_ER_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_ICPR1_R_NVIC_I2C1_ER_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL0_DIS
#define NVIC_ICPR1_R_NVIC_I2C1_ER_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL0_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_I2C2_EV_MASK    NVIC_ICPR_NVIC_PERIPHERAL1_MASK
#define NVIC_ICPR1_NVIC_I2C2_EV_DIS    NVIC_ICPR_NVIC_PERIPHERAL1_DIS
#define NVIC_ICPR1_NVIC_I2C2_EV_ENA    NVIC_ICPR_NVIC_PERIPHERAL1_ENA

#define NVIC_ICPR1_R_NVIC_I2C2_EV_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_ICPR1_R_NVIC_I2C2_EV_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_ICPR1_R_NVIC_I2C2_EV_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL1_DIS
#define NVIC_ICPR1_R_NVIC_I2C2_EV_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL1_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_I2C2_ER_MASK    NVIC_ICPR_NVIC_PERIPHERAL2_MASK
#define NVIC_ICPR1_NVIC_I2C2_ER_DIS    NVIC_ICPR_NVIC_PERIPHERAL2_DIS
#define NVIC_ICPR1_NVIC_I2C2_ER_ENA    NVIC_ICPR_NVIC_PERIPHERAL2_ENA

#define NVIC_ICPR1_R_NVIC_I2C2_ER_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_ICPR1_R_NVIC_I2C2_ER_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_ICPR1_R_NVIC_I2C2_ER_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL2_DIS
#define NVIC_ICPR1_R_NVIC_I2C2_ER_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL2_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_SPI1_MASK    NVIC_ICPR_NVIC_PERIPHERAL3_MASK
#define NVIC_ICPR1_NVIC_SPI1_DIS    NVIC_ICPR_NVIC_PERIPHERAL3_DIS
#define NVIC_ICPR1_NVIC_SPI1_ENA    NVIC_ICPR_NVIC_PERIPHERAL3_ENA

#define NVIC_ICPR1_R_NVIC_SPI1_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_ICPR1_R_NVIC_SPI1_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_ICPR1_R_NVIC_SPI1_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL3_DIS
#define NVIC_ICPR1_R_NVIC_SPI1_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL3_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_SPI2_MASK    NVIC_ICPR_NVIC_PERIPHERAL4_MASK
#define NVIC_ICPR1_NVIC_SPI2_DIS    NVIC_ICPR_NVIC_PERIPHERAL4_DIS
#define NVIC_ICPR1_NVIC_SPI2_ENA    NVIC_ICPR_NVIC_PERIPHERAL4_ENA

#define NVIC_ICPR1_R_NVIC_SPI2_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL4_BIT
#define NVIC_ICPR1_R_NVIC_SPI2_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL4_MASK
#define NVIC_ICPR1_R_NVIC_SPI2_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL4_DIS
#define NVIC_ICPR1_R_NVIC_SPI2_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL4_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_USART1_MASK    NVIC_ICPR_NVIC_PERIPHERAL5_MASK
#define NVIC_ICPR1_NVIC_USART1_DIS    NVIC_ICPR_NVIC_PERIPHERAL5_DIS
#define NVIC_ICPR1_NVIC_USART1_ENA    NVIC_ICPR_NVIC_PERIPHERAL5_ENA

#define NVIC_ICPR1_R_NVIC_USART1_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL5_BIT
#define NVIC_ICPR1_R_NVIC_USART1_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL5_MASK
#define NVIC_ICPR1_R_NVIC_USART1_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL5_DIS
#define NVIC_ICPR1_R_NVIC_USART1_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL5_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_USART2_MASK    NVIC_ICPR_NVIC_PERIPHERAL6_MASK
#define NVIC_ICPR1_NVIC_USART2_DIS    NVIC_ICPR_NVIC_PERIPHERAL6_DIS
#define NVIC_ICPR1_NVIC_USART2_ENA    NVIC_ICPR_NVIC_PERIPHERAL6_ENA

#define NVIC_ICPR1_R_NVIC_USART2_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL6_BIT
#define NVIC_ICPR1_R_NVIC_USART2_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL6_MASK
#define NVIC_ICPR1_R_NVIC_USART2_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL6_DIS
#define NVIC_ICPR1_R_NVIC_USART2_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL6_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_USART3_MASK    NVIC_ICPR_NVIC_PERIPHERAL7_MASK
#define NVIC_ICPR1_NVIC_USART3_DIS    NVIC_ICPR_NVIC_PERIPHERAL7_DIS
#define NVIC_ICPR1_NVIC_USART3_ENA    NVIC_ICPR_NVIC_PERIPHERAL7_ENA

#define NVIC_ICPR1_R_NVIC_USART3_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL7_BIT
#define NVIC_ICPR1_R_NVIC_USART3_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL7_MASK
#define NVIC_ICPR1_R_NVIC_USART3_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL7_DIS
#define NVIC_ICPR1_R_NVIC_USART3_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL7_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_EXTI15_10_MASK    NVIC_ICPR_NVIC_PERIPHERAL8_MASK
#define NVIC_ICPR1_NVIC_EXTI15_10_DIS    NVIC_ICPR_NVIC_PERIPHERAL8_DIS
#define NVIC_ICPR1_NVIC_EXTI15_10_ENA    NVIC_ICPR_NVIC_PERIPHERAL8_ENA

#define NVIC_ICPR1_R_NVIC_EXTI15_10_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL8_BIT
#define NVIC_ICPR1_R_NVIC_EXTI15_10_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL8_MASK
#define NVIC_ICPR1_R_NVIC_EXTI15_10_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL8_DIS
#define NVIC_ICPR1_R_NVIC_EXTI15_10_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL8_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_RTC_ALARM_MASK    NVIC_ICPR_NVIC_PERIPHERAL9_MASK
#define NVIC_ICPR1_NVIC_RTC_ALARM_DIS    NVIC_ICPR_NVIC_PERIPHERAL9_DIS
#define NVIC_ICPR1_NVIC_RTC_ALARM_ENA    NVIC_ICPR_NVIC_PERIPHERAL9_ENA

#define NVIC_ICPR1_R_NVIC_RTC_ALARM_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL9_BIT
#define NVIC_ICPR1_R_NVIC_RTC_ALARM_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL9_MASK
#define NVIC_ICPR1_R_NVIC_RTC_ALARM_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL9_DIS
#define NVIC_ICPR1_R_NVIC_RTC_ALARM_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL9_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_OTG_FS_WKUP_MASK    NVIC_ICPR_NVIC_PERIPHERAL10_MASK
#define NVIC_ICPR1_NVIC_OTG_FS_WKUP_DIS    NVIC_ICPR_NVIC_PERIPHERAL10_DIS
#define NVIC_ICPR1_NVIC_OTG_FS_WKUP_ENA    NVIC_ICPR_NVIC_PERIPHERAL10_ENA

#define NVIC_ICPR1_R_NVIC_OTG_FS_WKUP_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL10_BIT
#define NVIC_ICPR1_R_NVIC_OTG_FS_WKUP_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL10_MASK
#define NVIC_ICPR1_R_NVIC_OTG_FS_WKUP_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL10_DIS
#define NVIC_ICPR1_R_NVIC_OTG_FS_WKUP_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL10_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM8_BRK_TIM12_MASK    NVIC_ICPR_NVIC_PERIPHERAL11_MASK
#define NVIC_ICPR1_NVIC_TIM8_BRK_TIM12_DIS    NVIC_ICPR_NVIC_PERIPHERAL11_DIS
#define NVIC_ICPR1_NVIC_TIM8_BRK_TIM12_ENA    NVIC_ICPR_NVIC_PERIPHERAL11_ENA

#define NVIC_ICPR1_R_NVIC_TIM8_BRK_TIM12_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL11_BIT
#define NVIC_ICPR1_R_NVIC_TIM8_BRK_TIM12_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL11_MASK
#define NVIC_ICPR1_R_NVIC_TIM8_BRK_TIM12_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL11_DIS
#define NVIC_ICPR1_R_NVIC_TIM8_BRK_TIM12_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL11_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM8_UP_TIM13_MASK    NVIC_ICPR_NVIC_PERIPHERAL12_MASK
#define NVIC_ICPR1_NVIC_TIM8_UP_TIM13_DIS    NVIC_ICPR_NVIC_PERIPHERAL12_DIS
#define NVIC_ICPR1_NVIC_TIM8_UP_TIM13_ENA    NVIC_ICPR_NVIC_PERIPHERAL12_ENA

#define NVIC_ICPR1_R_NVIC_TIM8_UP_TIM13_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL12_BIT
#define NVIC_ICPR1_R_NVIC_TIM8_UP_TIM13_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL12_MASK
#define NVIC_ICPR1_R_NVIC_TIM8_UP_TIM13_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL12_DIS
#define NVIC_ICPR1_R_NVIC_TIM8_UP_TIM13_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL12_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM8_TRG_COM_TIM14_MASK    NVIC_ICPR_NVIC_PERIPHERAL13_MASK
#define NVIC_ICPR1_NVIC_TIM8_TRG_COM_TIM14_DIS    NVIC_ICPR_NVIC_PERIPHERAL13_DIS
#define NVIC_ICPR1_NVIC_TIM8_TRG_COM_TIM14_ENA    NVIC_ICPR_NVIC_PERIPHERAL13_ENA

#define NVIC_ICPR1_R_NVIC_TIM8_TRG_COM_TIM14_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL13_BIT
#define NVIC_ICPR1_R_NVIC_TIM8_TRG_COM_TIM14_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL13_MASK
#define NVIC_ICPR1_R_NVIC_TIM8_TRG_COM_TIM14_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL13_DIS
#define NVIC_ICPR1_R_NVIC_TIM8_TRG_COM_TIM14_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL13_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM8_CC_MASK    NVIC_ICPR_NVIC_PERIPHERAL14_MASK
#define NVIC_ICPR1_NVIC_TIM8_CC_DIS    NVIC_ICPR_NVIC_PERIPHERAL14_DIS
#define NVIC_ICPR1_NVIC_TIM8_CC_ENA    NVIC_ICPR_NVIC_PERIPHERAL14_ENA

#define NVIC_ICPR1_R_NVIC_TIM8_CC_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL14_BIT
#define NVIC_ICPR1_R_NVIC_TIM8_CC_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL14_MASK
#define NVIC_ICPR1_R_NVIC_TIM8_CC_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL14_DIS
#define NVIC_ICPR1_R_NVIC_TIM8_CC_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL14_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_DMA1_STREAM7_MASK    NVIC_ICPR_NVIC_PERIPHERAL15_MASK
#define NVIC_ICPR1_NVIC_DMA1_STREAM7_DIS    NVIC_ICPR_NVIC_PERIPHERAL15_DIS
#define NVIC_ICPR1_NVIC_DMA1_STREAM7_ENA    NVIC_ICPR_NVIC_PERIPHERAL15_ENA

#define NVIC_ICPR1_R_NVIC_DMA1_STREAM7_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL15_BIT
#define NVIC_ICPR1_R_NVIC_DMA1_STREAM7_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL15_MASK
#define NVIC_ICPR1_R_NVIC_DMA1_STREAM7_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL15_DIS
#define NVIC_ICPR1_R_NVIC_DMA1_STREAM7_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL15_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_FMC_MASK    NVIC_ICPR_NVIC_PERIPHERAL16_MASK
#define NVIC_ICPR1_NVIC_FMC_DIS    NVIC_ICPR_NVIC_PERIPHERAL16_DIS
#define NVIC_ICPR1_NVIC_FMC_ENA    NVIC_ICPR_NVIC_PERIPHERAL16_ENA

#define NVIC_ICPR1_R_NVIC_FMC_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL16_BIT
#define NVIC_ICPR1_R_NVIC_FMC_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL16_MASK
#define NVIC_ICPR1_R_NVIC_FMC_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL16_DIS
#define NVIC_ICPR1_R_NVIC_FMC_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL16_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_SDMMC1_MASK    NVIC_ICPR_NVIC_PERIPHERAL17_MASK
#define NVIC_ICPR1_NVIC_SDMMC1_DIS    NVIC_ICPR_NVIC_PERIPHERAL17_DIS
#define NVIC_ICPR1_NVIC_SDMMC1_ENA    NVIC_ICPR_NVIC_PERIPHERAL17_ENA

#define NVIC_ICPR1_R_NVIC_SDMMC1_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL17_BIT
#define NVIC_ICPR1_R_NVIC_SDMMC1_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL17_MASK
#define NVIC_ICPR1_R_NVIC_SDMMC1_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL17_DIS
#define NVIC_ICPR1_R_NVIC_SDMMC1_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL17_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM5_MASK    NVIC_ICPR_NVIC_PERIPHERAL18_MASK
#define NVIC_ICPR1_NVIC_TIM5_DIS    NVIC_ICPR_NVIC_PERIPHERAL18_DIS
#define NVIC_ICPR1_NVIC_TIM5_ENA    NVIC_ICPR_NVIC_PERIPHERAL18_ENA

#define NVIC_ICPR1_R_NVIC_TIM5_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL18_BIT
#define NVIC_ICPR1_R_NVIC_TIM5_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL18_MASK
#define NVIC_ICPR1_R_NVIC_TIM5_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL18_DIS
#define NVIC_ICPR1_R_NVIC_TIM5_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL18_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_SPI3_MASK    NVIC_ICPR_NVIC_PERIPHERAL19_MASK
#define NVIC_ICPR1_NVIC_SPI3_DIS    NVIC_ICPR_NVIC_PERIPHERAL19_DIS
#define NVIC_ICPR1_NVIC_SPI3_ENA    NVIC_ICPR_NVIC_PERIPHERAL19_ENA

#define NVIC_ICPR1_R_NVIC_SPI3_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL19_BIT
#define NVIC_ICPR1_R_NVIC_SPI3_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL19_MASK
#define NVIC_ICPR1_R_NVIC_SPI3_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL19_DIS
#define NVIC_ICPR1_R_NVIC_SPI3_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL19_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_UART4_MASK    NVIC_ICPR_NVIC_PERIPHERAL20_MASK
#define NVIC_ICPR1_NVIC_UART4_DIS    NVIC_ICPR_NVIC_PERIPHERAL20_DIS
#define NVIC_ICPR1_NVIC_UART4_ENA    NVIC_ICPR_NVIC_PERIPHERAL20_ENA

#define NVIC_ICPR1_R_NVIC_UART4_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL20_BIT
#define NVIC_ICPR1_R_NVIC_UART4_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL20_MASK
#define NVIC_ICPR1_R_NVIC_UART4_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL20_DIS
#define NVIC_ICPR1_R_NVIC_UART4_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL20_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_UART5_MASK    NVIC_ICPR_NVIC_PERIPHERAL21_MASK
#define NVIC_ICPR1_NVIC_UART5_DIS    NVIC_ICPR_NVIC_PERIPHERAL21_DIS
#define NVIC_ICPR1_NVIC_UART5_ENA    NVIC_ICPR_NVIC_PERIPHERAL21_ENA

#define NVIC_ICPR1_R_NVIC_UART5_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL21_BIT
#define NVIC_ICPR1_R_NVIC_UART5_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL21_MASK
#define NVIC_ICPR1_R_NVIC_UART5_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL21_DIS
#define NVIC_ICPR1_R_NVIC_UART5_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL21_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM6_DAC_MASK    NVIC_ICPR_NVIC_PERIPHERAL22_MASK
#define NVIC_ICPR1_NVIC_TIM6_DAC_DIS    NVIC_ICPR_NVIC_PERIPHERAL22_DIS
#define NVIC_ICPR1_NVIC_TIM6_DAC_ENA    NVIC_ICPR_NVIC_PERIPHERAL22_ENA

#define NVIC_ICPR1_R_NVIC_TIM6_DAC_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL22_BIT
#define NVIC_ICPR1_R_NVIC_TIM6_DAC_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL22_MASK
#define NVIC_ICPR1_R_NVIC_TIM6_DAC_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL22_DIS
#define NVIC_ICPR1_R_NVIC_TIM6_DAC_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL22_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_TIM7_MASK    NVIC_ICPR_NVIC_PERIPHERAL23_MASK
#define NVIC_ICPR1_NVIC_TIM7_DIS    NVIC_ICPR_NVIC_PERIPHERAL23_DIS
#define NVIC_ICPR1_NVIC_TIM7_ENA    NVIC_ICPR_NVIC_PERIPHERAL23_ENA

#define NVIC_ICPR1_R_NVIC_TIM7_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL23_BIT
#define NVIC_ICPR1_R_NVIC_TIM7_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL23_MASK
#define NVIC_ICPR1_R_NVIC_TIM7_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL23_DIS
#define NVIC_ICPR1_R_NVIC_TIM7_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL23_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_DMA2_STREAM0_MASK    NVIC_ICPR_NVIC_PERIPHERAL24_MASK
#define NVIC_ICPR1_NVIC_DMA2_STREAM0_DIS    NVIC_ICPR_NVIC_PERIPHERAL24_DIS
#define NVIC_ICPR1_NVIC_DMA2_STREAM0_ENA    NVIC_ICPR_NVIC_PERIPHERAL24_ENA

#define NVIC_ICPR1_R_NVIC_DMA2_STREAM0_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL24_BIT
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM0_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL24_MASK
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM0_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL24_DIS
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM0_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL24_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_DMA2_STREAM1_MASK    NVIC_ICPR_NVIC_PERIPHERAL25_MASK
#define NVIC_ICPR1_NVIC_DMA2_STREAM1_DIS    NVIC_ICPR_NVIC_PERIPHERAL25_DIS
#define NVIC_ICPR1_NVIC_DMA2_STREAM1_ENA    NVIC_ICPR_NVIC_PERIPHERAL25_ENA

#define NVIC_ICPR1_R_NVIC_DMA2_STREAM1_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL25_BIT
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM1_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL25_MASK
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM1_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL25_DIS
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM1_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL25_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_DMA2_STREAM2_MASK    NVIC_ICPR_NVIC_PERIPHERAL26_MASK
#define NVIC_ICPR1_NVIC_DMA2_STREAM2_DIS    NVIC_ICPR_NVIC_PERIPHERAL26_DIS
#define NVIC_ICPR1_NVIC_DMA2_STREAM2_ENA    NVIC_ICPR_NVIC_PERIPHERAL26_ENA

#define NVIC_ICPR1_R_NVIC_DMA2_STREAM2_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL26_BIT
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM2_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL26_MASK
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM2_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL26_DIS
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM2_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL26_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_DMA2_STREAM3_MASK    NVIC_ICPR_NVIC_PERIPHERAL27_MASK
#define NVIC_ICPR1_NVIC_DMA2_STREAM3_DIS    NVIC_ICPR_NVIC_PERIPHERAL27_DIS
#define NVIC_ICPR1_NVIC_DMA2_STREAM3_ENA    NVIC_ICPR_NVIC_PERIPHERAL27_ENA

#define NVIC_ICPR1_R_NVIC_DMA2_STREAM3_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL27_BIT
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM3_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL27_MASK
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM3_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL27_DIS
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM3_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL27_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_DMA2_STREAM4_MASK    NVIC_ICPR_NVIC_PERIPHERAL28_MASK
#define NVIC_ICPR1_NVIC_DMA2_STREAM4_DIS    NVIC_ICPR_NVIC_PERIPHERAL28_DIS
#define NVIC_ICPR1_NVIC_DMA2_STREAM4_ENA    NVIC_ICPR_NVIC_PERIPHERAL28_ENA

#define NVIC_ICPR1_R_NVIC_DMA2_STREAM4_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL28_BIT
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM4_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL28_MASK
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM4_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL28_DIS
#define NVIC_ICPR1_R_NVIC_DMA2_STREAM4_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL28_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_ETH_MASK    NVIC_ICPR_NVIC_PERIPHERAL29_MASK
#define NVIC_ICPR1_NVIC_ETH_DIS    NVIC_ICPR_NVIC_PERIPHERAL29_DIS
#define NVIC_ICPR1_NVIC_ETH_ENA    NVIC_ICPR_NVIC_PERIPHERAL29_ENA

#define NVIC_ICPR1_R_NVIC_ETH_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL29_BIT
#define NVIC_ICPR1_R_NVIC_ETH_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL29_MASK
#define NVIC_ICPR1_R_NVIC_ETH_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL29_DIS
#define NVIC_ICPR1_R_NVIC_ETH_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL29_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_ETH_WKUP_MASK    NVIC_ICPR_NVIC_PERIPHERAL30_MASK
#define NVIC_ICPR1_NVIC_ETH_WKUP_DIS    NVIC_ICPR_NVIC_PERIPHERAL30_DIS
#define NVIC_ICPR1_NVIC_ETH_WKUP_ENA    NVIC_ICPR_NVIC_PERIPHERAL30_ENA

#define NVIC_ICPR1_R_NVIC_ETH_WKUP_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL30_BIT
#define NVIC_ICPR1_R_NVIC_ETH_WKUP_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL30_MASK
#define NVIC_ICPR1_R_NVIC_ETH_WKUP_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL30_DIS
#define NVIC_ICPR1_R_NVIC_ETH_WKUP_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL30_ENA
/*----------*/

/*----------*/
#define NVIC_ICPR1_NVIC_CAN2_TX_MASK    NVIC_ICPR_NVIC_PERIPHERAL31_MASK
#define NVIC_ICPR1_NVIC_CAN2_TX_DIS    NVIC_ICPR_NVIC_PERIPHERAL31_DIS
#define NVIC_ICPR1_NVIC_CAN2_TX_ENA    NVIC_ICPR_NVIC_PERIPHERAL31_ENA

#define NVIC_ICPR1_R_NVIC_CAN2_TX_BIT    NVIC_ICPR_R_NVIC_PERIPHERAL31_BIT
#define NVIC_ICPR1_R_NVIC_CAN2_TX_MASK    NVIC_ICPR_R_NVIC_PERIPHERAL31_MASK
#define NVIC_ICPR1_R_NVIC_CAN2_TX_DIS    NVIC_ICPR_R_NVIC_PERIPHERAL31_DIS
#define NVIC_ICPR1_R_NVIC_CAN2_TX_ENA    NVIC_ICPR_R_NVIC_PERIPHERAL31_ENA
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET1_NVIC_REGISTERDEFINES_SET1_ICPR_H_ */
