/**
 *
 * @file NVIC_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 19 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 19 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Enum.h>

typedef enum
{
    NVIC_enERROR_OK = (UBase_t) MCU_enERROR_OK,
    NVIC_enERROR_POINTER = (UBase_t) MCU_enERROR_POINTER,
    NVIC_enERROR_VALUE = (UBase_t) MCU_enERROR_VALUE,
    NVIC_enERROR_RANGE = (UBase_t) MCU_enERROR_RANGE,
    NVIC_enERROR_UNDEF = (UBase_t) MCU_enERROR_UNDEF,
}NVIC_nERROR;

typedef enum
{
    NVIC_enSTATE_DIS = (UBase_t) MCU_enSTATE_DIS,
    NVIC_enSTATE_ENA = (UBase_t) MCU_enSTATE_ENA,
    NVIC_enSTATE_UNDEF = (UBase_t) MCU_enSTATE_UNDEF,
}NVIC_nSTATE;

typedef enum
{
    NVIC_enFALSE = (UBase_t) FALSE,
    NVIC_enTRUE = (UBase_t) TRUE,
    NVIC_enBOOLEAN_UNDEF = (UBase_t) BOOLEAN_UNDEF,
}NVIC_nBOOLEAN;

typedef enum
{
    NVIC_enSTATUS_INACTIVE = (UBase_t) MCU_enSTATUS_INACTIVE,
    NVIC_enSTATUS_ACTIVE = (UBase_t) MCU_enSTATUS_ACTIVE,
    NVIC_enSTATUS_UNDEF = (UBase_t) MCU_enSTATUS_UNDEF,
}NVIC_nSTATUS;

typedef enum
{
    NVIC_enPRI0 = (UBase_t) MCU_enPRI0,
    NVIC_enPRI1 = (UBase_t) MCU_enPRI1,
    NVIC_enPRI2 = (UBase_t) MCU_enPRI2,
    NVIC_enPRI3 = (UBase_t) MCU_enPRI3,
    NVIC_enPRI4 = (UBase_t) MCU_enPRI4,
    NVIC_enPRI5 = (UBase_t) MCU_enPRI5,
    NVIC_enPRI6 = (UBase_t) MCU_enPRI6,
    NVIC_enPRI7 = (UBase_t) MCU_enPRI7,
    NVIC_enPRI8 = (UBase_t) MCU_enPRI8,
    NVIC_enPRI9 = (UBase_t) MCU_enPRI9,
    NVIC_enPRI10 = (UBase_t) MCU_enPRI10,
    NVIC_enPRI11 = (UBase_t) MCU_enPRI11,
    NVIC_enPRI12 = (UBase_t) MCU_enPRI12,
    NVIC_enPRI13 = (UBase_t) MCU_enPRI13,
    NVIC_enPRI14 = (UBase_t) MCU_enPRI14,
    NVIC_enPRI15 = (UBase_t) MCU_enPRI15,
    NVIC_enPRIMAX = (UBase_t) MCU_enPRIMAX,
    NVIC_enDEFAULT = (UBase_t) MCU_enDEFAULT,
    NVIC_enPRI_UNDEF = (UBase_t) MCU_enDEFAULT,
}NVIC_nPRIORITY;

typedef enum
{
    NVIC_enMODULE_0 = 0UL,
    NVIC_enMODULE_MAX = 1UL,
    NVIC_enMODULE_UNDEF = UNDEF_VALUE,
}NVIC_nMODULE;

typedef enum
{
     NVIC_enVECTOR_WWDT = 0UL,
     NVIC_enVECTOR_PVD = 1UL,
     NVIC_enVECTOR_TAMP_STAMP = 2UL,
     NVIC_enVECTOR_RTC_WKUP = 3UL,
     NVIC_enVECTOR_FLASH = 4UL,
     NVIC_enVECTOR_RCC = 5UL,
     NVIC_enVECTOR_EXTI0 = 6UL,
     NVIC_enVECTOR_EXTI1 = 7UL,
     NVIC_enVECTOR_EXTI2 = 8UL,
     NVIC_enVECTOR_EXTI3 = 9UL,
     NVIC_enVECTOR_EXTI4 = 10UL,
     NVIC_enVECTOR_DMA1_STREAM0 = 11UL,
     NVIC_enVECTOR_DMA1_STREAM1 = 12UL,
     NVIC_enVECTOR_DMA1_STREAM2 = 13UL,
     NVIC_enVECTOR_DMA1_STREAM3 = 14UL,
     NVIC_enVECTOR_DMA1_STREAM4 = 15UL,
     NVIC_enVECTOR_DMA1_STREAM5 = 16UL,
     NVIC_enVECTOR_DMA1_STREAM6 = 17UL,
     NVIC_enVECTOR_ADC = 18UL,
     NVIC_enVECTOR_CAN1_TX = 19UL,
     NVIC_enVECTOR_CAN1_RX0 = 20UL,
     NVIC_enVECTOR_CAN1_RX1 = 21UL,
     NVIC_enVECTOR_CAN1_SCE = 22UL,
     NVIC_enVECTOR_EXTI9_5 = 23UL,
     NVIC_enVECTOR_TIM1_BRK_TIM9 = 24UL,
     NVIC_enVECTOR_TIM1_UP_TIM10 = 25UL,
     NVIC_enVECTOR_TIM1_TRG_COM_TIM11 = 26UL,
     NVIC_enVECTOR_TIM1_CC = 27UL,
     NVIC_enVECTOR_TIM2 = 28UL,
     NVIC_enVECTOR_TIM3 = 29UL,
     NVIC_enVECTOR_TIM4 = 30UL,
     NVIC_enVECTOR_I2C1_EV = 31UL,
     NVIC_enVECTOR_I2C1_ER = 32UL,
     NVIC_enVECTOR_I2C2_EV = 33UL,
     NVIC_enVECTOR_I2C2_ER = 34UL,
     NVIC_enVECTOR_SPI1 = 35UL,
     NVIC_enVECTOR_SPI2 = 36UL,
     NVIC_enVECTOR_USART1 = 37UL,
     NVIC_enVECTOR_USART2 = 38UL,
     NVIC_enVECTOR_USART3 = 39UL,
     NVIC_enVECTOR_EXTI15_10 = 40UL,
     NVIC_enVECTOR_RTC_ALARM = 41UL,
     NVIC_enVECTOR_OTG_FS_WKUP = 42UL,
     NVIC_enVECTOR_TIM8_BRK_TIM12 = 43UL,
     NVIC_enVECTOR_TIM8_UP_TIM13 = 44UL,
     NVIC_enVECTOR_TIM8_TRG_COM_TIM14 = 45UL,
     NVIC_enVECTOR_TIM8_CC = 46UL,
     NVIC_enVECTOR_DMA1_STREAM7 = 47UL,
     NVIC_enVECTOR_FMC = 48UL,
     NVIC_enVECTOR_SDMMC1 = 49UL,
     NVIC_enVECTOR_TIM5 = 50UL,
     NVIC_enVECTOR_SPI3 = 51UL,
     NVIC_enVECTOR_UART4 = 52UL,
     NVIC_enVECTOR_UART5 = 53UL,
     NVIC_enVECTOR_TIM6_DAC = 54UL,
     NVIC_enVECTOR_TIM7 = 55UL,
     NVIC_enVECTOR_DMA2_STREAM0 = 56UL,
     NVIC_enVECTOR_DMA2_STREAM1 = 57UL,
     NVIC_enVECTOR_DMA2_STREAM2 = 58UL,
     NVIC_enVECTOR_DMA2_STREAM3 = 59UL,
     NVIC_enVECTOR_DMA2_STREAM4 = 60UL,
     NVIC_enVECTOR_ETH = 61UL,
     NVIC_enVECTOR_ETH_WKUP = 62UL,
     NVIC_enVECTOR_CAN2_TX = 63UL,
     NVIC_enVECTOR_CAN2_RX0 = 64UL,
     NVIC_enVECTOR_CAN2_RX1 = 65UL,
     NVIC_enVECTOR_CAN2_SCE = 66UL,
     NVIC_enVECTOR_OTG_FS = 67UL,
     NVIC_enVECTOR_DMA2_STREAM5 = 68UL,
     NVIC_enVECTOR_DMA2_STREAM6 = 69UL,
     NVIC_enVECTOR_DMA2_STREAM7 = 70UL,
     NVIC_enVECTOR_USART6 = 71UL,
     NVIC_enVECTOR_I2C3_EV = 72UL,
     NVIC_enVECTOR_I2C3_ER = 73UL,
     NVIC_enVECTOR_OTG_HS_EP1_OUT = 74UL,
     NVIC_enVECTOR_OTG_HS_EP1_IN = 75UL,
     NVIC_enVECTOR_OTG_HS_WKUP = 76UL,
     NVIC_enVECTOR_OTG_HS = 77UL,
     NVIC_enVECTOR_DCMI = 78UL,
     NVIC_enVECTOR_CRYP = 79UL,
     NVIC_enVECTOR_HASH_RNG = 80UL,
     NVIC_enVECTOR_FPU = 81UL,
     NVIC_enVECTOR_UART7 = 82UL,
     NVIC_enVECTOR_UART8 = 83UL,
     NVIC_enVECTOR_SPI4 = 84UL,
     NVIC_enVECTOR_SPI5 = 85UL,
     NVIC_enVECTOR_SPI6 = 86UL,
     NVIC_enVECTOR_SAI1 = 87UL,
     NVIC_enVECTOR_LCD_TFT = 88UL,
     NVIC_enVECTOR_LCD_TFT_ER = 89UL,
     NVIC_enVECTOR_DMA2D = 90UL,
     NVIC_enVECTOR_SAI2 = 91UL,
     NVIC_enVECTOR_QSPI = 92UL,
     NVIC_enVECTOR_LPTIM1 = 93UL,
     NVIC_enVECTOR_HDMI_CEC = 94UL,
     NVIC_enVECTOR_I2C4_EV = 95UL,
     NVIC_enVECTOR_I2C4_ER = 96UL,
     NVIC_enVECTOR_SPDIF_RX = 97UL,
     NVIC_enVECTOR_DSI_HOST = 98UL,
     NVIC_enVECTOR_DFSDM1_FLT0 = 99UL,
     NVIC_enVECTOR_DFSDM1_FLT1 = 100UL,
     NVIC_enVECTOR_DFSDM1_FLT2 = 101UL,
     NVIC_enVECTOR_DFSDM1_FLT3 = 102UL,
     NVIC_enVECTOR_SDMMC2 = 103UL,
     NVIC_enVECTOR_CAN3_TX = 104UL,
     NVIC_enVECTOR_CAN3_RX0 = 105UL,
     NVIC_enVECTOR_CAN3_RX1 = 106UL,
     NVIC_enVECTOR_CAN3_SCE = 107UL,
     NVIC_enVECTOR_JPEG = 108UL,
     NVIC_enVECTOR_MDIO_SLAVE = 109UL,
     NVIC_enVECTOR_MAX = 110UL,
     NVIC_enVECTOR_UNDEF = UNDEF_VALUE,
}NVIC_nVECTOR;

typedef enum
{
/******  Cortex-M4 Processor Exceptions Numbers ****************************************************************/
      ThreadMode_IRQn = -16,
      Reset_IRQn = -15,
      NonMaskableInt_IRQn = -14,    /*!< 2 Non Maskable Interrupt                                          */
      HardFault_IRQn = -13,
      MemoryManagement_IRQn = -12,    /*!< 4 Cortex-M4 Memory Management Interrupt                           */
      BusFault_IRQn = -11,    /*!< 5 Cortex-M4 Bus Fault Interrupt                                   */
      UsageFault_IRQn = -10,    /*!< 6 Cortex-M4 Usage Fault Interrupt                                 */
      SVCall_IRQn = -5,     /*!< 11 Cortex-M4 SV Call Interrupt                                    */
      DebugMonitor_IRQn = -4,     /*!< 12 Cortex-M4 Debug Monitor Interrupt                              */
      PendSV_IRQn = -2,     /*!< 14 Cortex-M4 Pend SV Interrupt                                    */
      SYSTICK_IRQn = -1,     /*!< 15 Cortex-M4 System Tick Interrupt                                */
/******  TM4C specific Interrupt Numbers **********************************************************************/
      WWDT_IRQn = 0,
      PVD_IRQn = 1,
      TAMP_STAMP_IRQn = 2,
      RTC_WKUP_IRQn = 3,
      FLASH_IRQn = 4,
      RCC_IRQn = 5,
      EXTI0_IRQn = 6,
      EXTI1_IRQn = 7,
      EXTI2_IRQn = 8,
      EXTI3_IRQn = 9,
      EXTI4_IRQn = 10,
      DMA1_STREAM0_IRQn = 11,
      DMA1_STREAM1_IRQn= 12,
      DMA1_STREAM2_IRQn = 13,
      DMA1_STREAM3_IRQn = 14,
      DMA1_STREAM4_IRQn = 15,
      DMA1_STREAM5_IRQn = 16,
      DMA1_STREAM6_IRQn = 17,
      ADC_IRQn = 18,
      CAN1_TX_IRQn = 19,
      CAN1_RX0_IRQn = 20,
      CAN1_RX1_IRQn = 21,
      CAN1_SCE_IRQn = 22,
      EXTI9_5_IRQn = 23,
      TIM1_BRK_TIM9_IRQn = 24,
      TIM1_UP_TIM10_IRQn = 25,
      TIM1_TRG_COM_TIM11_IRQn = 26,
      TIM1_CC_IRQn = 27,
      TIM2_IRQn = 28,
      TIM3_IRQn = 29,
      TIM4_IRQn = 30,
      I2C1_EV_IRQn = 31,
      I2C1_ER_IRQn = 32,
      I2C2_EV_IRQn = 33,
      I2C2_ER_IRQn = 34,
      SPI1_IRQn = 35,
      SPI2_IRQn = 36,
      USART1_IRQn = 37,
      USART2_IRQn = 38,
      USART3_IRQn = 39,
      EXTI15_10_IRQn = 40,
      RTC_ALARM_IRQn = 41,
      OTG_FS_WKUP_IRQn = 42,
      TIM8_BRK_TIM12_IRQn = 43,
      TIM8_UP_TIM13_IRQn = 44,
      TIM8_TRG_COM_TIM14_IRQn = 45,
      TIM8_CC_IRQn = 46,
      DMA1_STREAM7_IRQn = 47,
      FMC_IRQn = 48,
      SDMMC1_IRQn = 49,
      TIM5_IRQn = 50,
      SPI3_IRQn = 51,
      UART4_IRQn = 52,
      UART5_IRQn = 53,
      TIM6_DAC_IRQn = 54,
      TIM7_IRQn = 55,
      DMA2_STREAM0_IRQn = 56,
      DMA2_STREAM1_IRQn = 57,
      DMA2_STREAM2_IRQn = 58,
      DMA2_STREAM3_IRQn = 59,
      DMA2_STREAM4_IRQn = 60,
      ETH_IRQn = 61,
      ETH_WKUP_IRQn = 62,
      CAN2_TX_IRQn = 63,
      CAN2_RX0_IRQn = 64,
      CAN2_RX1_IRQn = 65,
      CAN2_SCE_IRQn = 66,
      OTG_FS_IRQn = 67,
      DMA2_STREAM5_IRQn = 68,
      DMA2_STREAM6_IRQn = 69,
      DMA2_STREAM7_IRQn = 70,
      USART6_IRQn = 71,
      I2C3_EV_IRQn = 72,
      I2C3_ER_IRQn = 73,
      OTG_HS_EP1_OUT_IRQn = 74,
      OTG_HS_EP1_IN_IRQn = 75,
      OTG_HS_WHUP_IRQn = 76,
      OTG_HS_IRQn = 77,
      DCMI_IRQn = 78,
      CRYP_IRQn = 79,
      HASH_RNG_IRQn = 80,
      FPU_IRQn = 81,
      UART7_IRQn = 82,
      UART8_IRQn = 83,
      SPI4_IRQn = 84,
      SPI5_IRQn = 85,
      SPI6_IRQn = 86,
      SAI1_IRQn = 87,
      LCD_TFT_IRQn = 88,
      LCD_TFT_ER_IRQn = 89,
      DMA2D_IRQn = 90,
      SAI2_IRQn = 91,
      QSPI_IRQn = 92,
      LPTIM1_IRQn = 93,
      HDMI_CEC_IRQn = 94,
      I2C4_EV_IRQn = 95,
      I2C4_ER_IRQn = 96,
      SPDIF_RX_IRQn = 97,
      DSI_HOST_IRQn = 98,
      DFSDM1_FLT0_IRQn = 99,
      DFSDM1_FLT1_IRQn = 100,
      DFSDM1_FLT2_IRQn = 101,
      DFSDM1_FLT3_IRQn = 102,
      SDMMC2_IRQn = 103,
      CAN3_TX_IRQn = 104,
      CAN3_RX0_IRQn = 105,
      CAN3_RX1_IRQn = 106,
      CAN3_SCE_IRQn = 107,
      JPEG_IRQn = 108,
      MDIO_SLAVE_IRQn = 109,
      UNDEF_IRQn = UNDEF_VALUE,
}IRQn_Type;

typedef enum
{

    NVIC_enVECTOR_PRI_WWDT = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_PVD = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TAMP_STAMP = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_RTC_WKUP = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_FLASH = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_RCC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI4 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM4 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM5 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM6 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_ADC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN1_TX = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN1_RX0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN1_RX1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN1_SCE = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI9_5 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM1_BRK_TIM9 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM1_UP_TIM10 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM1_TRG_COM_TIM11 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM1_CC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM4 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C1_EV = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C1_ER = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C2_EV = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C2_ER = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPI1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPI2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_USART1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_USART2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_USART3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_EXTI15_10 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_RTC_ALARM = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_OTG_FS_WKUP = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM8_BRK_TIM12 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM8_UP_TIM13 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM8_TRG_COM_TIM14 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM8_CC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA1_STREAM7 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_FMC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SDMMC1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM5 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPI3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_UART4 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_UART5 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM6_DAC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_TIM7 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM4 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_ETH = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_ETH_WKUP = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN2_TX = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN2_RX0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN2_RX1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN2_SCE = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_OTG_FS = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM5 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM6 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2_STREAM7 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_USART6 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C3_EV = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C3_ER = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_OTG_HS_EP1_OUT = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_OTG_HS_EP1_IN = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_OTG_HS_WHUP = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_OTG_HS = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DCMI = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CRYP = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_HASH_RNG = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_FPU = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_UART7 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_UART8 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPI4 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPI5 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPI6 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SAI1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_LCD_TFT = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_LCD_TFT_ER = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DMA2D = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SAI2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_QSPI = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_LPTIM1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_HDMI_CEC = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C4_EV = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_I2C4_ER = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SPDIF_RX = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DSI_HOST = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DFSDM1_FLT0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DFSDM1_FLT1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DFSDM1_FLT2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_DFSDM1_FLT3 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_SDMMC2 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN3_TX = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN3_RX0 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN3_RX1 = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_CAN3_SCE = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_JPEG = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_MDIO_SLAVE = (UBase_t) MCU_enPRI15,
    NVIC_enVECTOR_PRI_UNDEF = UNDEF_VALUE,

}NVIC_nVECTOR_PRI;

typedef MCU_Register_t NVIC_Register_t;
typedef MCU_pvfIRQSourceHandler_t NVIC_pvfIRQSourceHandler_t;


#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_ENUM_H_ */
