/**
 *
 * @file NVIC_RegisterDefines_Set2_ISPR.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET2_NVIC_REGISTERDEFINES_SET2_ISPR_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET2_NVIC_REGISTERDEFINES_SET2_ISPR_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_Set/RegisterDefines_Set_Generic/NVIC_RegisterDefines_Set_Generic.h>

/********************************************************************************************/
/************************************* ISPR2 ***********************************************/
/********************************************************************************************/

/*----------*/
#define NVIC_ISPR2_NVIC_CAN2_RX0_MASK    NVIC_ISPR_NVIC_PERIPHERAL0_MASK
#define NVIC_ISPR2_NVIC_CAN2_RX0_DIS    NVIC_ISPR_NVIC_PERIPHERAL0_DIS
#define NVIC_ISPR2_NVIC_CAN2_RX0_ENA    NVIC_ISPR_NVIC_PERIPHERAL0_ENA

#define NVIC_ISPR2_R_NVIC_CAN2_RX0_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_ISPR2_R_NVIC_CAN2_RX0_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_ISPR2_R_NVIC_CAN2_RX0_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL0_DIS
#define NVIC_ISPR2_R_NVIC_CAN2_RX0_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL0_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_CAN2_RX1_MASK    NVIC_ISPR_NVIC_PERIPHERAL1_MASK
#define NVIC_ISPR2_NVIC_CAN2_RX1_DIS    NVIC_ISPR_NVIC_PERIPHERAL1_DIS
#define NVIC_ISPR2_NVIC_CAN2_RX1_ENA    NVIC_ISPR_NVIC_PERIPHERAL1_ENA

#define NVIC_ISPR2_R_NVIC_CAN2_RX1_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_ISPR2_R_NVIC_CAN2_RX1_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_ISPR2_R_NVIC_CAN2_RX1_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL1_DIS
#define NVIC_ISPR2_R_NVIC_CAN2_RX1_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL1_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_CAN2_SCE_MASK    NVIC_ISPR_NVIC_PERIPHERAL2_MASK
#define NVIC_ISPR2_NVIC_CAN2_SCE_DIS    NVIC_ISPR_NVIC_PERIPHERAL2_DIS
#define NVIC_ISPR2_NVIC_CAN2_SCE_ENA    NVIC_ISPR_NVIC_PERIPHERAL2_ENA

#define NVIC_ISPR2_R_NVIC_CAN2_SCE_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_ISPR2_R_NVIC_CAN2_SCE_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_ISPR2_R_NVIC_CAN2_SCE_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL2_DIS
#define NVIC_ISPR2_R_NVIC_CAN2_SCE_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL2_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_OTG_FS_MASK    NVIC_ISPR_NVIC_PERIPHERAL3_MASK
#define NVIC_ISPR2_NVIC_OTG_FS_DIS    NVIC_ISPR_NVIC_PERIPHERAL3_DIS
#define NVIC_ISPR2_NVIC_OTG_FS_ENA    NVIC_ISPR_NVIC_PERIPHERAL3_ENA

#define NVIC_ISPR2_R_NVIC_OTG_FS_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_ISPR2_R_NVIC_OTG_FS_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_ISPR2_R_NVIC_OTG_FS_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL3_DIS
#define NVIC_ISPR2_R_NVIC_OTG_FS_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL3_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_DMA2_STREAM5_MASK    NVIC_ISPR_NVIC_PERIPHERAL4_MASK
#define NVIC_ISPR2_NVIC_DMA2_STREAM5_DIS    NVIC_ISPR_NVIC_PERIPHERAL4_DIS
#define NVIC_ISPR2_NVIC_DMA2_STREAM5_ENA    NVIC_ISPR_NVIC_PERIPHERAL4_ENA

#define NVIC_ISPR2_R_NVIC_DMA2_STREAM5_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL4_BIT
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM5_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL4_MASK
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM5_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL4_DIS
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM5_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL4_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_DMA2_STREAM6_MASK    NVIC_ISPR_NVIC_PERIPHERAL5_MASK
#define NVIC_ISPR2_NVIC_DMA2_STREAM6_DIS    NVIC_ISPR_NVIC_PERIPHERAL5_DIS
#define NVIC_ISPR2_NVIC_DMA2_STREAM6_ENA    NVIC_ISPR_NVIC_PERIPHERAL5_ENA

#define NVIC_ISPR2_R_NVIC_DMA2_STREAM6_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL5_BIT
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM6_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL5_MASK
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM6_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL5_DIS
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM6_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL5_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_DMA2_STREAM7_MASK    NVIC_ISPR_NVIC_PERIPHERAL6_MASK
#define NVIC_ISPR2_NVIC_DMA2_STREAM7_DIS    NVIC_ISPR_NVIC_PERIPHERAL6_DIS
#define NVIC_ISPR2_NVIC_DMA2_STREAM7_ENA    NVIC_ISPR_NVIC_PERIPHERAL6_ENA

#define NVIC_ISPR2_R_NVIC_DMA2_STREAM7_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL6_BIT
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM7_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL6_MASK
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM7_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL6_DIS
#define NVIC_ISPR2_R_NVIC_DMA2_STREAM7_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL6_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_USART6_MASK    NVIC_ISPR_NVIC_PERIPHERAL7_MASK
#define NVIC_ISPR2_NVIC_USART6_DIS    NVIC_ISPR_NVIC_PERIPHERAL7_DIS
#define NVIC_ISPR2_NVIC_USART6_ENA    NVIC_ISPR_NVIC_PERIPHERAL7_ENA

#define NVIC_ISPR2_R_NVIC_USART6_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL7_BIT
#define NVIC_ISPR2_R_NVIC_USART6_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL7_MASK
#define NVIC_ISPR2_R_NVIC_USART6_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL7_DIS
#define NVIC_ISPR2_R_NVIC_USART6_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL7_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_I2C3_EV_MASK    NVIC_ISPR_NVIC_PERIPHERAL8_MASK
#define NVIC_ISPR2_NVIC_I2C3_EV_DIS    NVIC_ISPR_NVIC_PERIPHERAL8_DIS
#define NVIC_ISPR2_NVIC_I2C3_EV_ENA    NVIC_ISPR_NVIC_PERIPHERAL8_ENA

#define NVIC_ISPR2_R_NVIC_I2C3_EV_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL8_BIT
#define NVIC_ISPR2_R_NVIC_I2C3_EV_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL8_MASK
#define NVIC_ISPR2_R_NVIC_I2C3_EV_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL8_DIS
#define NVIC_ISPR2_R_NVIC_I2C3_EV_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL8_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_I2C3_ER_MASK    NVIC_ISPR_NVIC_PERIPHERAL9_MASK
#define NVIC_ISPR2_NVIC_I2C3_ER_DIS    NVIC_ISPR_NVIC_PERIPHERAL9_DIS
#define NVIC_ISPR2_NVIC_I2C3_ER_ENA    NVIC_ISPR_NVIC_PERIPHERAL9_ENA

#define NVIC_ISPR2_R_NVIC_I2C3_ER_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL9_BIT
#define NVIC_ISPR2_R_NVIC_I2C3_ER_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL9_MASK
#define NVIC_ISPR2_R_NVIC_I2C3_ER_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL9_DIS
#define NVIC_ISPR2_R_NVIC_I2C3_ER_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL9_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_OTG_HS_EP1_OUT_MASK    NVIC_ISPR_NVIC_PERIPHERAL10_MASK
#define NVIC_ISPR2_NVIC_OTG_HS_EP1_OUT_DIS    NVIC_ISPR_NVIC_PERIPHERAL10_DIS
#define NVIC_ISPR2_NVIC_OTG_HS_EP1_OUT_ENA    NVIC_ISPR_NVIC_PERIPHERAL10_ENA

#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_OUT_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL10_BIT
#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_OUT_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL10_MASK
#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_OUT_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL10_DIS
#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_OUT_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL10_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_OTG_HS_EP1_IN_MASK    NVIC_ISPR_NVIC_PERIPHERAL11_MASK
#define NVIC_ISPR2_NVIC_OTG_HS_EP1_IN_DIS    NVIC_ISPR_NVIC_PERIPHERAL11_DIS
#define NVIC_ISPR2_NVIC_OTG_HS_EP1_IN_ENA    NVIC_ISPR_NVIC_PERIPHERAL11_ENA

#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_IN_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL11_BIT
#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_IN_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL11_MASK
#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_IN_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL11_DIS
#define NVIC_ISPR2_R_NVIC_OTG_HS_EP1_IN_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL11_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_OTG_HS_WKUP_MASK    NVIC_ISPR_NVIC_PERIPHERAL12_MASK
#define NVIC_ISPR2_NVIC_OTG_HS_WKUP_DIS    NVIC_ISPR_NVIC_PERIPHERAL12_DIS
#define NVIC_ISPR2_NVIC_OTG_HS_WKUP_ENA    NVIC_ISPR_NVIC_PERIPHERAL12_ENA

#define NVIC_ISPR2_R_NVIC_OTG_HS_WKUP_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL12_BIT
#define NVIC_ISPR2_R_NVIC_OTG_HS_WKUP_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL12_MASK
#define NVIC_ISPR2_R_NVIC_OTG_HS_WKUP_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL12_DIS
#define NVIC_ISPR2_R_NVIC_OTG_HS_WKUP_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL12_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_OTG_HS_MASK    NVIC_ISPR_NVIC_PERIPHERAL13_MASK
#define NVIC_ISPR2_NVIC_OTG_HS_DIS    NVIC_ISPR_NVIC_PERIPHERAL13_DIS
#define NVIC_ISPR2_NVIC_OTG_HS_ENA    NVIC_ISPR_NVIC_PERIPHERAL13_ENA

#define NVIC_ISPR2_R_NVIC_OTG_HS_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL13_BIT
#define NVIC_ISPR2_R_NVIC_OTG_HS_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL13_MASK
#define NVIC_ISPR2_R_NVIC_OTG_HS_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL13_DIS
#define NVIC_ISPR2_R_NVIC_OTG_HS_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL13_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_DCMI_MASK    NVIC_ISPR_NVIC_PERIPHERAL14_MASK
#define NVIC_ISPR2_NVIC_DCMI_DIS    NVIC_ISPR_NVIC_PERIPHERAL14_DIS
#define NVIC_ISPR2_NVIC_DCMI_ENA    NVIC_ISPR_NVIC_PERIPHERAL14_ENA

#define NVIC_ISPR2_R_NVIC_DCMI_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL14_BIT
#define NVIC_ISPR2_R_NVIC_DCMI_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL14_MASK
#define NVIC_ISPR2_R_NVIC_DCMI_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL14_DIS
#define NVIC_ISPR2_R_NVIC_DCMI_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL14_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_CRYP_MASK    NVIC_ISPR_NVIC_PERIPHERAL15_MASK
#define NVIC_ISPR2_NVIC_CRYP_DIS    NVIC_ISPR_NVIC_PERIPHERAL15_DIS
#define NVIC_ISPR2_NVIC_CRYP_ENA    NVIC_ISPR_NVIC_PERIPHERAL15_ENA

#define NVIC_ISPR2_R_NVIC_CRYP_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL15_BIT
#define NVIC_ISPR2_R_NVIC_CRYP_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL15_MASK
#define NVIC_ISPR2_R_NVIC_CRYP_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL15_DIS
#define NVIC_ISPR2_R_NVIC_CRYP_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL15_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_HASH_RNG_MASK    NVIC_ISPR_NVIC_PERIPHERAL16_MASK
#define NVIC_ISPR2_NVIC_HASH_RNG_DIS    NVIC_ISPR_NVIC_PERIPHERAL16_DIS
#define NVIC_ISPR2_NVIC_HASH_RNG_ENA    NVIC_ISPR_NVIC_PERIPHERAL16_ENA

#define NVIC_ISPR2_R_NVIC_HASH_RNG_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL16_BIT
#define NVIC_ISPR2_R_NVIC_HASH_RNG_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL16_MASK
#define NVIC_ISPR2_R_NVIC_HASH_RNG_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL16_DIS
#define NVIC_ISPR2_R_NVIC_HASH_RNG_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL16_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_FPU_MASK    NVIC_ISPR_NVIC_PERIPHERAL17_MASK
#define NVIC_ISPR2_NVIC_FPU_DIS    NVIC_ISPR_NVIC_PERIPHERAL17_DIS
#define NVIC_ISPR2_NVIC_FPU_ENA    NVIC_ISPR_NVIC_PERIPHERAL17_ENA

#define NVIC_ISPR2_R_NVIC_FPU_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL17_BIT
#define NVIC_ISPR2_R_NVIC_FPU_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL17_MASK
#define NVIC_ISPR2_R_NVIC_FPU_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL17_DIS
#define NVIC_ISPR2_R_NVIC_FPU_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL17_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_UART7_MASK    NVIC_ISPR_NVIC_PERIPHERAL18_MASK
#define NVIC_ISPR2_NVIC_UART7_DIS    NVIC_ISPR_NVIC_PERIPHERAL18_DIS
#define NVIC_ISPR2_NVIC_UART7_ENA    NVIC_ISPR_NVIC_PERIPHERAL18_ENA

#define NVIC_ISPR2_R_NVIC_UART7_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL18_BIT
#define NVIC_ISPR2_R_NVIC_UART7_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL18_MASK
#define NVIC_ISPR2_R_NVIC_UART7_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL18_DIS
#define NVIC_ISPR2_R_NVIC_UART7_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL18_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_UART8_MASK    NVIC_ISPR_NVIC_PERIPHERAL19_MASK
#define NVIC_ISPR2_NVIC_UART8_DIS    NVIC_ISPR_NVIC_PERIPHERAL19_DIS
#define NVIC_ISPR2_NVIC_UART8_ENA    NVIC_ISPR_NVIC_PERIPHERAL19_ENA

#define NVIC_ISPR2_R_NVIC_UART8_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL19_BIT
#define NVIC_ISPR2_R_NVIC_UART8_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL19_MASK
#define NVIC_ISPR2_R_NVIC_UART8_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL19_DIS
#define NVIC_ISPR2_R_NVIC_UART8_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL19_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_SPI4_MASK    NVIC_ISPR_NVIC_PERIPHERAL20_MASK
#define NVIC_ISPR2_NVIC_SPI4_DIS    NVIC_ISPR_NVIC_PERIPHERAL20_DIS
#define NVIC_ISPR2_NVIC_SPI4_ENA    NVIC_ISPR_NVIC_PERIPHERAL20_ENA

#define NVIC_ISPR2_R_NVIC_SPI4_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL20_BIT
#define NVIC_ISPR2_R_NVIC_SPI4_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL20_MASK
#define NVIC_ISPR2_R_NVIC_SPI4_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL20_DIS
#define NVIC_ISPR2_R_NVIC_SPI4_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL20_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_SPI5_MASK    NVIC_ISPR_NVIC_PERIPHERAL21_MASK
#define NVIC_ISPR2_NVIC_SPI5_DIS    NVIC_ISPR_NVIC_PERIPHERAL21_DIS
#define NVIC_ISPR2_NVIC_SPI5_ENA    NVIC_ISPR_NVIC_PERIPHERAL21_ENA

#define NVIC_ISPR2_R_NVIC_SPI5_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL21_BIT
#define NVIC_ISPR2_R_NVIC_SPI5_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL21_MASK
#define NVIC_ISPR2_R_NVIC_SPI5_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL21_DIS
#define NVIC_ISPR2_R_NVIC_SPI5_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL21_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_SPI6_MASK    NVIC_ISPR_NVIC_PERIPHERAL22_MASK
#define NVIC_ISPR2_NVIC_SPI6_DIS    NVIC_ISPR_NVIC_PERIPHERAL22_DIS
#define NVIC_ISPR2_NVIC_SPI6_ENA    NVIC_ISPR_NVIC_PERIPHERAL22_ENA

#define NVIC_ISPR2_R_NVIC_SPI6_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL22_BIT
#define NVIC_ISPR2_R_NVIC_SPI6_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL22_MASK
#define NVIC_ISPR2_R_NVIC_SPI6_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL22_DIS
#define NVIC_ISPR2_R_NVIC_SPI6_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL22_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_SAI1_MASK    NVIC_ISPR_NVIC_PERIPHERAL23_MASK
#define NVIC_ISPR2_NVIC_SAI1_DIS    NVIC_ISPR_NVIC_PERIPHERAL23_DIS
#define NVIC_ISPR2_NVIC_SAI1_ENA    NVIC_ISPR_NVIC_PERIPHERAL23_ENA

#define NVIC_ISPR2_R_NVIC_SAI1_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL23_BIT
#define NVIC_ISPR2_R_NVIC_SAI1_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL23_MASK
#define NVIC_ISPR2_R_NVIC_SAI1_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL23_DIS
#define NVIC_ISPR2_R_NVIC_SAI1_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL23_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_LCD_TFT_MASK    NVIC_ISPR_NVIC_PERIPHERAL24_MASK
#define NVIC_ISPR2_NVIC_LCD_TFT_DIS    NVIC_ISPR_NVIC_PERIPHERAL24_DIS
#define NVIC_ISPR2_NVIC_LCD_TFT_ENA    NVIC_ISPR_NVIC_PERIPHERAL24_ENA

#define NVIC_ISPR2_R_NVIC_LCD_TFT_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL24_BIT
#define NVIC_ISPR2_R_NVIC_LCD_TFT_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL24_MASK
#define NVIC_ISPR2_R_NVIC_LCD_TFT_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL24_DIS
#define NVIC_ISPR2_R_NVIC_LCD_TFT_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL24_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_LCD_TFT_ER_MASK    NVIC_ISPR_NVIC_PERIPHERAL25_MASK
#define NVIC_ISPR2_NVIC_LCD_TFT_ER_DIS    NVIC_ISPR_NVIC_PERIPHERAL25_DIS
#define NVIC_ISPR2_NVIC_LCD_TFT_ER_ENA    NVIC_ISPR_NVIC_PERIPHERAL25_ENA

#define NVIC_ISPR2_R_NVIC_LCD_TFT_ER_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL25_BIT
#define NVIC_ISPR2_R_NVIC_LCD_TFT_ER_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL25_MASK
#define NVIC_ISPR2_R_NVIC_LCD_TFT_ER_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL25_DIS
#define NVIC_ISPR2_R_NVIC_LCD_TFT_ER_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL25_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_DMA2D_MASK    NVIC_ISPR_NVIC_PERIPHERAL26_MASK
#define NVIC_ISPR2_NVIC_DMA2D_DIS    NVIC_ISPR_NVIC_PERIPHERAL26_DIS
#define NVIC_ISPR2_NVIC_DMA2D_ENA    NVIC_ISPR_NVIC_PERIPHERAL26_ENA

#define NVIC_ISPR2_R_NVIC_DMA2D_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL26_BIT
#define NVIC_ISPR2_R_NVIC_DMA2D_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL26_MASK
#define NVIC_ISPR2_R_NVIC_DMA2D_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL26_DIS
#define NVIC_ISPR2_R_NVIC_DMA2D_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL26_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_SAI2_MASK    NVIC_ISPR_NVIC_PERIPHERAL27_MASK
#define NVIC_ISPR2_NVIC_SAI2_DIS    NVIC_ISPR_NVIC_PERIPHERAL27_DIS
#define NVIC_ISPR2_NVIC_SAI2_ENA    NVIC_ISPR_NVIC_PERIPHERAL27_ENA

#define NVIC_ISPR2_R_NVIC_SAI2_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL27_BIT
#define NVIC_ISPR2_R_NVIC_SAI2_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL27_MASK
#define NVIC_ISPR2_R_NVIC_SAI2_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL27_DIS
#define NVIC_ISPR2_R_NVIC_SAI2_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL27_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_QSPI_MASK    NVIC_ISPR_NVIC_PERIPHERAL28_MASK
#define NVIC_ISPR2_NVIC_QSPI_DIS    NVIC_ISPR_NVIC_PERIPHERAL28_DIS
#define NVIC_ISPR2_NVIC_QSPI_ENA    NVIC_ISPR_NVIC_PERIPHERAL28_ENA

#define NVIC_ISPR2_R_NVIC_QSPI_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL28_BIT
#define NVIC_ISPR2_R_NVIC_QSPI_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL28_MASK
#define NVIC_ISPR2_R_NVIC_QSPI_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL28_DIS
#define NVIC_ISPR2_R_NVIC_QSPI_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL28_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_LPTIM1_MASK    NVIC_ISPR_NVIC_PERIPHERAL29_MASK
#define NVIC_ISPR2_NVIC_LPTIM1_DIS    NVIC_ISPR_NVIC_PERIPHERAL29_DIS
#define NVIC_ISPR2_NVIC_LPTIM1_ENA    NVIC_ISPR_NVIC_PERIPHERAL29_ENA

#define NVIC_ISPR2_R_NVIC_LPTIM1_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL29_BIT
#define NVIC_ISPR2_R_NVIC_LPTIM1_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL29_MASK
#define NVIC_ISPR2_R_NVIC_LPTIM1_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL29_DIS
#define NVIC_ISPR2_R_NVIC_LPTIM1_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL29_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_HDMI_CEC_MASK    NVIC_ISPR_NVIC_PERIPHERAL30_MASK
#define NVIC_ISPR2_NVIC_HDMI_CEC_DIS    NVIC_ISPR_NVIC_PERIPHERAL30_DIS
#define NVIC_ISPR2_NVIC_HDMI_CEC_ENA    NVIC_ISPR_NVIC_PERIPHERAL30_ENA

#define NVIC_ISPR2_R_NVIC_HDMI_CEC_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL30_BIT
#define NVIC_ISPR2_R_NVIC_HDMI_CEC_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL30_MASK
#define NVIC_ISPR2_R_NVIC_HDMI_CEC_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL30_DIS
#define NVIC_ISPR2_R_NVIC_HDMI_CEC_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL30_ENA
/*----------*/

/*----------*/
#define NVIC_ISPR2_NVIC_I2C4_EV_MASK    NVIC_ISPR_NVIC_PERIPHERAL31_MASK
#define NVIC_ISPR2_NVIC_I2C4_EV_DIS    NVIC_ISPR_NVIC_PERIPHERAL31_DIS
#define NVIC_ISPR2_NVIC_I2C4_EV_ENA    NVIC_ISPR_NVIC_PERIPHERAL31_ENA

#define NVIC_ISPR2_R_NVIC_I2C4_EV_BIT    NVIC_ISPR_R_NVIC_PERIPHERAL31_BIT
#define NVIC_ISPR2_R_NVIC_I2C4_EV_MASK    NVIC_ISPR_R_NVIC_PERIPHERAL31_MASK
#define NVIC_ISPR2_R_NVIC_I2C4_EV_DIS    NVIC_ISPR_R_NVIC_PERIPHERAL31_DIS
#define NVIC_ISPR2_R_NVIC_I2C4_EV_ENA    NVIC_ISPR_R_NVIC_PERIPHERAL31_ENA
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET2_NVIC_REGISTERDEFINES_SET2_ISPR_H_ */
