/**
 *
 * @file NVIC_RegisterDefines_STIR.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 22 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_STIR_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_STIR_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/xHeader/NVIC_Enum.h>

/********************************************************************************************/
/************************************* STIR ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_STIR_R_INTID_MASK    ((UBase_t) 0x000000FFUL)
#define NVIC_STIR_R_INTID_BIT    ((UBase_t) 0UL)
#define NVIC_STIR_R_INTID_WWDT    ((UBase_t) 0UL)
#define NVIC_STIR_R_INTID_PVD    ((UBase_t) 1UL)
#define NVIC_STIR_R_INTID_TAMP_STAMP    ((UBase_t) 2UL)
#define NVIC_STIR_R_INTID_RTC_WKUP    ((UBase_t) 3UL)
#define NVIC_STIR_R_INTID_FLASH    ((UBase_t) 4UL)
#define NVIC_STIR_R_INTID_RCC    ((UBase_t) 5UL)
#define NVIC_STIR_R_INTID_EXTI0    ((UBase_t) 6UL)
#define NVIC_STIR_R_INTID_EXTI1    ((UBase_t) 7UL)
#define NVIC_STIR_R_INTID_EXTI2    ((UBase_t) 8UL)
#define NVIC_STIR_R_INTID_EXTI3    ((UBase_t) 9UL)
#define NVIC_STIR_R_INTID_EXTI4    ((UBase_t) 10UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM0    ((UBase_t) 11UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM1    ((UBase_t) 12UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM2    ((UBase_t) 13UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM3    ((UBase_t) 14UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM4    ((UBase_t) 15UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM5    ((UBase_t) 16UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM6    ((UBase_t) 17UL)
#define NVIC_STIR_R_INTID_ADC    ((UBase_t) 18UL)
#define NVIC_STIR_R_INTID_CAN1_TX    ((UBase_t) 19UL)
#define NVIC_STIR_R_INTID_CAN1_RX0    ((UBase_t) 20UL)
#define NVIC_STIR_R_INTID_CAN1_RX1    ((UBase_t) 21UL)
#define NVIC_STIR_R_INTID_CAN1_SCE    ((UBase_t) 22UL)
#define NVIC_STIR_R_INTID_EXTI9_5    ((UBase_t) 23UL)
#define NVIC_STIR_R_INTID_TIM1_BRK_TIM9    ((UBase_t) 24UL)
#define NVIC_STIR_R_INTID_TIM1_UP_TIM10    ((UBase_t) 25UL)
#define NVIC_STIR_R_INTID_TIM1_TRG_COM_TIM11    ((UBase_t) 26UL)
#define NVIC_STIR_R_INTID_TIM1_CC    ((UBase_t) 27UL)
#define NVIC_STIR_R_INTID_TIM2    ((UBase_t) 28UL)
#define NVIC_STIR_R_INTID_TIM3    ((UBase_t) 29UL)
#define NVIC_STIR_R_INTID_TIM4    ((UBase_t) 30UL)
#define NVIC_STIR_R_INTID_I2C1_EV    ((UBase_t) 31UL)
#define NVIC_STIR_R_INTID_I2C1_ER    ((UBase_t) 32UL)
#define NVIC_STIR_R_INTID_I2C2_EV    ((UBase_t) 33UL)
#define NVIC_STIR_R_INTID_I2C2_ER    ((UBase_t) 34UL)
#define NVIC_STIR_R_INTID_SPI1    ((UBase_t) 35UL)
#define NVIC_STIR_R_INTID_SPI2    ((UBase_t) 36UL)
#define NVIC_STIR_R_INTID_USART1    ((UBase_t) 37UL)
#define NVIC_STIR_R_INTID_USART2    ((UBase_t) 38UL)
#define NVIC_STIR_R_INTID_USART3    ((UBase_t) 39UL)
#define NVIC_STIR_R_INTID_EXTI15_10    ((UBase_t) 40UL)
#define NVIC_STIR_R_INTID_RTC_ALARM    ((UBase_t) 41UL)
#define NVIC_STIR_R_INTID_OTG_FS_WKUP    ((UBase_t) 42UL)
#define NVIC_STIR_R_INTID_TIM8_BRK_TIM12    ((UBase_t) 43UL)
#define NVIC_STIR_R_INTID_TIM8_UP_TIM13    ((UBase_t) 44UL)
#define NVIC_STIR_R_INTID_TIM8_TRG_COM_TIM14    ((UBase_t) 45UL)
#define NVIC_STIR_R_INTID_TIM8_CC    ((UBase_t) 46UL)
#define NVIC_STIR_R_INTID_DMA1_STREAM7    ((UBase_t) 47UL)
#define NVIC_STIR_R_INTID_FMC    ((UBase_t) 48UL)
#define NVIC_STIR_R_INTID_SDMMC1    ((UBase_t) 49UL)
#define NVIC_STIR_R_INTID_TIM5    ((UBase_t) 50UL)
#define NVIC_STIR_R_INTID_SPI3    ((UBase_t) 51UL)
#define NVIC_STIR_R_INTID_UART4    ((UBase_t) 52UL)
#define NVIC_STIR_R_INTID_UART5    ((UBase_t) 53UL)
#define NVIC_STIR_R_INTID_TIM6_DAC    ((UBase_t) 54UL)
#define NVIC_STIR_R_INTID_TIM7    ((UBase_t) 55UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM0    ((UBase_t) 56UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM1    ((UBase_t) 57UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM2    ((UBase_t) 58UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM3    ((UBase_t) 59UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM4    ((UBase_t) 60UL)
#define NVIC_STIR_R_INTID_ETH    ((UBase_t) 61UL)
#define NVIC_STIR_R_INTID_ETH_WKUP    ((UBase_t) 62UL)
#define NVIC_STIR_R_INTID_CAN2_TX    ((UBase_t) 63UL)
#define NVIC_STIR_R_INTID_CAN2_RX0    ((UBase_t) 64UL)
#define NVIC_STIR_R_INTID_CAN2_RX1    ((UBase_t) 65UL)
#define NVIC_STIR_R_INTID_CAN2_SCE    ((UBase_t) 66UL)
#define NVIC_STIR_R_INTID_OTG_FS    ((UBase_t) 67UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM5    ((UBase_t) 68UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM6    ((UBase_t) 69UL)
#define NVIC_STIR_R_INTID_DMA2_STREAM7    ((UBase_t) 70UL)
#define NVIC_STIR_R_INTID_USART6    ((UBase_t) 71UL)
#define NVIC_STIR_R_INTID_I2C3_EV    ((UBase_t) 72UL)
#define NVIC_STIR_R_INTID_I2C3_ER    ((UBase_t) 73UL)
#define NVIC_STIR_R_INTID_OTG_HS_EP1_OUT    ((UBase_t) 74UL)
#define NVIC_STIR_R_INTID_OTG_HS_EP1_IN    ((UBase_t) 75UL)
#define NVIC_STIR_R_INTID_OTG_HS_WKUP    ((UBase_t) 76UL)
#define NVIC_STIR_R_INTID_OTG_HS    ((UBase_t) 77UL)
#define NVIC_STIR_R_INTID_DCMI    ((UBase_t) 78UL)
#define NVIC_STIR_R_INTID_CRYP    ((UBase_t) 79UL)
#define NVIC_STIR_R_INTID_HASH_RNG    ((UBase_t) 80UL)
#define NVIC_STIR_R_INTID_FPU    ((UBase_t) 81UL)
#define NVIC_STIR_R_INTID_UART7    ((UBase_t) 82UL)
#define NVIC_STIR_R_INTID_UART8    ((UBase_t) 83UL)
#define NVIC_STIR_R_INTID_SPI4    ((UBase_t) 84UL)
#define NVIC_STIR_R_INTID_SPI5    ((UBase_t) 85UL)
#define NVIC_STIR_R_INTID_SPI6    ((UBase_t) 86UL)
#define NVIC_STIR_R_INTID_SAI1    ((UBase_t) 87UL)
#define NVIC_STIR_R_INTID_LCD_TFT    ((UBase_t) 88UL)
#define NVIC_STIR_R_INTID_LCD_TFT_ER    ((UBase_t) 89UL)
#define NVIC_STIR_R_INTID_DMA2D    ((UBase_t) 90UL)
#define NVIC_STIR_R_INTID_SAI2    ((UBase_t) 91UL)
#define NVIC_STIR_R_INTID_QSPI    ((UBase_t) 92UL)
#define NVIC_STIR_R_INTID_LPTIM1    ((UBase_t) 93UL)
#define NVIC_STIR_R_INTID_HDMI_CEC    ((UBase_t) 94UL)
#define NVIC_STIR_R_INTID_I2C4_EV    ((UBase_t) 95UL)
#define NVIC_STIR_R_INTID_I2C4_ER    ((UBase_t) 96UL)
#define NVIC_STIR_R_INTID_SPDIF_RX    ((UBase_t) 97UL)
#define NVIC_STIR_R_INTID_DSI_HOST    ((UBase_t) 98UL)
#define NVIC_STIR_R_INTID_DFSDM1_FLT0    ((UBase_t) 99UL)
#define NVIC_STIR_R_INTID_DFSDM1_FLT1    ((UBase_t) 100UL)
#define NVIC_STIR_R_INTID_DFSDM1_FLT2    ((UBase_t) 101UL)
#define NVIC_STIR_R_INTID_DFSDM1_FLT3    ((UBase_t) 102UL)
#define NVIC_STIR_R_INTID_SDMMC2    ((UBase_t) 103UL)
#define NVIC_STIR_R_INTID_CAN3_TX    ((UBase_t) 104UL)
#define NVIC_STIR_R_INTID_CAN3_RX0    ((UBase_t) 105UL)
#define NVIC_STIR_R_INTID_CAN3_RX1    ((UBase_t) 106UL)
#define NVIC_STIR_R_INTID_CAN3_SCE    ((UBase_t) 107UL)
#define NVIC_STIR_R_INTID_JPEG    ((UBase_t) 108UL)
#define NVIC_STIR_R_INTID_MDIO_SLAVE    ((UBase_t) 109UL)

#define NVIC_STIR_INTID_MASK    ((UBase_t) 0x000000FFUL)
#define NVIC_STIR_INTID_BIT    ((UBase_t) 0UL)
#define NVIC_STIR_INTID_WWDT    ((UBase_t) 0UL)
#define NVIC_STIR_INTID_PVD    ((UBase_t) 1UL)
#define NVIC_STIR_INTID_TAMP_STAMP    ((UBase_t) 2UL)
#define NVIC_STIR_INTID_RTC_WKUP    ((UBase_t) 3UL)
#define NVIC_STIR_INTID_FLASH    ((UBase_t) 4UL)
#define NVIC_STIR_INTID_RCC    ((UBase_t) 5UL)
#define NVIC_STIR_INTID_EXTI0    ((UBase_t) 6UL)
#define NVIC_STIR_INTID_EXTI1    ((UBase_t) 7UL)
#define NVIC_STIR_INTID_EXTI2    ((UBase_t) 8UL)
#define NVIC_STIR_INTID_EXTI3    ((UBase_t) 9UL)
#define NVIC_STIR_INTID_EXTI4    ((UBase_t) 10UL)
#define NVIC_STIR_INTID_DMA1_STREAM0    ((UBase_t) 11UL)
#define NVIC_STIR_INTID_DMA1_STREAM1    ((UBase_t) 12UL)
#define NVIC_STIR_INTID_DMA1_STREAM2    ((UBase_t) 13UL)
#define NVIC_STIR_INTID_DMA1_STREAM3    ((UBase_t) 14UL)
#define NVIC_STIR_INTID_DMA1_STREAM4    ((UBase_t) 15UL)
#define NVIC_STIR_INTID_DMA1_STREAM5    ((UBase_t) 16UL)
#define NVIC_STIR_INTID_DMA1_STREAM6    ((UBase_t) 17UL)
#define NVIC_STIR_INTID_ADC    ((UBase_t) 18UL)
#define NVIC_STIR_INTID_CAN1_TX    ((UBase_t) 19UL)
#define NVIC_STIR_INTID_CAN1_RX0    ((UBase_t) 20UL)
#define NVIC_STIR_INTID_CAN1_RX1    ((UBase_t) 21UL)
#define NVIC_STIR_INTID_CAN1_SCE    ((UBase_t) 22UL)
#define NVIC_STIR_INTID_EXTI9_5    ((UBase_t) 23UL)
#define NVIC_STIR_INTID_TIM1_BRK_TIM9    ((UBase_t) 24UL)
#define NVIC_STIR_INTID_TIM1_UP_TIM10    ((UBase_t) 25UL)
#define NVIC_STIR_INTID_TIM1_TRG_COM_TIM11    ((UBase_t) 26UL)
#define NVIC_STIR_INTID_TIM1_CC    ((UBase_t) 27UL)
#define NVIC_STIR_INTID_TIM2    ((UBase_t) 28UL)
#define NVIC_STIR_INTID_TIM3    ((UBase_t) 29UL)
#define NVIC_STIR_INTID_TIM4    ((UBase_t) 30UL)
#define NVIC_STIR_INTID_I2C1_EV    ((UBase_t) 31UL)
#define NVIC_STIR_INTID_I2C1_ER    ((UBase_t) 32UL)
#define NVIC_STIR_INTID_I2C2_EV    ((UBase_t) 33UL)
#define NVIC_STIR_INTID_I2C2_ER    ((UBase_t) 34UL)
#define NVIC_STIR_INTID_SPI1    ((UBase_t) 35UL)
#define NVIC_STIR_INTID_SPI2    ((UBase_t) 36UL)
#define NVIC_STIR_INTID_USART1    ((UBase_t) 37UL)
#define NVIC_STIR_INTID_USART2    ((UBase_t) 38UL)
#define NVIC_STIR_INTID_USART3    ((UBase_t) 39UL)
#define NVIC_STIR_INTID_EXTI15_10    ((UBase_t) 40UL)
#define NVIC_STIR_INTID_RTC_ALARM    ((UBase_t) 41UL)
#define NVIC_STIR_INTID_OTG_FS_WKUP    ((UBase_t) 42UL)
#define NVIC_STIR_INTID_TIM8_BRK_TIM12    ((UBase_t) 43UL)
#define NVIC_STIR_INTID_TIM8_UP_TIM13    ((UBase_t) 44UL)
#define NVIC_STIR_INTID_TIM8_TRG_COM_TIM14    ((UBase_t) 45UL)
#define NVIC_STIR_INTID_TIM8_CC    ((UBase_t) 46UL)
#define NVIC_STIR_INTID_DMA1_STREAM7    ((UBase_t) 47UL)
#define NVIC_STIR_INTID_FMC    ((UBase_t) 48UL)
#define NVIC_STIR_INTID_SDMMC1    ((UBase_t) 49UL)
#define NVIC_STIR_INTID_TIM5    ((UBase_t) 50UL)
#define NVIC_STIR_INTID_SPI3    ((UBase_t) 51UL)
#define NVIC_STIR_INTID_UART4    ((UBase_t) 52UL)
#define NVIC_STIR_INTID_UART5    ((UBase_t) 53UL)
#define NVIC_STIR_INTID_TIM6_DAC    ((UBase_t) 54UL)
#define NVIC_STIR_INTID_TIM7    ((UBase_t) 55UL)
#define NVIC_STIR_INTID_DMA2_STREAM0    ((UBase_t) 56UL)
#define NVIC_STIR_INTID_DMA2_STREAM1    ((UBase_t) 57UL)
#define NVIC_STIR_INTID_DMA2_STREAM2    ((UBase_t) 58UL)
#define NVIC_STIR_INTID_DMA2_STREAM3    ((UBase_t) 59UL)
#define NVIC_STIR_INTID_DMA2_STREAM4    ((UBase_t) 60UL)
#define NVIC_STIR_INTID_ETH    ((UBase_t) 61UL)
#define NVIC_STIR_INTID_ETH_WKUP    ((UBase_t) 62UL)
#define NVIC_STIR_INTID_CAN2_TX    ((UBase_t) 63UL)
#define NVIC_STIR_INTID_CAN2_RX0    ((UBase_t) 64UL)
#define NVIC_STIR_INTID_CAN2_RX1    ((UBase_t) 65UL)
#define NVIC_STIR_INTID_CAN2_SCE    ((UBase_t) 66UL)
#define NVIC_STIR_INTID_OTG_FS    ((UBase_t) 67UL)
#define NVIC_STIR_INTID_DMA2_STREAM5    ((UBase_t) 68UL)
#define NVIC_STIR_INTID_DMA2_STREAM6    ((UBase_t) 69UL)
#define NVIC_STIR_INTID_DMA2_STREAM7    ((UBase_t) 70UL)
#define NVIC_STIR_INTID_USART6    ((UBase_t) 71UL)
#define NVIC_STIR_INTID_I2C3_EV    ((UBase_t) 72UL)
#define NVIC_STIR_INTID_I2C3_ER    ((UBase_t) 73UL)
#define NVIC_STIR_INTID_OTG_HS_EP1_OUT    ((UBase_t) 74UL)
#define NVIC_STIR_INTID_OTG_HS_EP1_IN    ((UBase_t) 75UL)
#define NVIC_STIR_INTID_OTG_HS_WKUP    ((UBase_t) 76UL)
#define NVIC_STIR_INTID_OTG_HS    ((UBase_t) 77UL)
#define NVIC_STIR_INTID_DCMI    ((UBase_t) 78UL)
#define NVIC_STIR_INTID_CRYP    ((UBase_t) 79UL)
#define NVIC_STIR_INTID_HASH_RNG    ((UBase_t) 80UL)
#define NVIC_STIR_INTID_FPU    ((UBase_t) 81UL)
#define NVIC_STIR_INTID_UART7    ((UBase_t) 82UL)
#define NVIC_STIR_INTID_UART8    ((UBase_t) 83UL)
#define NVIC_STIR_INTID_SPI4    ((UBase_t) 84UL)
#define NVIC_STIR_INTID_SPI5    ((UBase_t) 85UL)
#define NVIC_STIR_INTID_SPI6    ((UBase_t) 86UL)
#define NVIC_STIR_INTID_SAI1    ((UBase_t) 87UL)
#define NVIC_STIR_INTID_LCD_TFT    ((UBase_t) 88UL)
#define NVIC_STIR_INTID_LCD_TFT_ER    ((UBase_t) 89UL)
#define NVIC_STIR_INTID_DMA2D    ((UBase_t) 90UL)
#define NVIC_STIR_INTID_SAI2    ((UBase_t) 91UL)
#define NVIC_STIR_INTID_QSPI    ((UBase_t) 92UL)
#define NVIC_STIR_INTID_LPTIM1    ((UBase_t) 93UL)
#define NVIC_STIR_INTID_HDMI_CEC    ((UBase_t) 94UL)
#define NVIC_STIR_INTID_I2C4_EV    ((UBase_t) 95UL)
#define NVIC_STIR_INTID_I2C4_ER    ((UBase_t) 96UL)
#define NVIC_STIR_INTID_SPDIF_RX    ((UBase_t) 97UL)
#define NVIC_STIR_INTID_DSI_HOST    ((UBase_t) 98UL)
#define NVIC_STIR_INTID_DFSDM1_FLT0    ((UBase_t) 99UL)
#define NVIC_STIR_INTID_DFSDM1_FLT1    ((UBase_t) 100UL)
#define NVIC_STIR_INTID_DFSDM1_FLT2    ((UBase_t) 101UL)
#define NVIC_STIR_INTID_DFSDM1_FLT3    ((UBase_t) 102UL)
#define NVIC_STIR_INTID_SDMMC2    ((UBase_t) 103UL)
#define NVIC_STIR_INTID_CAN3_TX    ((UBase_t) 104UL)
#define NVIC_STIR_INTID_CAN3_RX0    ((UBase_t) 105UL)
#define NVIC_STIR_INTID_CAN3_RX1    ((UBase_t) 106UL)
#define NVIC_STIR_INTID_CAN3_SCE    ((UBase_t) 107UL)
#define NVIC_STIR_INTID_JPEG    ((UBase_t) 108UL)
#define NVIC_STIR_INTID_MDIO_SLAVE    ((UBase_t) 109UL)
/*-----------------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_STIR_H_ */
