/**
 *
 * @file SCB_RegisterDefines.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date Author Version Description
 * 22 jun. 2020 vyldram 1.0 initial Version@endverbatim
 */
#ifndef XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_REGISTER_SCB_REGISTERDEFINES_H_
#define XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_REGISTER_SCB_REGISTERDEFINES_H_

#include <xDriver_MCU/Core/SCB/Peripheral/xHeader/SCB_Enum.h>
#include <xDriver_MCU/Core/SCB/Peripheral/Register/RegisterDefines/xHeader/SCB_RegisterDefines_INTCTLR.h>

/********************************************************************************************/
/************************************* 1 ICTLR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_ICTLR_INTLINESNUM_MASK    ((UBase_t) 0x1FUL)
#define SCB_ICTLR_INTLINESNUM_0_32    ((UBase_t) 0x00UL)
#define SCB_ICTLR_INTLINESNUM_33_64    ((UBase_t) 0x01UL)
#define SCB_ICTLR_INTLINESNUM_65_96    ((UBase_t) 0x02UL)
#define SCB_ICTLR_INTLINESNUM_97_128    ((UBase_t) 0x03UL)
#define SCB_ICTLR_INTLINESNUM_129_160    ((UBase_t) 0x04UL)
#define SCB_ICTLR_INTLINESNUM_161_192    ((UBase_t) 0x05UL)
#define SCB_ICTLR_INTLINESNUM_193_224    ((UBase_t) 0x06UL)
#define SCB_ICTLR_INTLINESNUM_225_256    ((UBase_t) 0x07UL)

#define SCB_ICTLR_R_INTLINESNUM_BIT    (0UL)

#define SCB_ICTLR_R_INTLINESNUM_MASK    (SCB_ICTLR_INTLINESNUM_MASK << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_0_32    (SCB_ICTLR_INTLINESNUM_0_32 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_33_64    (SCB_ICTLR_INTLINESNUM_33_64 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_65_96    (SCB_ICTLR_INTLINESNUM_65_96 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_97_128    (SCB_ICTLR_INTLINESNUM_97_128 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_129_160    (SCB_ICTLR_INTLINESNUM_129_160 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_161_192    (SCB_ICTLR_INTLINESNUM_161_192 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_193_224    (SCB_ICTLR_INTLINESNUM_193_224 << SCB_ICTLR_R_INTLINESNUM_BIT)
#define SCB_ICTLR_R_INTLINESNUM_225_256    (SCB_ICTLR_INTLINESNUM_225_256 << SCB_ICTLR_R_INTLINESNUM_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 2 ACTLR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_ACTLR_DISFOLD_MASK    ((UBase_t) 0x00000001UL)
#define SCB_ACTLR_DISFOLD_ENA    ((UBase_t) 0x00000000UL)
#define SCB_ACTLR_DISFOLD_DIS    ((UBase_t) 0x00000001UL)

#define SCB_ACTLR_R_DISFOLD_BIT    (2UL)

#define SCB_ACTLR_R_DISFOLD_MASK    (SCB_ACTLR_DISFOLD_MASK << SCB_ACTLR_R_DISFOLD_BIT)
#define SCB_ACTLR_R_DISFOLD_ENA    (SCB_ACTLR_DISFOLD_ENA << SCB_ACTLR_R_DISFOLD_BIT)
#define SCB_ACTLR_R_DISFOLD_DIS    (SCB_ACTLR_DISFOLD_DIS << SCB_ACTLR_R_DISFOLD_BIT)
/*----------*/

/*----------*/
#define SCB_ACTLR_FPEXCODIS_MASK    ((UBase_t) 0x00000001UL)
#define SCB_ACTLR_FPEXCODIS_ENA    ((UBase_t) 0x00000000UL)
#define SCB_ACTLR_FPEXCODIS_DIS    ((UBase_t) 0x00000001UL)

#define SCB_ACTLR_R_FPEXCODIS_BIT    (10UL)

#define SCB_ACTLR_R_FPEXCODIS_MASK    (SCB_ACTLR_FPEXCODIS_MASK << SCB_ACTLR_R_FPEXCODIS_BIT)
#define SCB_ACTLR_R_FPEXCODIS_ENA    (SCB_ACTLR_FPEXCODIS_ENA << SCB_ACTLR_R_FPEXCODIS_BIT)
#define SCB_ACTLR_R_FPEXCODIS_DIS    (SCB_ACTLR_FPEXCODIS_DIS << SCB_ACTLR_R_FPEXCODIS_BIT)
/*----------*/

/*----------*/
#define SCB_ACTLR_DISRAMODE_MASK    ((UBase_t) 0x00000001UL)
#define SCB_ACTLR_DISRAMODE_ENA    ((UBase_t) 0x00000000UL)
#define SCB_ACTLR_DISRAMODE_DIS    ((UBase_t) 0x00000001UL)

#define SCB_ACTLR_R_DISRAMODE_BIT    (11UL)

#define SCB_ACTLR_R_DISRAMODE_MASK    (SCB_ACTLR_DISRAMODE_MASK << SCB_ACTLR_R_DISRAMODE_BIT)
#define SCB_ACTLR_R_DISRAMODE_ENA    (SCB_ACTLR_DISRAMODE_ENA << SCB_ACTLR_R_DISRAMODE_BIT)
#define SCB_ACTLR_R_DISRAMODE_DIS    (SCB_ACTLR_DISRAMODE_DIS << SCB_ACTLR_R_DISRAMODE_BIT)
/*----------*/

/*----------*/
#define SCB_ACTLR_DISITMATBFLUSH_MASK    ((UBase_t) 0x00000001UL)
#define SCB_ACTLR_DISITMATBFLUSH_ENA    ((UBase_t) 0x00000000UL)
#define SCB_ACTLR_DISITMATBFLUSH_DIS    ((UBase_t) 0x00000001UL)

#define SCB_ACTLR_R_DISITMATBFLUSH_BIT    (12UL)

#define SCB_ACTLR_R_DISITMATBFLUSH_MASK    (SCB_ACTLR_DISITMATBFLUSH_MASK << SCB_ACTLR_R_DISITMATBFLUSH_BIT)
#define SCB_ACTLR_R_DISITMATBFLUSH_ENA    (SCB_ACTLR_DISITMATBFLUSH_ENA << SCB_ACTLR_R_DISITMATBFLUSH_BIT)
#define SCB_ACTLR_R_DISITMATBFLUSH_DIS    (SCB_ACTLR_DISITMATBFLUSH_DIS << SCB_ACTLR_R_DISITMATBFLUSH_BIT)
/*----------*/


/********************************************************************************************/
/************************************* 3 CPUID ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_CPUID_REVISION_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_CPUID_REVISION_rnp0    ((UBase_t) 0x00000000UL)
#define SCB_CPUID_REVISION_rnp1    ((UBase_t) 0x00000001UL)
#define SCB_CPUID_REVISION_rnp2    ((UBase_t) 0x00000002UL)
#define SCB_CPUID_REVISION_rnp3    ((UBase_t) 0x00000003UL)
#define SCB_CPUID_REVISION_rnp4    ((UBase_t) 0x00000004UL)
#define SCB_CPUID_REVISION_rnp5    ((UBase_t) 0x00000005UL)
#define SCB_CPUID_REVISION_rnp6    ((UBase_t) 0x00000006UL)
#define SCB_CPUID_REVISION_rnp7    ((UBase_t) 0x00000007UL)
#define SCB_CPUID_REVISION_rnp8    ((UBase_t) 0x00000008UL)
#define SCB_CPUID_REVISION_rnp9    ((UBase_t) 0x00000009UL)
#define SCB_CPUID_REVISION_rnp10    ((UBase_t) 0x0000000AUL)
#define SCB_CPUID_REVISION_rnp11    ((UBase_t) 0x0000000BUL)
#define SCB_CPUID_REVISION_rnp12    ((UBase_t) 0x0000000CUL)
#define SCB_CPUID_REVISION_rnp13    ((UBase_t) 0x0000000DUL)
#define SCB_CPUID_REVISION_rnp14    ((UBase_t) 0x0000000EUL)
#define SCB_CPUID_REVISION_rnp15    ((UBase_t) 0x0000000FUL)

#define SCB_CPUID_R_REVISION_BIT    (0UL)

#define SCB_CPUID_R_REVISION_MASK    (SCB_CPUID_REVISION_MASK << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp0    (SCB_CPUID_REVISION_rnp0 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp1    (SCB_CPUID_REVISION_rnp1 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp2    (SCB_CPUID_REVISION_rnp2 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp3    (SCB_CPUID_REVISION_rnp3 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp4    (SCB_CPUID_REVISION_rnp4 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp5    (SCB_CPUID_REVISION_rnp5 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp6    (SCB_CPUID_REVISION_rnp6 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp7    (SCB_CPUID_REVISION_rnp7 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp8    (SCB_CPUID_REVISION_rnp8 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp9    (SCB_CPUID_REVISION_rnp9 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp10    (SCB_CPUID_REVISION_rnp10 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp11    (SCB_CPUID_REVISION_rnp11 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp12    (SCB_CPUID_REVISION_rnp12 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp13    (SCB_CPUID_REVISION_rnp13 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp14    (SCB_CPUID_REVISION_rnp14 << SCB_CPUID_R_REVISION_BIT)
#define SCB_CPUID_R_REVISION_rnp15    (SCB_CPUID_REVISION_rnp15 << SCB_CPUID_R_REVISION_BIT)
/*----------*/

/*----------*/
#define SCB_CPUID_PARTNO_MASK    ((UBase_t) 0x00000FFFUL)
#define SCB_CPUID_PARTNO_M4    ((UBase_t) 0x00000C24UL)
#define SCB_CPUID_PARTNO_M7    ((UBase_t) 0x00000C27UL)

#define SCB_CPUID_R_PARTNO_BIT    (4UL)

#define SCB_CPUID_R_PARTNO_MASK    (SCB_CPUID_PARTNO_MASK << SCB_CPUID_R_PARTNO_BIT)
#define SCB_CPUID_R_PARTNO_M4    (SCB_CPUID_PARTNO_M4 << SCB_CPUID_R_PARTNO_BIT)
#define SCB_CPUID_R_PARTNO_M7    (SCB_CPUID_PARTNO_M7 << SCB_CPUID_R_PARTNO_BIT)
/*----------*/

/*----------*/
#define SCB_CPUID_CON_MASK    ((UBase_t) 0x0000000FUL)

#define SCB_CPUID_R_CON_BIT    (16UL)

#define SCB_CPUID_R_CON_MASK    (SCB_CPUID_CON_MASK << SCB_CPUID_R_CON_BIT)
/*----------*/

/*----------*/
#define SCB_CPUID_VARIANT_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_CPUID_VARIANT_r0pn    ((UBase_t) 0x00000000UL)
#define SCB_CPUID_VARIANT_r1pn    ((UBase_t) 0x00000001UL)
#define SCB_CPUID_VARIANT_r2pn    ((UBase_t) 0x00000002UL)
#define SCB_CPUID_VARIANT_r3pn    ((UBase_t) 0x00000003UL)
#define SCB_CPUID_VARIANT_r4pn    ((UBase_t) 0x00000004UL)
#define SCB_CPUID_VARIANT_r5pn    ((UBase_t) 0x00000005UL)
#define SCB_CPUID_VARIANT_r6pn    ((UBase_t) 0x00000006UL)
#define SCB_CPUID_VARIANT_r7pn    ((UBase_t) 0x00000007UL)
#define SCB_CPUID_VARIANT_r8pn    ((UBase_t) 0x00000008UL)
#define SCB_CPUID_VARIANT_r9pn    ((UBase_t) 0x00000009UL)
#define SCB_CPUID_VARIANT_r10pn    ((UBase_t) 0x0000000AUL)
#define SCB_CPUID_VARIANT_r11pn    ((UBase_t) 0x0000000BUL)
#define SCB_CPUID_VARIANT_r12pn    ((UBase_t) 0x0000000CUL)
#define SCB_CPUID_VARIANT_r13pn    ((UBase_t) 0x0000000DUL)
#define SCB_CPUID_VARIANT_r14pn    ((UBase_t) 0x0000000EUL)
#define SCB_CPUID_VARIANT_r15pn    ((UBase_t) 0x0000000FUL)

#define SCB_CPUID_R_VARIANT_BIT    (20UL)

#define SCB_CPUID_R_VARIANT_MASK    (SCB_CPUID_VARIANT_MASK << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r0pn    (SCB_CPUID_VARIANT_r0pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r1pn    (SCB_CPUID_VARIANT_r1pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r2pn    (SCB_CPUID_VARIANT_r2pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r3pn    (SCB_CPUID_VARIANT_r3pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r4pn    (SCB_CPUID_VARIANT_r4pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r5pn    (SCB_CPUID_VARIANT_r5pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r6pn    (SCB_CPUID_VARIANT_r6pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r7pn    (SCB_CPUID_VARIANT_r7pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r8pn    (SCB_CPUID_VARIANT_r8pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r9pn    (SCB_CPUID_VARIANT_r9pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r10pn    (SCB_CPUID_VARIANT_r10pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r11pn    (SCB_CPUID_VARIANT_r11pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r12pn    (SCB_CPUID_VARIANT_r12pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r13pn    (SCB_CPUID_VARIANT_r13pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r14pn    (SCB_CPUID_VARIANT_r14pn << SCB_CPUID_R_VARIANT_BIT)
#define SCB_CPUID_R_VARIANT_r15pn    (SCB_CPUID_VARIANT_r15pn << SCB_CPUID_R_VARIANT_BIT)
/*----------*/

/*----------*/
#define SCB_CPUID_IMPLEMENTER_MASK    ((UBase_t) 0x000000FFUL)
#define SCB_CPUID_IMPLEMENTER_ARM    ((UBase_t) 0x00000041UL)

#define SCB_CPUID_R_IMPLEMENTER_BIT    (24UL)

#define SCB_CPUID_R_IMPLEMENTER_MASK    (SCB_CPUID_IMPLEMENTER_MASK << SCB_CPUID_R_IMPLEMENTER_BIT)
#define SCB_CPUID_R_IMPLEMENTER_ARM    (SCB_CPUID_IMPLEMENTER_ARM << SCB_CPUID_R_IMPLEMENTER_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 5 VTOR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_VTOR_TBLOFF_MASK    ((UBase_t) 0x007FFFFFFUL)

#define SCB_VTOR_R_TBLOFF_BIT    (9UL)

#define SCB_VTOR_R_TBLOFF_MASK    (SCB_VTOR_TBLOFF_MASK << SCB_VTOR_R_TBLOFF_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 6 AIRCR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_AIRCR_VECTRESET_MASK    ((UBase_t) 0x00000001UL)
#define SCB_AIRCR_VECTRESET_NOUSE    ((UBase_t) 0x00000000UL)
#define SCB_AIRCR_VECTRESET_NOEFFECT    ((UBase_t) 0x00000001UL)

#define SCB_AIRCR_R_VECTRESET_BIT    (0UL)

#define SCB_AIRCR_R_VECTRESET_MASK    (SCB_AIRCR_VECTRESET_MASK << SCB_AIRCR_R_VECTRESET_BIT)
#define SCB_AIRCR_R_VECTRESET_NOUSE    (SCB_AIRCR_VECTRESET_NOUSE << SCB_AIRCR_R_VECTRESET_BIT)
#define SCB_AIRCR_R_VECTRESET_NOEFFECT    (SCB_AIRCR_VECTRESET_NOEFFECT << SCB_AIRCR_R_VECTRESET_BIT)
/*----------*/

/*----------*/
#define SCB_AIRCR_VECTCLRACTIVE_MASK    ((UBase_t) 0x00000001UL)
#define SCB_AIRCR_VECTCLRACTIVE_NOUSE    ((UBase_t) 0x00000000UL)
#define SCB_AIRCR_VECTCLRACTIVE_NOEFFECT    ((UBase_t) 0x00000001UL)

#define SCB_AIRCR_R_VECTCLRACTIVE_BIT    (1UL)

#define SCB_AIRCR_R_VECTCLRACTIVE_MASK    (SCB_AIRCR_VECTCLRACTIVE_MASK << SCB_AIRCR_R_VECTCLRACTIVE_BIT)
#define SCB_AIRCR_R_VECTCLRACTIVE_NOUSE    (SCB_AIRCR_VECTCLRACTIVE_NOUSE << SCB_AIRCR_R_VECTCLRACTIVE_BIT)
#define SCB_AIRCR_R_VECTCLRACTIVE_NOEFFECT    (SCB_AIRCR_VECTCLRACTIVE_NOEFFECT << SCB_AIRCR_R_VECTCLRACTIVE_BIT)
/*----------*/

/*----------*/
#define SCB_AIRCR_SYSRESETREQ_MASK    ((UBase_t) 0x00000001UL)
#define SCB_AIRCR_SYSRESETREQ_NOEFFECT    ((UBase_t) 0x00000000UL)
#define SCB_AIRCR_SYSRESETREQ_RESET    ((UBase_t) 0x00000001UL)

#define SCB_AIRCR_R_SYSRESETREQ_BIT    (2UL)

#define SCB_AIRCR_R_SYSRESETREQ_MASK    (SCB_AIRCR_SYSRESETREQ_MASK << SCB_AIRCR_R_SYSRESETREQ_BIT)
#define SCB_AIRCR_R_SYSRESETREQ_NOEFFECT    (SCB_AIRCR_SYSRESETREQ_NOEFFECT << SCB_AIRCR_R_SYSRESETREQ_BIT)
#define SCB_AIRCR_R_SYSRESETREQ_RESET    (SCB_AIRCR_SYSRESETREQ_RESET << SCB_AIRCR_R_SYSRESETREQ_BIT)
/*----------*/

/*----------*/
#define SCB_PRIGROUP_XXXX    (3UL)
#define SCB_PRIGROUP_XXXY    (4UL)
#define SCB_PRIGROUP_XXYY    (5UL)
#define SCB_PRIGROUP_XYYY    (6UL)
#define SCB_PRIGROUP_YYYY    (7UL)

#define SCB_AIRCR_PRIGROUP_MASK    ((UBase_t) 0x00000007UL)
#define SCB_AIRCR_PRIGROUP_XXXX    ((UBase_t) 0x00000003UL)
#define SCB_AIRCR_PRIGROUP_XXXY    ((UBase_t) 0x00000004UL)
#define SCB_AIRCR_PRIGROUP_XXYY    ((UBase_t) 0x00000005UL)
#define SCB_AIRCR_PRIGROUP_XYYY    ((UBase_t) 0x00000006UL)
#define SCB_AIRCR_PRIGROUP_YYYY    ((UBase_t) 0x00000007UL)

#define SCB_AIRCR_R_PRIGROUP_BIT    (8UL)

#define SCB_AIRCR_R_PRIGROUP_MASK    (SCB_AIRCR_PRIGROUP_MASK << SCB_AIRCR_R_PRIGROUP_BIT)
#define SCB_AIRCR_R_PRIGROUP_XXXX    (SCB_AIRCR_PRIGROUP_XXXX << SCB_AIRCR_R_PRIGROUP_BIT)
#define SCB_AIRCR_R_PRIGROUP_XXXY    (SCB_AIRCR_PRIGROUP_XXXY << SCB_AIRCR_R_PRIGROUP_BIT)
#define SCB_AIRCR_R_PRIGROUP_XXYY    (SCB_AIRCR_PRIGROUP_XXYY << SCB_AIRCR_R_PRIGROUP_BIT)
#define SCB_AIRCR_R_PRIGROUP_XYYY    (SCB_AIRCR_PRIGROUP_XYYY << SCB_AIRCR_R_PRIGROUP_BIT)
#define SCB_AIRCR_R_PRIGROUP_YYYY    (SCB_AIRCR_PRIGROUP_YYYY << SCB_AIRCR_R_PRIGROUP_BIT)
/*----------*/

/*----------*/

#define SCB_AIRCR_ENDIANESS_MASK    ((UBase_t) 0x00000001UL)
#define SCB_AIRCR_ENDIANESS_LITTLE    ((UBase_t) 0x00000000UL)
#define SCB_AIRCR_ENDIANESS_BIG    ((UBase_t) 0x00000001UL)

#define SCB_AIRCR_R_ENDIANESS_BIT    (15UL)

#define SCB_AIRCR_R_ENDIANESS_MASK    (SCB_AIRCR_ENDIANESS_MASK << SCB_AIRCR_R_ENDIANESS_BIT)
#define SCB_AIRCR_R_ENDIANESS_LITTLE    (SCB_AIRCR_ENDIANESS_LITTLE << SCB_AIRCR_R_ENDIANESS_BIT)
#define SCB_AIRCR_R_ENDIANESS_BIG    (SCB_AIRCR_ENDIANESS_BIG << SCB_AIRCR_R_ENDIANESS_BIT)
/*----------*/

/*----------*/

#define SCB_AIRCR_VECTKEY_MASK    ((UBase_t) 0x0000FFFFUL)
#define SCB_AIRCR_VECTKEY_READ    ((UBase_t) 0x0000FA05UL)
#define SCB_AIRCR_VECTKEY_WRITE    ((UBase_t) 0x000005FAUL)

#define SCB_AIRCR_R_VECTKEY_BIT    (16UL)

#define SCB_AIRCR_R_VECTKEY_MASK    (SCB_AIRCR_VECTKEY_MASK << SCB_AIRCR_R_VECTKEY_BIT)
#define SCB_AIRCR_R_VECTKEY_READ    (SCB_AIRCR_VECTKEY_READ << SCB_AIRCR_R_VECTKEY_BIT)
#define SCB_AIRCR_R_VECTKEY_WRITE    (SCB_AIRCR_VECTKEY_WRITE << SCB_AIRCR_R_VECTKEY_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 7 SCR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_SCR_SLEEPONEXIT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SCR_SLEEPONEXIT_RUN    ((UBase_t) 0x00000000UL)
#define SCB_SCR_SLEEPONEXIT_SLEEP    ((UBase_t) 0x00000001UL)

#define SCB_SCR_R_SLEEPONEXIT_BIT    (1UL)

#define SCB_SCR_R_SLEEPONEXIT_MASK    (SCB_SCR_SLEEPONEXIT_MASK << SCB_SCR_R_SLEEPONEXIT_BIT)
#define SCB_SCR_R_SLEEPONEXIT_RUN    (SCB_SCR_SLEEPONEXIT_RUN << SCB_SCR_R_SLEEPONEXIT_BIT)
#define SCB_SCR_R_SLEEPONEXIT_SLEEP    (SCB_SCR_SLEEPONEXIT_SLEEP << SCB_SCR_R_SLEEPONEXIT_BIT)
/*----------*/

/*----------*/
#define SCB_SLEEPDEEP_SLEEP    (0UL)
#define SCB_SLEEPDEEP_DEEPSLEEP    (1UL)

#define SCB_SCR_SLEEPDEEP_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SCR_SLEEPDEEP_SLEEP    ((UBase_t) 0x00000000UL)
#define SCB_SCR_SLEEPDEEP_DEEPSLEEP    ((UBase_t) 0x00000001UL)

#define SCB_SCR_R_SLEEPDEEP_BIT    (2UL)

#define SCB_SCR_R_SLEEPDEEP_MASK    (SCB_SCR_SLEEPDEEP_MASK << SCB_SCR_R_SLEEPDEEP_BIT)
#define SCB_SCR_R_SLEEPDEEP_SLEEP    (SCB_SCR_SLEEPDEEP_SLEEP << SCB_SCR_R_SLEEPDEEP_BIT)
#define SCB_SCR_R_SLEEPDEEP_DEEPSLEEP    (SCB_SCR_SLEEPDEEP_DEEPSLEEP << SCB_SCR_R_SLEEPDEEP_BIT)
/*----------*/

/*----------*/
#define SCB_SCR_SEVONPEND_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SCR_SEVONPEND_ONLY    ((UBase_t) 0x00000000UL)
#define SCB_SCR_SEVONPEND_ALL    ((UBase_t) 0x00000001UL)

#define SCB_SCR_R_SEVONPEND_BIT    (4UL)

#define SCB_SCR_R_SEVONPEND_MASK    (SCB_SCR_SEVONPEND_MASK << SCB_SCR_R_SEVONPEND_BIT)
#define SCB_SCR_R_SEVONPEND_ONLY    (SCB_SCR_SEVONPEND_ONLY << SCB_SCR_R_SEVONPEND_BIT)
#define SCB_SCR_R_SEVONPEND_ALL    (SCB_SCR_SEVONPEND_ALL << SCB_SCR_R_SEVONPEND_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 8 CCR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_CCR_NONBASETHREDENA_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_NONBASETHREDENA_ONLY    ((UBase_t) 0x00000000UL)
#define SCB_CCR_NONBASETHREDENA_ALL    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_NONBASETHREDENA_BIT    (0UL)

#define SCB_CCR_R_NONBASETHREDENA_MASK    (SCB_CCR_NONBASETHREDENA_MASK << SCB_CCR_R_NONBASETHREDENA_BIT)
#define SCB_CCR_R_NONBASETHREDENA_ONLY    (SCB_CCR_NONBASETHREDENA_ONLY << SCB_CCR_R_NONBASETHREDENA_BIT)
#define SCB_CCR_R_NONBASETHREDENA_ALL    (SCB_CCR_NONBASETHREDENA_ALL << SCB_CCR_R_NONBASETHREDENA_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_USERSETMPEND_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_USERSETMPEND_DIS    ((UBase_t) 0x00000000UL)
#define SCB_CCR_USERSETMPEND_ENA    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_USERSETMPEND_BIT    (1UL)

#define SCB_CCR_R_USERSETMPEND_MASK    (SCB_CCR_USERSETMPEND_MASK << SCB_CCR_R_USERSETMPEND_BIT)
#define SCB_CCR_R_USERSETMPEND_DIS    (SCB_CCR_USERSETMPEND_DIS << SCB_CCR_R_USERSETMPEND_BIT)
#define SCB_CCR_R_USERSETMPEND_ENA    (SCB_CCR_USERSETMPEND_ENA << SCB_CCR_R_USERSETMPEND_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_UNALIGN_TRP_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_UNALIGN_TRP_NOOCCUR    ((UBase_t) 0x00000000UL)
#define SCB_CCR_UNALIGN_TRP_OCCUR    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_UNALIGN_TRP_BIT    (3UL)

#define SCB_CCR_R_UNALIGN_TRP_MASK    (SCB_CCR_UNALIGN_TRP_MASK << SCB_CCR_R_UNALIGN_TRP_BIT)
#define SCB_CCR_R_UNALIGN_TRP_NOOCCUR    (SCB_CCR_UNALIGN_TRP_NOOCCUR << SCB_CCR_R_UNALIGN_TRP_BIT)
#define SCB_CCR_R_UNALIGN_TRP_OCCUR    (SCB_CCR_UNALIGN_TRP_OCCUR << SCB_CCR_R_UNALIGN_TRP_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_DIV_0_TRP_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_DIV_0_TRP_NOOCCUR    ((UBase_t) 0x00000000UL)
#define SCB_CCR_DIV_0_TRP_OCCUR    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_DIV_0_TRP_BIT    (4UL)

#define SCB_CCR_R_DIV_0_TRP_MASK    (SCB_CCR_DIV_0_TRP_MASK << SCB_CCR_R_DIV_0_TRP_BIT)
#define SCB_CCR_R_DIV_0_TRP_NOOCCUR    (SCB_CCR_DIV_0_TRP_NOOCCUR << SCB_CCR_R_DIV_0_TRP_BIT)
#define SCB_CCR_R_DIV_0_TRP_OCCUR    (SCB_CCR_DIV_0_TRP_OCCUR << SCB_CCR_R_DIV_0_TRP_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_BFHFNMIGN_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_BFHFNMIGN_NORMAL    ((UBase_t) 0x00000000UL)
#define SCB_CCR_BFHFNMIGN_IGNORE    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_BFHFNMIGN_BIT    (8UL)

#define SCB_CCR_R_BFHFNMIGN_MASK    (SCB_CCR_BFHFNMIGN_MASK << SCB_CCR_R_BFHFNMIGN_BIT)
#define SCB_CCR_R_BFHFNMIGN_NORMAL    (SCB_CCR_BFHFNMIGN_NORMAL << SCB_CCR_R_BFHFNMIGN_BIT)
#define SCB_CCR_R_BFHFNMIGN_IGNORE    (SCB_CCR_BFHFNMIGN_IGNORE << SCB_CCR_R_BFHFNMIGN_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_STKALIGN_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_STKALIGN_4BYTE    ((UBase_t) 0x00000000UL)
#define SCB_CCR_STKALIGN_8BYTE    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_STKALIGN_BIT    (9UL)

#define SCB_CCR_R_STKALIGN_MASK    (SCB_CCR_STKALIGN_MASK << SCB_CCR_R_STKALIGN_BIT)
#define SCB_CCR_R_STKALIGN_4BYTE    (SCB_CCR_STKALIGN_4BYTE << SCB_CCR_R_STKALIGN_BIT)
#define SCB_CCR_R_STKALIGN_8BYTE    (SCB_CCR_STKALIGN_8BYTE << SCB_CCR_R_STKALIGN_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_DC_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_DC_DIS    ((UBase_t) 0x00000000UL)
#define SCB_CCR_DC_ENA    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_DC_BIT    (16UL)

#define SCB_CCR_R_DC_MASK    (SCB_CCR_DC_MASK << SCB_CCR_R_DC_BIT)
#define SCB_CCR_R_DC_DIS    (SCB_CCR_DC_DIS << SCB_CCR_R_DC_BIT)
#define SCB_CCR_R_DC_ENA    (SCB_CCR_DC_ENA << SCB_CCR_R_DC_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_IC_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_IC_DIS    ((UBase_t) 0x00000000UL)
#define SCB_CCR_IC_ENA    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_IC_BIT    (17UL)

#define SCB_CCR_R_IC_MASK    (SCB_CCR_IC_MASK << SCB_CCR_R_IC_BIT)
#define SCB_CCR_R_IC_DIS    (SCB_CCR_IC_DIS << SCB_CCR_R_IC_BIT)
#define SCB_CCR_R_IC_ENA    (SCB_CCR_IC_ENA << SCB_CCR_R_IC_BIT)
/*----------*/

/*----------*/
#define SCB_CCR_BP_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CCR_BP_DIS    ((UBase_t) 0x00000000UL)
#define SCB_CCR_BP_ENA    ((UBase_t) 0x00000001UL)

#define SCB_CCR_R_BP_BIT    (19UL)

#define SCB_CCR_R_BP_MASK    (SCB_CCR_BP_MASK << SCB_CCR_R_BP_BIT)
#define SCB_CCR_R_BP_DIS    (SCB_CCR_BP_DIS << SCB_CCR_R_BP_BIT)
#define SCB_CCR_R_BP_ENA    (SCB_CCR_BP_ENA << SCB_CCR_R_BP_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 9 SHPR1 ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_SHPR1_MEM_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR1_MEM_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR1_MEM_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR1_MEM_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR1_MEM_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR1_MEM_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR1_MEM_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR1_MEM_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR1_MEM_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR1_MEM_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR1_MEM_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR1_MEM_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR1_MEM_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR1_MEM_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR1_MEM_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR1_MEM_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR1_MEM_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR1_R_MEM_BIT    (0UL + 4UL)

#define SCB_SHPR1_R_MEM_MASK    (SCB_SHPR1_MEM_MASK << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI0    (SCB_SHPR1_MEM_PRI0 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI1    (SCB_SHPR1_MEM_PRI1 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI2    (SCB_SHPR1_MEM_PRI2 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI3    (SCB_SHPR1_MEM_PRI3 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI4    (SCB_SHPR1_MEM_PRI4 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI5    (SCB_SHPR1_MEM_PRI5 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI6    (SCB_SHPR1_MEM_PRI6 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI7    (SCB_SHPR1_MEM_PRI7 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI8    (SCB_SHPR1_MEM_PRI8 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI9    (SCB_SHPR1_MEM_PRI9 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI10    (SCB_SHPR1_MEM_PRI10 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI11    (SCB_SHPR1_MEM_PRI11 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI12    (SCB_SHPR1_MEM_PRI12 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI13    (SCB_SHPR1_MEM_PRI13 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI14    (SCB_SHPR1_MEM_PRI14 << SCB_SHPR1_R_MEM_BIT)
#define SCB_SHPR1_R_MEM_PRI15    (SCB_SHPR1_MEM_PRI15 << SCB_SHPR1_R_MEM_BIT)
/*----------*/

/*----------*/
#define SCB_SHPR1_BUS_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR1_BUS_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR1_BUS_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR1_BUS_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR1_BUS_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR1_BUS_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR1_BUS_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR1_BUS_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR1_BUS_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR1_BUS_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR1_BUS_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR1_BUS_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR1_BUS_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR1_BUS_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR1_BUS_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR1_BUS_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR1_BUS_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR1_R_BUS_BIT    (8UL + 4UL)

#define SCB_SHPR1_R_BUS_MASK    (SCB_SHPR1_BUS_MASK << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI0    (SCB_SHPR1_BUS_PRI0 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI1    (SCB_SHPR1_BUS_PRI1 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI2    (SCB_SHPR1_BUS_PRI2 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI3    (SCB_SHPR1_BUS_PRI3 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI4    (SCB_SHPR1_BUS_PRI4 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI5    (SCB_SHPR1_BUS_PRI5 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI6    (SCB_SHPR1_BUS_PRI6 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI7    (SCB_SHPR1_BUS_PRI7 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI8    (SCB_SHPR1_BUS_PRI8 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI9    (SCB_SHPR1_BUS_PRI9 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI10    (SCB_SHPR1_BUS_PRI10 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI11    (SCB_SHPR1_BUS_PRI11 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI12    (SCB_SHPR1_BUS_PRI12 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI13    (SCB_SHPR1_BUS_PRI13 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI14    (SCB_SHPR1_BUS_PRI14 << SCB_SHPR1_R_BUS_BIT)
#define SCB_SHPR1_R_BUS_PRI15    (SCB_SHPR1_BUS_PRI15 << SCB_SHPR1_R_BUS_BIT)
/*----------*/

/*----------*/
#define SCB_SHPR1_USAGE_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR1_USAGE_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR1_USAGE_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR1_USAGE_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR1_USAGE_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR1_USAGE_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR1_USAGE_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR1_USAGE_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR1_USAGE_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR1_USAGE_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR1_USAGE_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR1_USAGE_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR1_USAGE_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR1_USAGE_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR1_USAGE_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR1_USAGE_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR1_USAGE_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR1_R_USAGE_BIT    (16UL + 4UL)

#define SCB_SHPR1_R_USAGE_MASK    (SCB_SHPR1_USAGE_MASK << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI0    (SCB_SHPR1_USAGE_PRI0 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI1    (SCB_SHPR1_USAGE_PRI1 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI2    (SCB_SHPR1_USAGE_PRI2 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI3    (SCB_SHPR1_USAGE_PRI3 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI4    (SCB_SHPR1_USAGE_PRI4 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI5    (SCB_SHPR1_USAGE_PRI5 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI6    (SCB_SHPR1_USAGE_PRI6 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI7    (SCB_SHPR1_USAGE_PRI7 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI8    (SCB_SHPR1_USAGE_PRI8 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI9    (SCB_SHPR1_USAGE_PRI9 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI10    (SCB_SHPR1_USAGE_PRI10 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI11    (SCB_SHPR1_USAGE_PRI11 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI12    (SCB_SHPR1_USAGE_PRI12 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI13    (SCB_SHPR1_USAGE_PRI13 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI14    (SCB_SHPR1_USAGE_PRI14 << SCB_SHPR1_R_USAGE_BIT)
#define SCB_SHPR1_R_USAGE_PRI15    (SCB_SHPR1_USAGE_PRI15 << SCB_SHPR1_R_USAGE_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 10 SHPR2 ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_SHPR2_SVCALL_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR2_SVCALL_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR2_SVCALL_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR2_SVCALL_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR2_SVCALL_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR2_SVCALL_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR2_SVCALL_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR2_SVCALL_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR2_SVCALL_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR2_SVCALL_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR2_SVCALL_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR2_SVCALL_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR2_SVCALL_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR2_SVCALL_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR2_SVCALL_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR2_SVCALL_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR2_SVCALL_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR2_R_SVCALL_BIT    (24UL + 4UL)

#define SCB_SHPR2_R_SVCALL_MASK    (SCB_SHPR2_SVCALL_MASK << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI0    (SCB_SHPR2_SVCALL_PRI0 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI1    (SCB_SHPR2_SVCALL_PRI1 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI2    (SCB_SHPR2_SVCALL_PRI2 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI3    (SCB_SHPR2_SVCALL_PRI3 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI4    (SCB_SHPR2_SVCALL_PRI4 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI5    (SCB_SHPR2_SVCALL_PRI5 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI6    (SCB_SHPR2_SVCALL_PRI6 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI7    (SCB_SHPR2_SVCALL_PRI7 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI8    (SCB_SHPR2_SVCALL_PRI8 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI9    (SCB_SHPR2_SVCALL_PRI9 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI10    (SCB_SHPR2_SVCALL_PRI10 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI11    (SCB_SHPR2_SVCALL_PRI11 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI12    (SCB_SHPR2_SVCALL_PRI12 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI13    (SCB_SHPR2_SVCALL_PRI13 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI14    (SCB_SHPR2_SVCALL_PRI14 << SCB_SHPR2_R_SVCALL_BIT)
#define SCB_SHPR2_R_SVCALL_PRI15    (SCB_SHPR2_SVCALL_PRI15 << SCB_SHPR2_R_SVCALL_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 11 SHPR3 ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_SHPR3_DEBUG_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR3_DEBUG_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR3_DEBUG_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR3_DEBUG_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR3_DEBUG_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR3_DEBUG_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR3_DEBUG_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR3_DEBUG_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR3_DEBUG_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR3_DEBUG_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR3_DEBUG_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR3_DEBUG_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR3_DEBUG_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR3_DEBUG_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR3_DEBUG_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR3_DEBUG_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR3_DEBUG_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR3_R_DEBUG_BIT    (0UL + 4UL)

#define SCB_SHPR3_R_DEBUG_MASK    (SCB_SHPR3_DEBUG_MASK << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI0    (SCB_SHPR3_DEBUG_PRI0 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI1    (SCB_SHPR3_DEBUG_PRI1 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI2    (SCB_SHPR3_DEBUG_PRI2 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI3    (SCB_SHPR3_DEBUG_PRI3 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI4    (SCB_SHPR3_DEBUG_PRI4 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI5    (SCB_SHPR3_DEBUG_PRI5 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI6    (SCB_SHPR3_DEBUG_PRI6 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI7    (SCB_SHPR3_DEBUG_PRI7 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI8    (SCB_SHPR3_DEBUG_PRI8 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI9    (SCB_SHPR3_DEBUG_PRI9 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI10    (SCB_SHPR3_DEBUG_PRI10 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI11    (SCB_SHPR3_DEBUG_PRI11 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI12    (SCB_SHPR3_DEBUG_PRI12 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI13    (SCB_SHPR3_DEBUG_PRI13 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI14    (SCB_SHPR3_DEBUG_PRI14 << SCB_SHPR3_R_DEBUG_BIT)
#define SCB_SHPR3_R_DEBUG_PRI15    (SCB_SHPR3_DEBUG_PRI15 << SCB_SHPR3_R_DEBUG_BIT)
/*----------*/

/*----------*/
#define SCB_SHPR3_PENDSV_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR3_PENDSV_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR3_PENDSV_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR3_PENDSV_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR3_PENDSV_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR3_PENDSV_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR3_PENDSV_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR3_PENDSV_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR3_PENDSV_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR3_PENDSV_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR3_PENDSV_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR3_PENDSV_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR3_PENDSV_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR3_PENDSV_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR3_PENDSV_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR3_PENDSV_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR3_PENDSV_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR3_R_PENDSV_BIT    (16UL + 4UL)

#define SCB_SHPR3_R_PENDSV_MASK    (SCB_SHPR3_PENDSV_MASK << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI0    (SCB_SHPR3_PENDSV_PRI0 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI1    (SCB_SHPR3_PENDSV_PRI1 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI2    (SCB_SHPR3_PENDSV_PRI2 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI3    (SCB_SHPR3_PENDSV_PRI3 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI4    (SCB_SHPR3_PENDSV_PRI4 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI5    (SCB_SHPR3_PENDSV_PRI5 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI6    (SCB_SHPR3_PENDSV_PRI6 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI7    (SCB_SHPR3_PENDSV_PRI7 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI8    (SCB_SHPR3_PENDSV_PRI8 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI9    (SCB_SHPR3_PENDSV_PRI9 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI10    (SCB_SHPR3_PENDSV_PRI10 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI11    (SCB_SHPR3_PENDSV_PRI11 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI12    (SCB_SHPR3_PENDSV_PRI12 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI13    (SCB_SHPR3_PENDSV_PRI13 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI14    (SCB_SHPR3_PENDSV_PRI14 << SCB_SHPR3_R_PENDSV_BIT)
#define SCB_SHPR3_R_PENDSV_PRI15    (SCB_SHPR3_PENDSV_PRI15 << SCB_SHPR3_R_PENDSV_BIT)
/*----------*/

/*----------*/
#define SCB_SHPR3_SYSTICK_MASK    ((UBase_t) 0x0000000FUL)
#define SCB_SHPR3_SYSTICK_PRI0    ((UBase_t) 0x00000000UL)
#define SCB_SHPR3_SYSTICK_PRI1    ((UBase_t) 0x00000001UL)
#define SCB_SHPR3_SYSTICK_PRI2    ((UBase_t) 0x00000002UL)
#define SCB_SHPR3_SYSTICK_PRI3    ((UBase_t) 0x00000003UL)
#define SCB_SHPR3_SYSTICK_PRI4    ((UBase_t) 0x00000004UL)
#define SCB_SHPR3_SYSTICK_PRI5    ((UBase_t) 0x00000005UL)
#define SCB_SHPR3_SYSTICK_PRI6    ((UBase_t) 0x00000006UL)
#define SCB_SHPR3_SYSTICK_PRI7    ((UBase_t) 0x00000007UL)
#define SCB_SHPR3_SYSTICK_PRI8    ((UBase_t) 0x00000008UL)
#define SCB_SHPR3_SYSTICK_PRI9    ((UBase_t) 0x00000009UL)
#define SCB_SHPR3_SYSTICK_PRI10    ((UBase_t) 0x000000AUL)
#define SCB_SHPR3_SYSTICK_PRI11    ((UBase_t) 0x0000000BUL)
#define SCB_SHPR3_SYSTICK_PRI12    ((UBase_t) 0x0000000CUL)
#define SCB_SHPR3_SYSTICK_PRI13    ((UBase_t) 0x0000000DUL)
#define SCB_SHPR3_SYSTICK_PRI14    ((UBase_t) 0x0000000EUL)
#define SCB_SHPR3_SYSTICK_PRI15    ((UBase_t) 0x0000000FUL)

#define SCB_SHPR3_R_SYSTICK_BIT    (24UL + 4UL)

#define SCB_SHPR3_R_SYSTICK_MASK    (SCB_SHPR3_SYSTICK_MASK << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI0    (SCB_SHPR3_SYSTICK_PRI0 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI1    (SCB_SHPR3_SYSTICK_PRI1 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI2    (SCB_SHPR3_SYSTICK_PRI2 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI3    (SCB_SHPR3_SYSTICK_PRI3 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI4    (SCB_SHPR3_SYSTICK_PRI4 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI5    (SCB_SHPR3_SYSTICK_PRI5 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI6    (SCB_SHPR3_SYSTICK_PRI6 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI7    (SCB_SHPR3_SYSTICK_PRI7 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI8    (SCB_SHPR3_SYSTICK_PRI8 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI9    (SCB_SHPR3_SYSTICK_PRI9 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI10    (SCB_SHPR3_SYSTICK_PRI10 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI11    (SCB_SHPR3_SYSTICK_PRI11 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI12    (SCB_SHPR3_SYSTICK_PRI12 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI13    (SCB_SHPR3_SYSTICK_PRI13 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI14    (SCB_SHPR3_SYSTICK_PRI14 << SCB_SHPR3_R_SYSTICK_BIT)
#define SCB_SHPR3_R_SYSTICK_PRI15    (SCB_SHPR3_SYSTICK_PRI15 << SCB_SHPR3_R_SYSTICK_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 12 SHCSR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_SHCSR_MEMFAULTACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_MEMFAULTACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_MEMFAULTACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_MEMFAULTACT_BIT    (0UL)

#define SCB_SHCSR_R_MEMFAULTACT_MASK    (SCB_SHCSR_MEMFAULTACT_MASK << SCB_SHCSR_R_MEMFAULTACT_BIT)
#define SCB_SHCSR_R_MEMFAULTACT_INACTIVE    (SCB_SHCSR_MEMFAULTACT_INACTIVE << SCB_SHCSR_R_MEMFAULTACT_BIT)
#define SCB_SHCSR_R_MEMFAULTACT_ACTIVE    (SCB_SHCSR_MEMFAULTACT_ACTIVE << SCB_SHCSR_R_MEMFAULTACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_BUSFAULTACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_BUSFAULTACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_BUSFAULTACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_BUSFAULTACT_BIT    (1UL)

#define SCB_SHCSR_R_BUSFAULTACT_MASK    (SCB_SHCSR_BUSFAULTACT_MASK << SCB_SHCSR_R_BUSFAULTACT_BIT)
#define SCB_SHCSR_R_BUSFAULTACT_INACTIVE    (SCB_SHCSR_BUSFAULTACT_INACTIVE << SCB_SHCSR_R_BUSFAULTACT_BIT)
#define SCB_SHCSR_R_BUSFAULTACT_ACTIVE    (SCB_SHCSR_BUSFAULTACT_ACTIVE << SCB_SHCSR_R_BUSFAULTACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_USGFAULTACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_USGFAULTACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_USGFAULTACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_USGFAULTACT_BIT    (3UL)

#define SCB_SHCSR_R_USGFAULTACT_MASK    (SCB_SHCSR_USGFAULTACT_MASK << SCB_SHCSR_R_USGFAULTACT_BIT)
#define SCB_SHCSR_R_USGFAULTACT_INACTIVE    (SCB_SHCSR_USGFAULTACT_INACTIVE << SCB_SHCSR_R_USGFAULTACT_BIT)
#define SCB_SHCSR_R_USGFAULTACT_ACTIVE    (SCB_SHCSR_USGFAULTACT_ACTIVE << SCB_SHCSR_R_USGFAULTACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_SVCALLACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_SVCALLACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_SVCALLACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_SVCALLACT_BIT    (7UL)

#define SCB_SHCSR_R_SVCALLACT_MASK    (SCB_SHCSR_SVCALLACT_MASK << SCB_SHCSR_R_SVCALLACT_BIT)
#define SCB_SHCSR_R_SVCALLACT_INACTIVE    (SCB_SHCSR_SVCALLACT_INACTIVE << SCB_SHCSR_R_SVCALLACT_BIT)
#define SCB_SHCSR_R_SVCALLACT_ACTIVE    (SCB_SHCSR_SVCALLACT_ACTIVE << SCB_SHCSR_R_SVCALLACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_MONITORACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_MONITORACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_MONITORACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_MONITORACT_BIT    (8UL)

#define SCB_SHCSR_R_MONITORACT_MASK    (SCB_SHCSR_MONITORACT_MASK << SCB_SHCSR_R_MONITORACT_BIT)
#define SCB_SHCSR_R_MONITORACT_INACTIVE    (SCB_SHCSR_MONITORACT_INACTIVE << SCB_SHCSR_R_MONITORACT_BIT)
#define SCB_SHCSR_R_MONITORACT_ACTIVE    (SCB_SHCSR_MONITORACT_ACTIVE << SCB_SHCSR_R_MONITORACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_PENDSVACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_PENDSVACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_PENDSVACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_PENDSVACT_BIT    (10UL)

#define SCB_SHCSR_R_PENDSVACT_MASK    (SCB_SHCSR_PENDSVACT_MASK << SCB_SHCSR_R_PENDSVACT_BIT)
#define SCB_SHCSR_R_PENDSVACT_INACTIVE    (SCB_SHCSR_PENDSVACT_INACTIVE << SCB_SHCSR_R_PENDSVACT_BIT)
#define SCB_SHCSR_R_PENDSVACT_ACTIVE    (SCB_SHCSR_PENDSVACT_ACTIVE << SCB_SHCSR_R_PENDSVACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_SYSTICKACT_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_SYSTICKACT_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_SYSTICKACT_ACTIVE    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_SYSTICKACT_BIT    (11UL)

#define SCB_SHCSR_R_SYSTICKACT_MASK    (SCB_SHCSR_SYSTICKACT_MASK << SCB_SHCSR_R_SYSTICKACT_BIT)
#define SCB_SHCSR_R_SYSTICKACT_INACTIVE    (SCB_SHCSR_SYSTICKACT_INACTIVE << SCB_SHCSR_R_SYSTICKACT_BIT)
#define SCB_SHCSR_R_SYSTICKACT_ACTIVE    (SCB_SHCSR_SYSTICKACT_ACTIVE << SCB_SHCSR_R_SYSTICKACT_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_USGFAULTPENDED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_USGFAULTPENDED_UNPENDED    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_USGFAULTPENDED_PENDED    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_USGFAULTPENDED_BIT    (12UL)

#define SCB_SHCSR_R_USGFAULTPENDED_MASK    (SCB_SHCSR_USGFAULTPENDED_MASK << SCB_SHCSR_R_USGFAULTPENDED_BIT)
#define SCB_SHCSR_R_USGFAULTPENDED_UNPENDED    (SCB_SHCSR_USGFAULTPENDED_UNPENDED << SCB_SHCSR_R_USGFAULTPENDED_BIT)
#define SCB_SHCSR_R_USGFAULTPENDED_PENDED    (SCB_SHCSR_USGFAULTPENDED_PENDED << SCB_SHCSR_R_USGFAULTPENDED_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_MEMFAULTPENDED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_MEMFAULTPENDED_UNPENDED    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_MEMFAULTPENDED_PENDED    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_MEMFAULTPENDED_BIT    (13UL)

#define SCB_SHCSR_R_MEMFAULTPENDED_MASK    (SCB_SHCSR_MEMFAULTPENDED_MASK << SCB_SHCSR_R_MEMFAULTPENDED_BIT)
#define SCB_SHCSR_R_MEMFAULTPENDED_UNPENDED    (SCB_SHCSR_MEMFAULTPENDED_UNPENDED << SCB_SHCSR_R_MEMFAULTPENDED_BIT)
#define SCB_SHCSR_R_MEMFAULTPENDED_PENDED    (SCB_SHCSR_MEMFAULTPENDED_PENDED << SCB_SHCSR_R_MEMFAULTPENDED_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_BUSFAULTPENDED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_BUSFAULTPENDED_UNPENDED    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_BUSFAULTPENDED_PENDED    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_BUSFAULTPENDED_BIT    (14UL)

#define SCB_SHCSR_R_BUSFAULTPENDED_MASK    (SCB_SHCSR_BUSFAULTPENDED_MASK << SCB_SHCSR_R_BUSFAULTPENDED_BIT)
#define SCB_SHCSR_R_BUSFAULTPENDED_UNPENDED    (SCB_SHCSR_BUSFAULTPENDED_UNPENDED << SCB_SHCSR_R_BUSFAULTPENDED_BIT)
#define SCB_SHCSR_R_BUSFAULTPENDED_PENDED    (SCB_SHCSR_BUSFAULTPENDED_PENDED << SCB_SHCSR_R_BUSFAULTPENDED_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_SVCALLPENDED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_SVCALLPENDED_UNPENDED    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_SVCALLPENDED_PENDED    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_SVCALLPENDED_BIT    (15UL)

#define SCB_SHCSR_R_SVCALLPENDED_MASK    (SCB_SHCSR_SVCALLPENDED_MASK << SCB_SHCSR_R_SVCALLPENDED_BIT)
#define SCB_SHCSR_R_SVCALLPENDED_UNPENDED    (SCB_SHCSR_SVCALLPENDED_UNPENDED << SCB_SHCSR_R_SVCALLPENDED_BIT)
#define SCB_SHCSR_R_SVCALLPENDED_PENDED    (SCB_SHCSR_SVCALLPENDED_PENDED << SCB_SHCSR_R_SVCALLPENDED_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_MEMFAULTENA_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_MEMFAULTENA_DIS    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_MEMFAULTENA_ENA    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_MEMFAULTENA_BIT    (16UL)

#define SCB_SHCSR_R_MEMFAULTENA_MASK    (SCB_SHCSR_MEMFAULTENA_MASK << SCB_SHCSR_R_MEMFAULTENA_BIT)
#define SCB_SHCSR_R_MEMFAULTENA_DIS    (SCB_SHCSR_MEMFAULTENA_DIS << SCB_SHCSR_R_MEMFAULTENA_BIT)
#define SCB_SHCSR_R_MEMFAULTENA_ENA    (SCB_SHCSR_MEMFAULTENA_ENA << SCB_SHCSR_R_MEMFAULTENA_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_BUSFAULTENA_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_BUSFAULTENA_DIS    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_BUSFAULTENA_ENA    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_BUSFAULTENA_BIT    (17UL)

#define SCB_SHCSR_R_BUSFAULTENA_MASK    (SCB_SHCSR_BUSFAULTENA_MASK << SCB_SHCSR_R_BUSFAULTENA_BIT)
#define SCB_SHCSR_R_BUSFAULTENA_DIS    (SCB_SHCSR_BUSFAULTENA_DIS << SCB_SHCSR_R_BUSFAULTENA_BIT)
#define SCB_SHCSR_R_BUSFAULTENA_ENA    (SCB_SHCSR_BUSFAULTENA_ENA << SCB_SHCSR_R_BUSFAULTENA_BIT)
/*----------*/

/*----------*/
#define SCB_SHCSR_USGFAULTENA_MASK    ((UBase_t) 0x00000001UL)
#define SCB_SHCSR_USGFAULTENA_DIS    ((UBase_t) 0x00000000UL)
#define SCB_SHCSR_USGFAULTENA_ENA    ((UBase_t) 0x00000001UL)

#define SCB_SHCSR_R_USGFAULTENA_BIT    (18UL)

#define SCB_SHCSR_R_USGFAULTENA_MASK    (SCB_SHCSR_USGFAULTENA_MASK << SCB_SHCSR_R_USGFAULTENA_BIT)
#define SCB_SHCSR_R_USGFAULTENA_DIS    (SCB_SHCSR_USGFAULTENA_DIS << SCB_SHCSR_R_USGFAULTENA_BIT)
#define SCB_SHCSR_R_USGFAULTENA_ENA    (SCB_SHCSR_USGFAULTENA_ENA << SCB_SHCSR_R_USGFAULTENA_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 13 CFSR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_CFSR_IACCVIOL_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_IACCVIOL_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_IACCVIOL_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_IACCVIOL_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_IACCVIOL_BIT    (0UL)

#define SCB_CFSR_R_IACCVIOL_MASK    (SCB_CFSR_IACCVIOL_MASK << SCB_CFSR_R_IACCVIOL_BIT)
#define SCB_CFSR_R_IACCVIOL_INACTIVE    (SCB_CFSR_IACCVIOL_INACTIVE << SCB_CFSR_R_IACCVIOL_BIT)
#define SCB_CFSR_R_IACCVIOL_ACTIVE    (SCB_CFSR_IACCVIOL_ACTIVE << SCB_CFSR_R_IACCVIOL_BIT)
#define SCB_CFSR_R_IACCVIOL_CLEAR    (SCB_CFSR_IACCVIOL_CLEAR << SCB_CFSR_R_IACCVIOL_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_DACCVIOL_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_DACCVIOL_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_DACCVIOL_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_DACCVIOL_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_DACCVIOL_BIT    (1UL)

#define SCB_CFSR_R_DACCVIOL_MASK    (SCB_CFSR_DACCVIOL_MASK << SCB_CFSR_R_DACCVIOL_BIT)
#define SCB_CFSR_R_DACCVIOL_INACTIVE    (SCB_CFSR_DACCVIOL_INACTIVE << SCB_CFSR_R_DACCVIOL_BIT)
#define SCB_CFSR_R_DACCVIOL_ACTIVE    (SCB_CFSR_DACCVIOL_ACTIVE << SCB_CFSR_R_DACCVIOL_BIT)
#define SCB_CFSR_R_DACCVIOL_CLEAR    (SCB_CFSR_DACCVIOL_CLEAR << SCB_CFSR_R_DACCVIOL_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_MUNSTKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MUNSTKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_MUNSTKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MUNSTKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_MUNSTKERR_BIT    (3UL)

#define SCB_CFSR_R_MUNSTKERR_MASK    (SCB_CFSR_MUNSTKERR_MASK << SCB_CFSR_R_MUNSTKERR_BIT)
#define SCB_CFSR_R_MUNSTKERR_INACTIVE    (SCB_CFSR_MUNSTKERR_INACTIVE << SCB_CFSR_R_MUNSTKERR_BIT)
#define SCB_CFSR_R_MUNSTKERR_ACTIVE    (SCB_CFSR_MUNSTKERR_ACTIVE << SCB_CFSR_R_MUNSTKERR_BIT)
#define SCB_CFSR_R_MUNSTKERR_CLEAR    (SCB_CFSR_MUNSTKERR_CLEAR << SCB_CFSR_R_MUNSTKERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_MSTKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MSTKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_MSTKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MSTKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_MSTKERR_BIT    (4UL)

#define SCB_CFSR_R_MSTKERR_MASK    (SCB_CFSR_MSTKERR_MASK << SCB_CFSR_R_MSTKERR_BIT)
#define SCB_CFSR_R_MSTKERR_INACTIVE    (SCB_CFSR_MSTKERR_INACTIVE << SCB_CFSR_R_MSTKERR_BIT)
#define SCB_CFSR_R_MSTKERR_ACTIVE    (SCB_CFSR_MSTKERR_ACTIVE << SCB_CFSR_R_MSTKERR_BIT)
#define SCB_CFSR_R_MSTKERR_CLEAR    (SCB_CFSR_MSTKERR_CLEAR << SCB_CFSR_R_MSTKERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_MLSPERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MLSPERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_MLSPERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MLSPERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_MLSPERR_BIT    (5UL)

#define SCB_CFSR_R_MLSPERR_MASK    (SCB_CFSR_MLSPERR_MASK << SCB_CFSR_R_MLSPERR_BIT)
#define SCB_CFSR_R_MLSPERR_INACTIVE    (SCB_CFSR_MLSPERR_INACTIVE << SCB_CFSR_R_MLSPERR_BIT)
#define SCB_CFSR_R_MLSPERR_ACTIVE    (SCB_CFSR_MLSPERR_ACTIVE << SCB_CFSR_R_MLSPERR_BIT)
#define SCB_CFSR_R_MLSPERR_CLEAR    (SCB_CFSR_MLSPERR_CLEAR << SCB_CFSR_R_MLSPERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_MMARVALID_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MMARVALID_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_MMARVALID_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_MMARVALID_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_MMARVALID_BIT    (7UL)

#define SCB_CFSR_R_MMARVALID_MASK    (SCB_CFSR_MMARVALID_MASK << SCB_CFSR_R_MMARVALID_BIT)
#define SCB_CFSR_R_MMARVALID_INACTIVE    (SCB_CFSR_MMARVALID_INACTIVE << SCB_CFSR_R_MMARVALID_BIT)
#define SCB_CFSR_R_MMARVALID_ACTIVE    (SCB_CFSR_MMARVALID_ACTIVE << SCB_CFSR_R_MMARVALID_BIT)
#define SCB_CFSR_R_MMARVALID_CLEAR    (SCB_CFSR_MMARVALID_CLEAR << SCB_CFSR_R_MMARVALID_BIT)
/*----------*/




/*----------*/
#define SCB_CFSR_IBUSERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_IBUSERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_IBUSERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_IBUSERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_IBUSERR_BIT    (8UL)

#define SCB_CFSR_R_IBUSERR_MASK    (SCB_CFSR_IBUSERR_MASK << SCB_CFSR_R_IBUSERR_BIT)
#define SCB_CFSR_R_IBUSERR_INACTIVE    (SCB_CFSR_IBUSERR_INACTIVE << SCB_CFSR_R_IBUSERR_BIT)
#define SCB_CFSR_R_IBUSERR_ACTIVE    (SCB_CFSR_IBUSERR_ACTIVE << SCB_CFSR_R_IBUSERR_BIT)
#define SCB_CFSR_R_IBUSERR_CLEAR    (SCB_CFSR_IBUSERR_CLEAR << SCB_CFSR_R_IBUSERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_PRECISERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_PRECISERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_PRECISERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_PRECISERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_PRECISERR_BIT    (9UL)

#define SCB_CFSR_R_PRECISERR_MASK    (SCB_CFSR_PRECISERR_MASK << SCB_CFSR_R_PRECISERR_BIT)
#define SCB_CFSR_R_PRECISERR_INACTIVE    (SCB_CFSR_PRECISERR_INACTIVE << SCB_CFSR_R_PRECISERR_BIT)
#define SCB_CFSR_R_PRECISERR_ACTIVE    (SCB_CFSR_PRECISERR_ACTIVE << SCB_CFSR_R_PRECISERR_BIT)
#define SCB_CFSR_R_PRECISERR_CLEAR    (SCB_CFSR_PRECISERR_CLEAR << SCB_CFSR_R_PRECISERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_IMPRECISERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_IMPRECISERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_IMPRECISERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_IMPRECISERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_IMPRECISERR_BIT    (10UL)

#define SCB_CFSR_R_IMPRECISERR_MASK    (SCB_CFSR_IMPRECISERR_MASK << SCB_CFSR_R_IMPRECISERR_BIT)
#define SCB_CFSR_R_IMPRECISERR_INACTIVE    (SCB_CFSR_IMPRECISERR_INACTIVE << SCB_CFSR_R_IMPRECISERR_BIT)
#define SCB_CFSR_R_IMPRECISERR_ACTIVE    (SCB_CFSR_IMPRECISERR_ACTIVE << SCB_CFSR_R_IMPRECISERR_BIT)
#define SCB_CFSR_R_IMPRECISERR_CLEAR    (SCB_CFSR_IMPRECISERR_CLEAR << SCB_CFSR_R_IMPRECISERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_UNSTKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_UNSTKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_UNSTKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_UNSTKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_UNSTKERR_BIT    (11UL)

#define SCB_CFSR_R_UNSTKERR_MASK    (SCB_CFSR_UNSTKERR_MASK << SCB_CFSR_R_UNSTKERR_BIT)
#define SCB_CFSR_R_UNSTKERR_INACTIVE    (SCB_CFSR_UNSTKERR_INACTIVE << SCB_CFSR_R_UNSTKERR_BIT)
#define SCB_CFSR_R_UNSTKERR_ACTIVE    (SCB_CFSR_UNSTKERR_ACTIVE << SCB_CFSR_R_UNSTKERR_BIT)
#define SCB_CFSR_R_UNSTKERR_CLEAR    (SCB_CFSR_UNSTKERR_CLEAR << SCB_CFSR_R_UNSTKERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_STKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_STKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_STKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_STKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_STKERR_BIT    (12UL)

#define SCB_CFSR_R_STKERR_MASK    (SCB_CFSR_STKERR_MASK << SCB_CFSR_R_STKERR_BIT)
#define SCB_CFSR_R_STKERR_INACTIVE    (SCB_CFSR_STKERR_INACTIVE << SCB_CFSR_R_STKERR_BIT)
#define SCB_CFSR_R_STKERR_ACTIVE    (SCB_CFSR_STKERR_ACTIVE << SCB_CFSR_R_STKERR_BIT)
#define SCB_CFSR_R_STKERR_CLEAR    (SCB_CFSR_STKERR_CLEAR << SCB_CFSR_R_STKERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_LSPERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_LSPERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_LSPERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_LSPERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_LSPERR_BIT    (13UL)

#define SCB_CFSR_R_LSPERR_MASK    (SCB_CFSR_LSPERR_MASK << SCB_CFSR_R_LSPERR_BIT)
#define SCB_CFSR_R_LSPERR_INACTIVE    (SCB_CFSR_LSPERR_INACTIVE << SCB_CFSR_R_LSPERR_BIT)
#define SCB_CFSR_R_LSPERR_ACTIVE    (SCB_CFSR_LSPERR_ACTIVE << SCB_CFSR_R_LSPERR_BIT)
#define SCB_CFSR_R_LSPERR_CLEAR    (SCB_CFSR_LSPERR_CLEAR << SCB_CFSR_R_LSPERR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_BFARVALID_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_BFARVALID_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_BFARVALID_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_BFARVALID_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_BFARVALID_BIT    (15UL)

#define SCB_CFSR_R_BFARVALID_MASK    (SCB_CFSR_BFARVALID_MASK << SCB_CFSR_R_BFARVALID_BIT)
#define SCB_CFSR_R_BFARVALID_INACTIVE    (SCB_CFSR_BFARVALID_INACTIVE << SCB_CFSR_R_BFARVALID_BIT)
#define SCB_CFSR_R_BFARVALID_ACTIVE    (SCB_CFSR_BFARVALID_ACTIVE << SCB_CFSR_R_BFARVALID_BIT)
#define SCB_CFSR_R_BFARVALID_CLEAR    (SCB_CFSR_BFARVALID_CLEAR << SCB_CFSR_R_BFARVALID_BIT)
/*----------*/








/*----------*/
#define SCB_CFSR_UNDEFINSTR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_UNDEFINSTR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_UNDEFINSTR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_UNDEFINSTR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_UNDEFINSTR_BIT    (16UL)

#define SCB_CFSR_R_UNDEFINSTR_MASK    (SCB_CFSR_UNDEFINSTR_MASK << SCB_CFSR_R_UNDEFINSTR_BIT)
#define SCB_CFSR_R_UNDEFINSTR_INACTIVE    (SCB_CFSR_UNDEFINSTR_INACTIVE << SCB_CFSR_R_UNDEFINSTR_BIT)
#define SCB_CFSR_R_UNDEFINSTR_ACTIVE    (SCB_CFSR_UNDEFINSTR_ACTIVE << SCB_CFSR_R_UNDEFINSTR_BIT)
#define SCB_CFSR_R_UNDEFINSTR_CLEAR    (SCB_CFSR_UNDEFINSTR_CLEAR << SCB_CFSR_R_UNDEFINSTR_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_INVSTATE_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_INVSTATE_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_INVSTATE_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_INVSTATE_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_INVSTATE_BIT    (17UL)

#define SCB_CFSR_R_INVSTATE_MASK    (SCB_CFSR_INVSTATE_MASK << SCB_CFSR_R_INVSTATE_BIT)
#define SCB_CFSR_R_INVSTATE_INACTIVE    (SCB_CFSR_INVSTATE_INACTIVE << SCB_CFSR_R_INVSTATE_BIT)
#define SCB_CFSR_R_INVSTATE_ACTIVE    (SCB_CFSR_INVSTATE_ACTIVE << SCB_CFSR_R_INVSTATE_BIT)
#define SCB_CFSR_R_INVSTATE_CLEAR    (SCB_CFSR_INVSTATE_CLEAR << SCB_CFSR_R_INVSTATE_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_INVPC_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_INVPC_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_INVPC_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_INVPC_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_INVPC_BIT    (18UL)

#define SCB_CFSR_R_INVPC_MASK    (SCB_CFSR_INVPC_MASK << SCB_CFSR_R_INVPC_BIT)
#define SCB_CFSR_R_INVPC_INACTIVE    (SCB_CFSR_INVPC_INACTIVE << SCB_CFSR_R_INVPC_BIT)
#define SCB_CFSR_R_INVPC_ACTIVE    (SCB_CFSR_INVPC_ACTIVE << SCB_CFSR_R_INVPC_BIT)
#define SCB_CFSR_R_INVPC_CLEAR    (SCB_CFSR_INVPC_CLEAR << SCB_CFSR_R_INVPC_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_NOCP_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_NOCP_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_NOCP_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_NOCP_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_NOCP_BIT    (19UL)

#define SCB_CFSR_R_NOCP_MASK    (SCB_CFSR_NOCP_MASK << SCB_CFSR_R_NOCP_BIT)
#define SCB_CFSR_R_NOCP_INACTIVE    (SCB_CFSR_NOCP_INACTIVE << SCB_CFSR_R_NOCP_BIT)
#define SCB_CFSR_R_NOCP_ACTIVE    (SCB_CFSR_NOCP_ACTIVE << SCB_CFSR_R_NOCP_BIT)
#define SCB_CFSR_R_NOCP_CLEAR    (SCB_CFSR_NOCP_CLEAR << SCB_CFSR_R_NOCP_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_UNALIGNED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_UNALIGNED_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_UNALIGNED_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_UNALIGNED_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_UNALIGNED_BIT    (24UL)

#define SCB_CFSR_R_UNALIGNED_MASK    (SCB_CFSR_UNALIGNED_MASK << SCB_CFSR_R_UNALIGNED_BIT)
#define SCB_CFSR_R_UNALIGNED_INACTIVE    (SCB_CFSR_UNALIGNED_INACTIVE << SCB_CFSR_R_UNALIGNED_BIT)
#define SCB_CFSR_R_UNALIGNED_ACTIVE    (SCB_CFSR_UNALIGNED_ACTIVE << SCB_CFSR_R_UNALIGNED_BIT)
#define SCB_CFSR_R_UNALIGNED_CLEAR    (SCB_CFSR_UNALIGNED_CLEAR << SCB_CFSR_R_UNALIGNED_BIT)
/*----------*/

/*----------*/
#define SCB_CFSR_DIVBYZERO_MASK    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_DIVBYZERO_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_CFSR_DIVBYZERO_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_CFSR_DIVBYZERO_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_CFSR_R_DIVBYZERO_BIT    (25UL)

#define SCB_CFSR_R_DIVBYZERO_MASK    (SCB_CFSR_DIVBYZERO_MASK << SCB_CFSR_R_DIVBYZERO_BIT)
#define SCB_CFSR_R_DIVBYZERO_INACTIVE    (SCB_CFSR_DIVBYZERO_INACTIVE << SCB_CFSR_R_DIVBYZERO_BIT)
#define SCB_CFSR_R_DIVBYZERO_ACTIVE    (SCB_CFSR_DIVBYZERO_ACTIVE << SCB_CFSR_R_DIVBYZERO_BIT)
#define SCB_CFSR_R_DIVBYZERO_CLEAR    (SCB_CFSR_DIVBYZERO_CLEAR << SCB_CFSR_R_DIVBYZERO_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 13_1 UCFSR ***********************************************/
/********************************************************************************************/

/*----------*/
#define SCB_UCFSR_UNDEFINSTR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_UNDEFINSTR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_UCFSR_UNDEFINSTR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_UNDEFINSTR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_UCFSR_R_UNDEFINSTR_BIT    (0UL)

#define SCB_UCFSR_R_UNDEFINSTR_MASK    (SCB_UCFSR_UNDEFINSTR_MASK << SCB_UCFSR_R_UNDEFINSTR_BIT)
#define SCB_UCFSR_R_UNDEFINSTR_INACTIVE    (SCB_UCFSR_UNDEFINSTR_INACTIVE << SCB_UCFSR_R_UNDEFINSTR_BIT)
#define SCB_UCFSR_R_UNDEFINSTR_ACTIVE    (SCB_UCFSR_UNDEFINSTR_ACTIVE << SCB_UCFSR_R_UNDEFINSTR_BIT)
#define SCB_UCFSR_R_UNDEFINSTR_CLEAR    (SCB_UCFSR_UNDEFINSTR_CLEAR << SCB_UCFSR_R_UNDEFINSTR_BIT)
/*----------*/

/*----------*/
#define SCB_UCFSR_INVSTATE_MASK    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_INVSTATE_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_UCFSR_INVSTATE_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_INVSTATE_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_UCFSR_R_INVSTATE_BIT    (1UL)

#define SCB_UCFSR_R_INVSTATE_MASK    (SCB_UCFSR_INVSTATE_MASK << SCB_UCFSR_R_INVSTATE_BIT)
#define SCB_UCFSR_R_INVSTATE_INACTIVE    (SCB_UCFSR_INVSTATE_INACTIVE << SCB_UCFSR_R_INVSTATE_BIT)
#define SCB_UCFSR_R_INVSTATE_ACTIVE    (SCB_UCFSR_INVSTATE_ACTIVE << SCB_UCFSR_R_INVSTATE_BIT)
#define SCB_UCFSR_R_INVSTATE_CLEAR    (SCB_UCFSR_INVSTATE_CLEAR << SCB_UCFSR_R_INVSTATE_BIT)
/*----------*/

/*----------*/
#define SCB_UCFSR_INVPC_MASK    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_INVPC_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_UCFSR_INVPC_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_INVPC_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_UCFSR_R_INVPC_BIT    (2UL)

#define SCB_UCFSR_R_INVPC_MASK    (SCB_UCFSR_INVPC_MASK << SCB_UCFSR_R_INVPC_BIT)
#define SCB_UCFSR_R_INVPC_INACTIVE    (SCB_UCFSR_INVPC_INACTIVE << SCB_UCFSR_R_INVPC_BIT)
#define SCB_UCFSR_R_INVPC_ACTIVE    (SCB_UCFSR_INVPC_ACTIVE << SCB_UCFSR_R_INVPC_BIT)
#define SCB_UCFSR_R_INVPC_CLEAR    (SCB_UCFSR_INVPC_CLEAR << SCB_UCFSR_R_INVPC_BIT)
/*----------*/

/*----------*/
#define SCB_UCFSR_NOCP_MASK    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_NOCP_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_UCFSR_NOCP_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_NOCP_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_UCFSR_R_NOCP_BIT    (3UL)

#define SCB_UCFSR_R_NOCP_MASK    (SCB_UCFSR_NOCP_MASK << SCB_UCFSR_R_NOCP_BIT)
#define SCB_UCFSR_R_NOCP_INACTIVE    (SCB_UCFSR_NOCP_INACTIVE << SCB_UCFSR_R_NOCP_BIT)
#define SCB_UCFSR_R_NOCP_ACTIVE    (SCB_UCFSR_NOCP_ACTIVE << SCB_UCFSR_R_NOCP_BIT)
#define SCB_UCFSR_R_NOCP_CLEAR    (SCB_UCFSR_NOCP_CLEAR << SCB_UCFSR_R_NOCP_BIT)
/*----------*/

/*----------*/
#define SCB_UCFSR_UNALIGNED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_UNALIGNED_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_UCFSR_UNALIGNED_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_UNALIGNED_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_UCFSR_R_UNALIGNED_BIT    (8UL)

#define SCB_UCFSR_R_UNALIGNED_MASK    (SCB_UCFSR_UNALIGNED_MASK << SCB_UCFSR_R_UNALIGNED_BIT)
#define SCB_UCFSR_R_UNALIGNED_INACTIVE    (SCB_UCFSR_UNALIGNED_INACTIVE << SCB_UCFSR_R_UNALIGNED_BIT)
#define SCB_UCFSR_R_UNALIGNED_ACTIVE    (SCB_UCFSR_UNALIGNED_ACTIVE << SCB_UCFSR_R_UNALIGNED_BIT)
#define SCB_UCFSR_R_UNALIGNED_CLEAR    (SCB_UCFSR_UNALIGNED_CLEAR << SCB_UCFSR_R_UNALIGNED_BIT)
/*----------*/

/*----------*/
#define SCB_UCFSR_DIVBYZERO_MASK    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_DIVBYZERO_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_UCFSR_DIVBYZERO_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_UCFSR_DIVBYZERO_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_UCFSR_R_DIVBYZERO_BIT    (9UL)

#define SCB_UCFSR_R_DIVBYZERO_MASK    (SCB_UCFSR_DIVBYZERO_MASK << SCB_UCFSR_R_DIVBYZERO_BIT)
#define SCB_UCFSR_R_DIVBYZERO_INACTIVE    (SCB_UCFSR_DIVBYZERO_INACTIVE << SCB_UCFSR_R_DIVBYZERO_BIT)
#define SCB_UCFSR_R_DIVBYZERO_ACTIVE    (SCB_UCFSR_DIVBYZERO_ACTIVE << SCB_UCFSR_R_DIVBYZERO_BIT)
#define SCB_UCFSR_R_DIVBYZERO_CLEAR    (SCB_UCFSR_DIVBYZERO_CLEAR << SCB_UCFSR_R_DIVBYZERO_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 13_2 BCFSR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_BCFSR_IBUSERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_IBUSERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_IBUSERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_IBUSERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_IBUSERR_BIT    (0UL)

#define SCB_BCFSR_R_IBUSERR_MASK    (SCB_BCFSR_IBUSERR_MASK << SCB_BCFSR_R_IBUSERR_BIT)
#define SCB_BCFSR_R_IBUSERR_INACTIVE    (SCB_BCFSR_IBUSERR_INACTIVE << SCB_BCFSR_R_IBUSERR_BIT)
#define SCB_BCFSR_R_IBUSERR_ACTIVE    (SCB_BCFSR_IBUSERR_ACTIVE << SCB_BCFSR_R_IBUSERR_BIT)
#define SCB_BCFSR_R_IBUSERR_CLEAR    (SCB_BCFSR_IBUSERR_CLEAR << SCB_BCFSR_R_IBUSERR_BIT)
/*----------*/

/*----------*/
#define SCB_BCFSR_PRECISERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_PRECISERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_PRECISERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_PRECISERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_PRECISERR_BIT    (1UL)

#define SCB_BCFSR_R_PRECISERR_MASK    (SCB_BCFSR_PRECISERR_MASK << SCB_BCFSR_R_PRECISERR_BIT)
#define SCB_BCFSR_R_PRECISERR_INACTIVE    (SCB_BCFSR_PRECISERR_INACTIVE << SCB_BCFSR_R_PRECISERR_BIT)
#define SCB_BCFSR_R_PRECISERR_ACTIVE    (SCB_BCFSR_PRECISERR_ACTIVE << SCB_BCFSR_R_PRECISERR_BIT)
#define SCB_BCFSR_R_PRECISERR_CLEAR    (SCB_BCFSR_PRECISERR_CLEAR << SCB_BCFSR_R_PRECISERR_BIT)
/*----------*/

/*----------*/
#define SCB_BCFSR_IMPRECISERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_IMPRECISERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_IMPRECISERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_IMPRECISERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_IMPRECISERR_BIT    (2UL)

#define SCB_BCFSR_R_IMPRECISERR_MASK    (SCB_BCFSR_IMPRECISERR_MASK << SCB_BCFSR_R_IMPRECISERR_BIT)
#define SCB_BCFSR_R_IMPRECISERR_INACTIVE    (SCB_BCFSR_IMPRECISERR_INACTIVE << SCB_BCFSR_R_IMPRECISERR_BIT)
#define SCB_BCFSR_R_IMPRECISERR_ACTIVE    (SCB_BCFSR_IMPRECISERR_ACTIVE << SCB_BCFSR_R_IMPRECISERR_BIT)
#define SCB_BCFSR_R_IMPRECISERR_CLEAR    (SCB_BCFSR_IMPRECISERR_CLEAR << SCB_BCFSR_R_IMPRECISERR_BIT)
/*----------*/

/*----------*/
#define SCB_BCFSR_UNSTKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_UNSTKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_UNSTKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_UNSTKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_UNSTKERR_BIT    (3UL)

#define SCB_BCFSR_R_UNSTKERR_MASK    (SCB_BCFSR_UNSTKERR_MASK << SCB_BCFSR_R_UNSTKERR_BIT)
#define SCB_BCFSR_R_UNSTKERR_INACTIVE    (SCB_BCFSR_UNSTKERR_INACTIVE << SCB_BCFSR_R_UNSTKERR_BIT)
#define SCB_BCFSR_R_UNSTKERR_ACTIVE    (SCB_BCFSR_UNSTKERR_ACTIVE << SCB_BCFSR_R_UNSTKERR_BIT)
#define SCB_BCFSR_R_UNSTKERR_CLEAR    (SCB_BCFSR_UNSTKERR_CLEAR << SCB_BCFSR_R_UNSTKERR_BIT)
/*----------*/

/*----------*/
#define SCB_BCFSR_STKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_STKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_STKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_STKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_STKERR_BIT    (4UL)

#define SCB_BCFSR_R_STKERR_MASK    (SCB_BCFSR_STKERR_MASK << SCB_BCFSR_R_STKERR_BIT)
#define SCB_BCFSR_R_STKERR_INACTIVE    (SCB_BCFSR_STKERR_INACTIVE << SCB_BCFSR_R_STKERR_BIT)
#define SCB_BCFSR_R_STKERR_ACTIVE    (SCB_BCFSR_STKERR_ACTIVE << SCB_BCFSR_R_STKERR_BIT)
#define SCB_BCFSR_R_STKERR_CLEAR    (SCB_BCFSR_STKERR_CLEAR << SCB_BCFSR_R_STKERR_BIT)
/*----------*/

/*----------*/
#define SCB_BCFSR_LSPERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_LSPERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_LSPERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_LSPERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_LSPERR_BIT    (5UL)

#define SCB_BCFSR_R_LSPERR_MASK    (SCB_BCFSR_LSPERR_MASK << SCB_BCFSR_R_LSPERR_BIT)
#define SCB_BCFSR_R_LSPERR_INACTIVE    (SCB_BCFSR_LSPERR_INACTIVE << SCB_BCFSR_R_LSPERR_BIT)
#define SCB_BCFSR_R_LSPERR_ACTIVE    (SCB_BCFSR_LSPERR_ACTIVE << SCB_BCFSR_R_LSPERR_BIT)
#define SCB_BCFSR_R_LSPERR_CLEAR    (SCB_BCFSR_LSPERR_CLEAR << SCB_BCFSR_R_LSPERR_BIT)
/*----------*/

/*----------*/
#define SCB_BCFSR_BFARVALID_MASK    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_BFARVALID_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_BCFSR_BFARVALID_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_BCFSR_BFARVALID_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_BCFSR_R_BFARVALID_BIT    (7UL)

#define SCB_BCFSR_R_BFARVALID_MASK    (SCB_BCFSR_BFARVALID_MASK << SCB_BCFSR_R_BFARVALID_BIT)
#define SCB_BCFSR_R_BFARVALID_INACTIVE    (SCB_BCFSR_BFARVALID_INACTIVE << SCB_BCFSR_R_BFARVALID_BIT)
#define SCB_BCFSR_R_BFARVALID_ACTIVE    (SCB_BCFSR_BFARVALID_ACTIVE << SCB_BCFSR_R_BFARVALID_BIT)
#define SCB_BCFSR_R_BFARVALID_CLEAR    (SCB_BCFSR_BFARVALID_CLEAR << SCB_BCFSR_R_BFARVALID_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 13_3 MCFSR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_MCFSR_IACCVIOL_MASK    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_IACCVIOL_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_MCFSR_IACCVIOL_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_IACCVIOL_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_MCFSR_R_IACCVIOL_BIT    (0UL)

#define SCB_MCFSR_R_IACCVIOL_MASK    (SCB_MCFSR_IACCVIOL_MASK << SCB_MCFSR_R_IACCVIOL_BIT)
#define SCB_MCFSR_R_IACCVIOL_INACTIVE    (SCB_MCFSR_IACCVIOL_INACTIVE << SCB_MCFSR_R_IACCVIOL_BIT)
#define SCB_MCFSR_R_IACCVIOL_ACTIVE    (SCB_MCFSR_IACCVIOL_ACTIVE << SCB_MCFSR_R_IACCVIOL_BIT)
#define SCB_MCFSR_R_IACCVIOL_CLEAR    (SCB_MCFSR_IACCVIOL_CLEAR << SCB_MCFSR_R_IACCVIOL_BIT)
/*----------*/

/*----------*/
#define SCB_MCFSR_DACCVIOL_MASK    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_DACCVIOL_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_MCFSR_DACCVIOL_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_DACCVIOL_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_MCFSR_R_DACCVIOL_BIT    (1UL)

#define SCB_MCFSR_R_DACCVIOL_MASK    (SCB_MCFSR_DACCVIOL_MASK << SCB_MCFSR_R_DACCVIOL_BIT)
#define SCB_MCFSR_R_DACCVIOL_INACTIVE    (SCB_MCFSR_DACCVIOL_INACTIVE << SCB_MCFSR_R_DACCVIOL_BIT)
#define SCB_MCFSR_R_DACCVIOL_ACTIVE    (SCB_MCFSR_DACCVIOL_ACTIVE << SCB_MCFSR_R_DACCVIOL_BIT)
#define SCB_MCFSR_R_DACCVIOL_CLEAR    (SCB_MCFSR_DACCVIOL_CLEAR << SCB_MCFSR_R_DACCVIOL_BIT)
/*----------*/

/*----------*/
#define SCB_MCFSR_MUNSTKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MUNSTKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_MCFSR_MUNSTKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MUNSTKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_MCFSR_R_MUNSTKERR_BIT    (3UL)

#define SCB_MCFSR_R_MUNSTKERR_MASK    (SCB_MCFSR_MUNSTKERR_MASK << SCB_MCFSR_R_MUNSTKERR_BIT)
#define SCB_MCFSR_R_MUNSTKERR_INACTIVE    (SCB_MCFSR_MUNSTKERR_INACTIVE << SCB_MCFSR_R_MUNSTKERR_BIT)
#define SCB_MCFSR_R_MUNSTKERR_ACTIVE    (SCB_MCFSR_MUNSTKERR_ACTIVE << SCB_MCFSR_R_MUNSTKERR_BIT)
#define SCB_MCFSR_R_MUNSTKERR_CLEAR    (SCB_MCFSR_MUNSTKERR_CLEAR << SCB_MCFSR_R_MUNSTKERR_BIT)
/*----------*/

/*----------*/
#define SCB_MCFSR_MSTKERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MSTKERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_MCFSR_MSTKERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MSTKERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_MCFSR_R_MSTKERR_BIT    (4UL)

#define SCB_MCFSR_R_MSTKERR_MASK    (SCB_MCFSR_MSTKERR_MASK << SCB_MCFSR_R_MSTKERR_BIT)
#define SCB_MCFSR_R_MSTKERR_INACTIVE    (SCB_MCFSR_MSTKERR_INACTIVE << SCB_MCFSR_R_MSTKERR_BIT)
#define SCB_MCFSR_R_MSTKERR_ACTIVE    (SCB_MCFSR_MSTKERR_ACTIVE << SCB_MCFSR_R_MSTKERR_BIT)
#define SCB_MCFSR_R_MSTKERR_CLEAR    (SCB_MCFSR_MSTKERR_CLEAR << SCB_MCFSR_R_MSTKERR_BIT)
/*----------*/

/*----------*/
#define SCB_MCFSR_MLSPERR_MASK    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MLSPERR_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_MCFSR_MLSPERR_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MLSPERR_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_MCFSR_R_MLSPERR_BIT    (5UL)

#define SCB_MCFSR_R_MLSPERR_MASK    (SCB_MCFSR_MLSPERR_MASK << SCB_MCFSR_R_MLSPERR_BIT)
#define SCB_MCFSR_R_MLSPERR_INACTIVE    (SCB_MCFSR_MLSPERR_INACTIVE << SCB_MCFSR_R_MLSPERR_BIT)
#define SCB_MCFSR_R_MLSPERR_ACTIVE    (SCB_MCFSR_MLSPERR_ACTIVE << SCB_MCFSR_R_MLSPERR_BIT)
#define SCB_MCFSR_R_MLSPERR_CLEAR    (SCB_MCFSR_MLSPERR_CLEAR << SCB_MCFSR_R_MLSPERR_BIT)
/*----------*/

/*----------*/
#define SCB_MCFSR_MMARVALID_MASK    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MMARVALID_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_MCFSR_MMARVALID_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_MCFSR_MMARVALID_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_MCFSR_R_MMARVALID_BIT    (7UL)

#define SCB_MCFSR_R_MMARVALID_MASK    (SCB_MCFSR_MMARVALID_MASK << SCB_MCFSR_R_MMARVALID_BIT)
#define SCB_MCFSR_R_MMARVALID_INACTIVE    (SCB_MCFSR_MMARVALID_INACTIVE << SCB_MCFSR_R_MMARVALID_BIT)
#define SCB_MCFSR_R_MMARVALID_ACTIVE    (SCB_MCFSR_MMARVALID_ACTIVE << SCB_MCFSR_R_MMARVALID_BIT)
#define SCB_MCFSR_R_MMARVALID_CLEAR    (SCB_MCFSR_MMARVALID_CLEAR << SCB_MCFSR_R_MMARVALID_BIT)
/*----------*/
/********************************************************************************************/
/************************************* 14 HFSR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_HFSR_VECTTBL_MASK    ((UBase_t) 0x00000001UL)
#define SCB_HFSR_VECTTBL_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_HFSR_VECTTBL_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_HFSR_VECTTBL_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_HFSR_R_VECTTBL_BIT    (1UL)

#define SCB_HFSR_R_VECTTBL_MASK    (SCB_HFSR_VECTTBL_MASK << SCB_HFSR_R_VECTTBL_BIT)
#define SCB_HFSR_R_VECTTBL_INACTIVE    (SCB_HFSR_VECTTBL_INACTIVE << SCB_HFSR_R_VECTTBL_BIT)
#define SCB_HFSR_R_VECTTBL_ACTIVE    (SCB_HFSR_VECTTBL_ACTIVE << SCB_HFSR_R_VECTTBL_BIT)
#define SCB_HFSR_R_VECTTBL_CLEAR    (SCB_HFSR_VECTTBL_CLEAR << SCB_HFSR_R_VECTTBL_BIT)
/*----------*/

/*----------*/
#define SCB_HFSR_FORCED_MASK    ((UBase_t) 0x00000001UL)
#define SCB_HFSR_FORCED_INACTIVE    ((UBase_t) 0x00000000UL)
#define SCB_HFSR_FORCED_ACTIVE    ((UBase_t) 0x00000001UL)
#define SCB_HFSR_FORCED_CLEAR    ((UBase_t) 0x00000001UL)

#define SCB_HFSR_R_FORCED_BIT    (30UL)

#define SCB_HFSR_R_FORCED_MASK    (SCB_HFSR_FORCED_MASK << SCB_HFSR_R_FORCED_BIT)
#define SCB_HFSR_R_FORCED_INACTIVE    (SCB_HFSR_FORCED_INACTIVE << SCB_HFSR_R_FORCED_BIT)
#define SCB_HFSR_R_FORCED_ACTIVE    (SCB_HFSR_FORCED_ACTIVE << SCB_HFSR_R_FORCED_BIT)
#define SCB_HFSR_R_FORCED_CLEAR    (SCB_HFSR_FORCED_CLEAR << SCB_HFSR_R_FORCED_BIT)
/*----------*/

/*----------*/
#define SCB_HFSR_DEBUGEVT_MASK    ((UBase_t) 0x00000001UL)

#define SCB_HFSR_R_DEBUGEVT_BIT    (30UL)

#define SCB_HFSR_R_DEBUGEVT_MASK    (SCB_HFSR_DEBUGEVT_MASK << SCB_HFSR_R_DEBUGEVT_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 15 MMFAR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_MMFAR_ADDRESS_MASK    ((UBase_t) 0xFFFFFFFFUL)

#define SCB_MMFAR_R_ADDRESS_BIT    (0UL)

#define SCB_MMFAR_R_ADDRESS_MASK    (SCB_MMFAR_ADDRESS_MASK << SCB_MMFAR_R_ADDRESS_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 16 BFAR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_BFAR_ADDRESS_MASK    ((UBase_t) 0xFFFFFFFFUL)

#define SCB_BFAR_R_ADDRESS_BIT    (0UL)

#define SCB_BFAR_R_ADDRESS_MASK    (SCB_BFAR_ADDRESS_MASK << SCB_BFAR_R_ADDRESS_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 17 AFSR ***********************************************/
/********************************************************************************************/
/*----------*/
#define SCB_AFSR_IMPDEF_MASK    ((UBase_t) 0xFFFFFFFFUL)

#define SCB_AFSR_R_IMPDEF_BIT    (0UL)

#define SCB_AFSR_R_IMPDEF_MASK    (SCB_AFSR_IMPDEF_MASK << SCB_AFSR_R_IMPDEF_BIT)
/*----------*/

/********************************************************************************************/
/************************************* 18 PFR0 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 19 PFR1 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 20 DFR0 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 21 AFR0 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 22 MMFR0 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 23 MMFR1 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 24 MMFR2 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 25 MMFR3 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 26 ISAR0 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 27 ISAR1 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 28 ISAR2 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 29 ISAR3 ***********************************************/
/********************************************************************************************/

/********************************************************************************************/
/************************************* 30 ISAR4 ***********************************************/
/********************************************************************************************/

#endif /* XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_REGISTER_SCB_REGISTERDEFINES_H_ */
