/**
 *
 * @file NVIC_RegisterDefines_Set_Generic_ICPR.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 16 nov. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 16 nov. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_CORE_NVIC_PERIPHERAL_REGISTER_REGISTERDEFINES_REGISTERDEFINES_SET_REGISTERDEFINES_SET_GENERIC_XHEADER_NVIC_REGISTERDEFINES_SET_GENERIC_ICPR_H_
#define XDRIVER_MCU_CORE_NVIC_PERIPHERAL_REGISTER_REGISTERDEFINES_REGISTERDEFINES_SET_REGISTERDEFINES_SET_GENERIC_XHEADER_NVIC_REGISTERDEFINES_SET_GENERIC_ICPR_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/xHeader/NVIC_Enum.h>

/********************************************************************************************/
/************************************* ICPR ***********************************************/
/********************************************************************************************/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL0_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL0_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL0_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL0_BIT    (0UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL0_MASK    (NVIC_ICPR_NVIC_PERIPHERAL0_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL0_DIS    (NVIC_ICPR_NVIC_PERIPHERAL0_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL0_ENA    (NVIC_ICPR_NVIC_PERIPHERAL0_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL0_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL1_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL1_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL1_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL1_BIT    (1UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL1_MASK    (NVIC_ICPR_NVIC_PERIPHERAL1_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL1_DIS    (NVIC_ICPR_NVIC_PERIPHERAL1_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL1_ENA    (NVIC_ICPR_NVIC_PERIPHERAL1_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL1_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL2_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL2_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL2_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL2_BIT    (2UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL2_MASK    (NVIC_ICPR_NVIC_PERIPHERAL2_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL2_DIS    (NVIC_ICPR_NVIC_PERIPHERAL2_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL2_ENA    (NVIC_ICPR_NVIC_PERIPHERAL2_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL2_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL3_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL3_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL3_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL3_BIT    (3UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL3_MASK    (NVIC_ICPR_NVIC_PERIPHERAL3_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL3_DIS    (NVIC_ICPR_NVIC_PERIPHERAL3_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL3_ENA    (NVIC_ICPR_NVIC_PERIPHERAL3_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL3_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL4_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL4_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL4_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL4_BIT    (4UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL4_MASK    (NVIC_ICPR_NVIC_PERIPHERAL4_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL4_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL4_DIS    (NVIC_ICPR_NVIC_PERIPHERAL4_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL4_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL4_ENA    (NVIC_ICPR_NVIC_PERIPHERAL4_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL4_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL5_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL5_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL5_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL5_BIT    (5UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL5_MASK    (NVIC_ICPR_NVIC_PERIPHERAL5_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL5_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL5_DIS    (NVIC_ICPR_NVIC_PERIPHERAL5_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL5_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL5_ENA    (NVIC_ICPR_NVIC_PERIPHERAL5_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL5_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL6_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL6_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL6_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL6_BIT    (6UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL6_MASK    (NVIC_ICPR_NVIC_PERIPHERAL6_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL6_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL6_DIS    (NVIC_ICPR_NVIC_PERIPHERAL6_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL6_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL6_ENA    (NVIC_ICPR_NVIC_PERIPHERAL6_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL6_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL7_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL7_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL7_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL7_BIT    (7UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL7_MASK    (NVIC_ICPR_NVIC_PERIPHERAL7_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL7_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL7_DIS    (NVIC_ICPR_NVIC_PERIPHERAL7_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL7_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL7_ENA    (NVIC_ICPR_NVIC_PERIPHERAL7_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL7_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL8_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL8_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL8_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL8_BIT    (8UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL8_MASK    (NVIC_ICPR_NVIC_PERIPHERAL8_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL8_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL8_DIS    (NVIC_ICPR_NVIC_PERIPHERAL8_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL8_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL8_ENA    (NVIC_ICPR_NVIC_PERIPHERAL8_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL8_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL9_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL9_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL9_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL9_BIT    (9UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL9_MASK    (NVIC_ICPR_NVIC_PERIPHERAL9_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL9_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL9_DIS    (NVIC_ICPR_NVIC_PERIPHERAL9_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL9_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL9_ENA    (NVIC_ICPR_NVIC_PERIPHERAL9_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL9_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL10_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL10_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL10_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL10_BIT    (10UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL10_MASK    (NVIC_ICPR_NVIC_PERIPHERAL10_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL10_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL10_DIS    (NVIC_ICPR_NVIC_PERIPHERAL10_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL10_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL10_ENA    (NVIC_ICPR_NVIC_PERIPHERAL10_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL10_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL11_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL11_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL11_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL11_BIT    (11UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL11_MASK    (NVIC_ICPR_NVIC_PERIPHERAL11_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL11_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL11_DIS    (NVIC_ICPR_NVIC_PERIPHERAL11_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL11_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL11_ENA    (NVIC_ICPR_NVIC_PERIPHERAL11_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL11_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL12_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL12_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL12_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL12_BIT    (12UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL12_MASK    (NVIC_ICPR_NVIC_PERIPHERAL12_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL12_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL12_DIS    (NVIC_ICPR_NVIC_PERIPHERAL12_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL12_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL12_ENA    (NVIC_ICPR_NVIC_PERIPHERAL12_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL12_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL13_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL13_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL13_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL13_BIT    (13UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL13_MASK    (NVIC_ICPR_NVIC_PERIPHERAL13_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL13_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL13_DIS    (NVIC_ICPR_NVIC_PERIPHERAL13_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL13_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL13_ENA    (NVIC_ICPR_NVIC_PERIPHERAL13_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL13_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL14_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL14_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL14_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL14_BIT    (14UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL14_MASK    (NVIC_ICPR_NVIC_PERIPHERAL14_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL14_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL14_DIS    (NVIC_ICPR_NVIC_PERIPHERAL14_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL14_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL14_ENA    (NVIC_ICPR_NVIC_PERIPHERAL14_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL14_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL15_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL15_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL15_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL15_BIT    (15UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL15_MASK    (NVIC_ICPR_NVIC_PERIPHERAL15_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL15_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL15_DIS    (NVIC_ICPR_NVIC_PERIPHERAL15_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL15_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL15_ENA    (NVIC_ICPR_NVIC_PERIPHERAL15_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL15_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL16_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL16_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL16_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL16_BIT    (16UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL16_MASK    (NVIC_ICPR_NVIC_PERIPHERAL16_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL16_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL16_DIS    (NVIC_ICPR_NVIC_PERIPHERAL16_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL16_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL16_ENA    (NVIC_ICPR_NVIC_PERIPHERAL16_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL16_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL17_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL17_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL17_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL17_BIT    (17UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL17_MASK    (NVIC_ICPR_NVIC_PERIPHERAL17_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL17_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL17_DIS    (NVIC_ICPR_NVIC_PERIPHERAL17_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL17_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL17_ENA    (NVIC_ICPR_NVIC_PERIPHERAL17_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL17_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL18_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL18_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL18_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL18_BIT    (18UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL18_MASK    (NVIC_ICPR_NVIC_PERIPHERAL18_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL18_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL18_DIS    (NVIC_ICPR_NVIC_PERIPHERAL18_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL18_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL18_ENA    (NVIC_ICPR_NVIC_PERIPHERAL18_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL18_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL19_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL19_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL19_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL19_BIT    (19UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL19_MASK    (NVIC_ICPR_NVIC_PERIPHERAL19_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL19_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL19_DIS    (NVIC_ICPR_NVIC_PERIPHERAL19_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL19_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL19_ENA    (NVIC_ICPR_NVIC_PERIPHERAL19_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL19_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL20_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL20_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL20_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL20_BIT    (20UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL20_MASK    (NVIC_ICPR_NVIC_PERIPHERAL20_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL20_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL20_DIS    (NVIC_ICPR_NVIC_PERIPHERAL20_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL20_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL20_ENA    (NVIC_ICPR_NVIC_PERIPHERAL20_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL20_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL21_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL21_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL21_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL21_BIT    (21UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL21_MASK    (NVIC_ICPR_NVIC_PERIPHERAL21_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL21_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL21_DIS    (NVIC_ICPR_NVIC_PERIPHERAL21_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL21_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL21_ENA    (NVIC_ICPR_NVIC_PERIPHERAL21_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL21_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL22_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL22_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL22_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL22_BIT    (22UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL22_MASK    (NVIC_ICPR_NVIC_PERIPHERAL22_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL22_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL22_DIS    (NVIC_ICPR_NVIC_PERIPHERAL22_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL22_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL22_ENA    (NVIC_ICPR_NVIC_PERIPHERAL22_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL22_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL23_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL23_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL23_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL23_BIT    (23UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL23_MASK    (NVIC_ICPR_NVIC_PERIPHERAL23_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL23_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL23_DIS    (NVIC_ICPR_NVIC_PERIPHERAL23_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL23_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL23_ENA    (NVIC_ICPR_NVIC_PERIPHERAL23_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL23_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL24_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL24_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL24_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL24_BIT    (24UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL24_MASK    (NVIC_ICPR_NVIC_PERIPHERAL24_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL24_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL24_DIS    (NVIC_ICPR_NVIC_PERIPHERAL24_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL24_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL24_ENA    (NVIC_ICPR_NVIC_PERIPHERAL24_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL24_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL25_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL25_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL25_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL25_BIT    (25UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL25_MASK    (NVIC_ICPR_NVIC_PERIPHERAL25_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL25_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL25_DIS    (NVIC_ICPR_NVIC_PERIPHERAL25_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL25_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL25_ENA    (NVIC_ICPR_NVIC_PERIPHERAL25_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL25_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL26_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL26_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL26_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL26_BIT    (26UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL26_MASK    (NVIC_ICPR_NVIC_PERIPHERAL26_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL26_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL26_DIS    (NVIC_ICPR_NVIC_PERIPHERAL26_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL26_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL26_ENA    (NVIC_ICPR_NVIC_PERIPHERAL26_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL26_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL27_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL27_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL27_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL27_BIT    (27UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL27_MASK    (NVIC_ICPR_NVIC_PERIPHERAL27_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL27_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL27_DIS    (NVIC_ICPR_NVIC_PERIPHERAL27_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL27_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL27_ENA    (NVIC_ICPR_NVIC_PERIPHERAL27_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL27_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL28_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL28_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL28_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL28_BIT    (28UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL28_MASK    (NVIC_ICPR_NVIC_PERIPHERAL28_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL28_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL28_DIS    (NVIC_ICPR_NVIC_PERIPHERAL28_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL28_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL28_ENA    (NVIC_ICPR_NVIC_PERIPHERAL28_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL28_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL29_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL29_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL29_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL29_BIT    (29UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL29_MASK    (NVIC_ICPR_NVIC_PERIPHERAL29_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL29_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL29_DIS    (NVIC_ICPR_NVIC_PERIPHERAL29_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL29_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL29_ENA    (NVIC_ICPR_NVIC_PERIPHERAL29_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL29_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL30_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL30_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL30_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL30_BIT    (30UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL30_MASK    (NVIC_ICPR_NVIC_PERIPHERAL30_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL30_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL30_DIS    (NVIC_ICPR_NVIC_PERIPHERAL30_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL30_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL30_ENA    (NVIC_ICPR_NVIC_PERIPHERAL30_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL30_BIT)
/*----------*/

/*----------*/
#define NVIC_ICPR_NVIC_PERIPHERAL31_MASK    ((UBase_t) 0x00000001UL)
#define NVIC_ICPR_NVIC_PERIPHERAL31_DIS    ((UBase_t) 0x00000000UL)
#define NVIC_ICPR_NVIC_PERIPHERAL31_ENA    ((UBase_t) 0x00000001UL)

#define NVIC_ICPR_R_NVIC_PERIPHERAL31_BIT    (31UL)
#define NVIC_ICPR_R_NVIC_PERIPHERAL31_MASK    (NVIC_ICPR_NVIC_PERIPHERAL31_MASK << NVIC_ICPR_R_NVIC_PERIPHERAL31_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL31_DIS    (NVIC_ICPR_NVIC_PERIPHERAL31_DIS << NVIC_ICPR_R_NVIC_PERIPHERAL31_BIT)
#define NVIC_ICPR_R_NVIC_PERIPHERAL31_ENA    (NVIC_ICPR_NVIC_PERIPHERAL31_ENA << NVIC_ICPR_R_NVIC_PERIPHERAL31_BIT)
/*----------*/

#endif /* XDRIVER_MCU_CORE_NVIC_PERIPHERAL_REGISTER_REGISTERDEFINES_REGISTERDEFINES_SET_REGISTERDEFINES_SET_GENERIC_XHEADER_NVIC_REGISTERDEFINES_SET_GENERIC_ICPR_H_ */
