/**
 *
 * @file NVIC_RegisterDefines_IPR_Generic.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 15 nov. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 15 nov. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_CORE_NVIC_PERIPHERAL_REGISTER_REGISTERDEFINES_REGISTERDEFINES_IPR_XHEADER_NVIC_REGISTERDEFINES_IPR_GENERIC_H_
#define XDRIVER_MCU_CORE_NVIC_PERIPHERAL_REGISTER_REGISTERDEFINES_REGISTERDEFINES_IPR_XHEADER_NVIC_REGISTERDEFINES_IPR_GENERIC_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/xHeader/NVIC_Enum.h>

/********************************************************************************************/
/************************************* IPR ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR_NVIC_PERIPHERAL0_MASK    ((UBase_t) 0x0000000FUL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP0    ((UBase_t) 0x00000000UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP1    ((UBase_t) 0x00000001UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP2    ((UBase_t) 0x00000002UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP3    ((UBase_t) 0x00000003UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP4    ((UBase_t) 0x00000004UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP5    ((UBase_t) 0x00000005UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP6    ((UBase_t) 0x00000006UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP7    ((UBase_t) 0x00000007UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP8    ((UBase_t) 0x00000008UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP9    ((UBase_t) 0x00000009UL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP10    ((UBase_t) 0x0000000AUL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP11    ((UBase_t) 0x0000000BUL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP12    ((UBase_t) 0x0000000CUL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP13    ((UBase_t) 0x0000000DUL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP14    ((UBase_t) 0x0000000EUL)
#define NVIC_IPR_NVIC_PERIPHERAL0_IP15    ((UBase_t) 0x0000000FUL)

#define NVIC_IPR_R_NVIC_PERIPHERAL0_BIT    (4UL)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_MASK    (NVIC_IPR_NVIC_PERIPHERAL0_MASK << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP0    (NVIC_IPR_NVIC_PERIPHERAL0_IP0 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP1    (NVIC_IPR_NVIC_PERIPHERAL0_IP1 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP2    (NVIC_IPR_NVIC_PERIPHERAL0_IP2 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP3    (NVIC_IPR_NVIC_PERIPHERAL0_IP3 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP4    (NVIC_IPR_NVIC_PERIPHERAL0_IP4 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP5    (NVIC_IPR_NVIC_PERIPHERAL0_IP5 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP6    (NVIC_IPR_NVIC_PERIPHERAL0_IP6 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP7    (NVIC_IPR_NVIC_PERIPHERAL0_IP7 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP8    (NVIC_IPR_NVIC_PERIPHERAL0_IP8 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP9    (NVIC_IPR_NVIC_PERIPHERAL0_IP9 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP10    (NVIC_IPR_NVIC_PERIPHERAL0_IP10 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP11    (NVIC_IPR_NVIC_PERIPHERAL0_IP11 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP12    (NVIC_IPR_NVIC_PERIPHERAL0_IP12 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP13    (NVIC_IPR_NVIC_PERIPHERAL0_IP13 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP14    (NVIC_IPR_NVIC_PERIPHERAL0_IP14 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL0_IP15    (NVIC_IPR_NVIC_PERIPHERAL0_IP15 << NVIC_IPR_R_NVIC_PERIPHERAL0_BIT)
/*----------*/

/*----------*/
#define NVIC_IPR_NVIC_PERIPHERAL1_MASK    ((UBase_t) 0x0000000FUL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP0    ((UBase_t) 0x00000000UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP1    ((UBase_t) 0x00000001UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP2    ((UBase_t) 0x00000002UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP3    ((UBase_t) 0x00000003UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP4    ((UBase_t) 0x00000004UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP5    ((UBase_t) 0x00000005UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP6    ((UBase_t) 0x00000006UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP7    ((UBase_t) 0x00000007UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP8    ((UBase_t) 0x00000008UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP9    ((UBase_t) 0x00000009UL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP10    ((UBase_t) 0x0000000AUL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP11    ((UBase_t) 0x0000000BUL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP12    ((UBase_t) 0x0000000CUL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP13    ((UBase_t) 0x0000000DUL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP14    ((UBase_t) 0x0000000EUL)
#define NVIC_IPR_NVIC_PERIPHERAL1_IP15    ((UBase_t) 0x0000000FUL)

#define NVIC_IPR_R_NVIC_PERIPHERAL1_BIT    (4UL + 8UL)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_MASK    (NVIC_IPR_NVIC_PERIPHERAL1_MASK << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP0    (NVIC_IPR_NVIC_PERIPHERAL1_IP0 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP1    (NVIC_IPR_NVIC_PERIPHERAL1_IP1 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP2    (NVIC_IPR_NVIC_PERIPHERAL1_IP2 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP3    (NVIC_IPR_NVIC_PERIPHERAL1_IP3 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP4    (NVIC_IPR_NVIC_PERIPHERAL1_IP4 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP5    (NVIC_IPR_NVIC_PERIPHERAL1_IP5 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP6    (NVIC_IPR_NVIC_PERIPHERAL1_IP6 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP7    (NVIC_IPR_NVIC_PERIPHERAL1_IP7 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP8    (NVIC_IPR_NVIC_PERIPHERAL1_IP8 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP9    (NVIC_IPR_NVIC_PERIPHERAL1_IP9 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP10    (NVIC_IPR_NVIC_PERIPHERAL1_IP10 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP11    (NVIC_IPR_NVIC_PERIPHERAL1_IP11 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP12    (NVIC_IPR_NVIC_PERIPHERAL1_IP12 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP13    (NVIC_IPR_NVIC_PERIPHERAL1_IP13 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP14    (NVIC_IPR_NVIC_PERIPHERAL1_IP14 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL1_IP15    (NVIC_IPR_NVIC_PERIPHERAL1_IP15 << NVIC_IPR_R_NVIC_PERIPHERAL1_BIT)
/*----------*/

/*----------*/
#define NVIC_IPR_NVIC_PERIPHERAL2_MASK    ((UBase_t) 0x0000000FUL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP0    ((UBase_t) 0x00000000UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP1    ((UBase_t) 0x00000001UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP2    ((UBase_t) 0x00000002UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP3    ((UBase_t) 0x00000003UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP4    ((UBase_t) 0x00000004UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP5    ((UBase_t) 0x00000005UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP6    ((UBase_t) 0x00000006UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP7    ((UBase_t) 0x00000007UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP8    ((UBase_t) 0x00000008UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP9    ((UBase_t) 0x00000009UL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP10    ((UBase_t) 0x0000000AUL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP11    ((UBase_t) 0x0000000BUL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP12    ((UBase_t) 0x0000000CUL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP13    ((UBase_t) 0x0000000DUL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP14    ((UBase_t) 0x0000000EUL)
#define NVIC_IPR_NVIC_PERIPHERAL2_IP15    ((UBase_t) 0x0000000FUL)

#define NVIC_IPR_R_NVIC_PERIPHERAL2_BIT    (4UL + 16UL)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_MASK    (NVIC_IPR_NVIC_PERIPHERAL2_MASK << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP0    (NVIC_IPR_NVIC_PERIPHERAL2_IP0 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP1    (NVIC_IPR_NVIC_PERIPHERAL2_IP1 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP2    (NVIC_IPR_NVIC_PERIPHERAL2_IP2 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP3    (NVIC_IPR_NVIC_PERIPHERAL2_IP3 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP4    (NVIC_IPR_NVIC_PERIPHERAL2_IP4 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP5    (NVIC_IPR_NVIC_PERIPHERAL2_IP5 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP6    (NVIC_IPR_NVIC_PERIPHERAL2_IP6 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP7    (NVIC_IPR_NVIC_PERIPHERAL2_IP7 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP8    (NVIC_IPR_NVIC_PERIPHERAL2_IP8 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP9    (NVIC_IPR_NVIC_PERIPHERAL2_IP9 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP10    (NVIC_IPR_NVIC_PERIPHERAL2_IP10 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP11    (NVIC_IPR_NVIC_PERIPHERAL2_IP11 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP12    (NVIC_IPR_NVIC_PERIPHERAL2_IP12 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP13    (NVIC_IPR_NVIC_PERIPHERAL2_IP13 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP14    (NVIC_IPR_NVIC_PERIPHERAL2_IP14 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL2_IP15    (NVIC_IPR_NVIC_PERIPHERAL2_IP15 << NVIC_IPR_R_NVIC_PERIPHERAL2_BIT)
/*----------*/

/*----------*/
#define NVIC_IPR_NVIC_PERIPHERAL3_MASK    ((UBase_t) 0x0000000FUL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP0    ((UBase_t) 0x00000000UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP1    ((UBase_t) 0x00000001UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP2    ((UBase_t) 0x00000002UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP3    ((UBase_t) 0x00000003UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP4    ((UBase_t) 0x00000004UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP5    ((UBase_t) 0x00000005UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP6    ((UBase_t) 0x00000006UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP7    ((UBase_t) 0x00000007UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP8    ((UBase_t) 0x00000008UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP9    ((UBase_t) 0x00000009UL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP10    ((UBase_t) 0x0000000AUL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP11    ((UBase_t) 0x0000000BUL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP12    ((UBase_t) 0x0000000CUL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP13    ((UBase_t) 0x0000000DUL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP14    ((UBase_t) 0x0000000EUL)
#define NVIC_IPR_NVIC_PERIPHERAL3_IP15    ((UBase_t) 0x0000000FUL)

#define NVIC_IPR_R_NVIC_PERIPHERAL3_BIT    (4UL + 24UL)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_MASK    (NVIC_IPR_NVIC_PERIPHERAL3_MASK << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP0    (NVIC_IPR_NVIC_PERIPHERAL3_IP0 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP1    (NVIC_IPR_NVIC_PERIPHERAL3_IP1 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP2    (NVIC_IPR_NVIC_PERIPHERAL3_IP2 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP3    (NVIC_IPR_NVIC_PERIPHERAL3_IP3 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP4    (NVIC_IPR_NVIC_PERIPHERAL3_IP4 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP5    (NVIC_IPR_NVIC_PERIPHERAL3_IP5 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP6    (NVIC_IPR_NVIC_PERIPHERAL3_IP6 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP7    (NVIC_IPR_NVIC_PERIPHERAL3_IP7 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP8    (NVIC_IPR_NVIC_PERIPHERAL3_IP8 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP9    (NVIC_IPR_NVIC_PERIPHERAL3_IP9 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP10    (NVIC_IPR_NVIC_PERIPHERAL3_IP10 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP11    (NVIC_IPR_NVIC_PERIPHERAL3_IP11 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP12    (NVIC_IPR_NVIC_PERIPHERAL3_IP12 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP13    (NVIC_IPR_NVIC_PERIPHERAL3_IP13 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP14    (NVIC_IPR_NVIC_PERIPHERAL3_IP14 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
#define NVIC_IPR_R_NVIC_PERIPHERAL3_IP15    (NVIC_IPR_NVIC_PERIPHERAL3_IP15 << NVIC_IPR_R_NVIC_PERIPHERAL3_BIT)
/*----------*/

#endif /* XDRIVER_MCU_CORE_NVIC_PERIPHERAL_REGISTER_REGISTERDEFINES_REGISTERDEFINES_IPR_XHEADER_NVIC_REGISTERDEFINES_IPR_GENERIC_H_ */
