/**
 *
 * @file NVIC_RegisterDefines_IPR1.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date    Author    Version    Description
 * 21 jun. 2020    vyldram    1.0    initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR1_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR1_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_IPR/xHeader/NVIC_RegisterDefines_IPR_Generic.h>

/********************************************************************************************/
/************************************* IPR1 ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR1_NVIC_FLASH_MASK    NVIC_IPR_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR1_NVIC_FLASH_IP0    NVIC_IPR_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR1_NVIC_FLASH_IP1    NVIC_IPR_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR1_NVIC_FLASH_IP2    NVIC_IPR_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR1_NVIC_FLASH_IP3    NVIC_IPR_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR1_NVIC_FLASH_IP4    NVIC_IPR_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR1_NVIC_FLASH_IP5    NVIC_IPR_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR1_NVIC_FLASH_IP6    NVIC_IPR_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR1_NVIC_FLASH_IP7    NVIC_IPR_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR1_NVIC_FLASH_IP8    NVIC_IPR_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR1_NVIC_FLASH_IP9    NVIC_IPR_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR1_NVIC_FLASH_IP10    NVIC_IPR_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR1_NVIC_FLASH_IP11    NVIC_IPR_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR1_NVIC_FLASH_IP12    NVIC_IPR_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR1_NVIC_FLASH_IP13    NVIC_IPR_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR1_NVIC_FLASH_IP14    NVIC_IPR_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR1_NVIC_FLASH_IP15    NVIC_IPR_NVIC_PERIPHERAL0_IP15

#define NVIC_IPR1_R_NVIC_FLASH_BIT    NVIC_IPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IPR1_R_NVIC_FLASH_MASK    NVIC_IPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR1_R_NVIC_FLASH_IP0    NVIC_IPR_R_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR1_R_NVIC_FLASH_IP1    NVIC_IPR_R_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR1_R_NVIC_FLASH_IP2    NVIC_IPR_R_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR1_R_NVIC_FLASH_IP3    NVIC_IPR_R_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR1_R_NVIC_FLASH_IP4    NVIC_IPR_R_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR1_R_NVIC_FLASH_IP5    NVIC_IPR_R_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR1_R_NVIC_FLASH_IP6    NVIC_IPR_R_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR1_R_NVIC_FLASH_IP7    NVIC_IPR_R_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR1_R_NVIC_FLASH_IP8    NVIC_IPR_R_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR1_R_NVIC_FLASH_IP9    NVIC_IPR_R_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR1_R_NVIC_FLASH_IP10    NVIC_IPR_R_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR1_R_NVIC_FLASH_IP11    NVIC_IPR_R_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR1_R_NVIC_FLASH_IP12    NVIC_IPR_R_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR1_R_NVIC_FLASH_IP13    NVIC_IPR_R_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR1_R_NVIC_FLASH_IP14    NVIC_IPR_R_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR1_R_NVIC_FLASH_IP15    NVIC_IPR_R_NVIC_PERIPHERAL0_IP15
/*----------*/

/*----------*/
#define NVIC_IPR1_NVIC_RCC_MASK    NVIC_IPR_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR1_NVIC_RCC_IP0    NVIC_IPR_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR1_NVIC_RCC_IP1    NVIC_IPR_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR1_NVIC_RCC_IP2    NVIC_IPR_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR1_NVIC_RCC_IP3    NVIC_IPR_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR1_NVIC_RCC_IP4    NVIC_IPR_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR1_NVIC_RCC_IP5    NVIC_IPR_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR1_NVIC_RCC_IP6    NVIC_IPR_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR1_NVIC_RCC_IP7    NVIC_IPR_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR1_NVIC_RCC_IP8    NVIC_IPR_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR1_NVIC_RCC_IP9    NVIC_IPR_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR1_NVIC_RCC_IP10    NVIC_IPR_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR1_NVIC_RCC_IP11    NVIC_IPR_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR1_NVIC_RCC_IP12    NVIC_IPR_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR1_NVIC_RCC_IP13    NVIC_IPR_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR1_NVIC_RCC_IP14    NVIC_IPR_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR1_NVIC_RCC_IP15    NVIC_IPR_NVIC_PERIPHERAL1_IP15

#define NVIC_IPR1_R_NVIC_RCC_BIT    NVIC_IPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IPR1_R_NVIC_RCC_MASK    NVIC_IPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR1_R_NVIC_RCC_IP0    NVIC_IPR_R_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR1_R_NVIC_RCC_IP1    NVIC_IPR_R_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR1_R_NVIC_RCC_IP2    NVIC_IPR_R_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR1_R_NVIC_RCC_IP3    NVIC_IPR_R_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR1_R_NVIC_RCC_IP4    NVIC_IPR_R_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR1_R_NVIC_RCC_IP5    NVIC_IPR_R_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR1_R_NVIC_RCC_IP6    NVIC_IPR_R_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR1_R_NVIC_RCC_IP7    NVIC_IPR_R_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR1_R_NVIC_RCC_IP8    NVIC_IPR_R_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR1_R_NVIC_RCC_IP9    NVIC_IPR_R_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR1_R_NVIC_RCC_IP10    NVIC_IPR_R_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR1_R_NVIC_RCC_IP11    NVIC_IPR_R_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR1_R_NVIC_RCC_IP12    NVIC_IPR_R_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR1_R_NVIC_RCC_IP13    NVIC_IPR_R_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR1_R_NVIC_RCC_IP14    NVIC_IPR_R_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR1_R_NVIC_RCC_IP15    NVIC_IPR_R_NVIC_PERIPHERAL1_IP15
/*----------*/

/*----------*/
#define NVIC_IPR1_NVIC_EXTI0_MASK    NVIC_IPR_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR1_NVIC_EXTI0_IP0    NVIC_IPR_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR1_NVIC_EXTI0_IP1    NVIC_IPR_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR1_NVIC_EXTI0_IP2    NVIC_IPR_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR1_NVIC_EXTI0_IP3    NVIC_IPR_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR1_NVIC_EXTI0_IP4    NVIC_IPR_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR1_NVIC_EXTI0_IP5    NVIC_IPR_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR1_NVIC_EXTI0_IP6    NVIC_IPR_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR1_NVIC_EXTI0_IP7    NVIC_IPR_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR1_NVIC_EXTI0_IP8    NVIC_IPR_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR1_NVIC_EXTI0_IP9    NVIC_IPR_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR1_NVIC_EXTI0_IP10    NVIC_IPR_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR1_NVIC_EXTI0_IP11    NVIC_IPR_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR1_NVIC_EXTI0_IP12    NVIC_IPR_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR1_NVIC_EXTI0_IP13    NVIC_IPR_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR1_NVIC_EXTI0_IP14    NVIC_IPR_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR1_NVIC_EXTI0_IP15    NVIC_IPR_NVIC_PERIPHERAL2_IP15

#define NVIC_IPR1_R_NVIC_EXTI0_BIT    NVIC_IPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IPR1_R_NVIC_EXTI0_MASK    NVIC_IPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR1_R_NVIC_EXTI0_IP0    NVIC_IPR_R_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR1_R_NVIC_EXTI0_IP1    NVIC_IPR_R_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR1_R_NVIC_EXTI0_IP2    NVIC_IPR_R_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR1_R_NVIC_EXTI0_IP3    NVIC_IPR_R_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR1_R_NVIC_EXTI0_IP4    NVIC_IPR_R_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR1_R_NVIC_EXTI0_IP5    NVIC_IPR_R_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR1_R_NVIC_EXTI0_IP6    NVIC_IPR_R_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR1_R_NVIC_EXTI0_IP7    NVIC_IPR_R_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR1_R_NVIC_EXTI0_IP8    NVIC_IPR_R_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR1_R_NVIC_EXTI0_IP9    NVIC_IPR_R_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR1_R_NVIC_EXTI0_IP10    NVIC_IPR_R_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR1_R_NVIC_EXTI0_IP11    NVIC_IPR_R_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR1_R_NVIC_EXTI0_IP12    NVIC_IPR_R_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR1_R_NVIC_EXTI0_IP13    NVIC_IPR_R_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR1_R_NVIC_EXTI0_IP14    NVIC_IPR_R_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR1_R_NVIC_EXTI0_IP15    NVIC_IPR_R_NVIC_PERIPHERAL2_IP15
/*----------*/

/*----------*/
#define NVIC_IPR1_NVIC_EXTI1_MASK    NVIC_IPR_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR1_NVIC_EXTI1_IP0    NVIC_IPR_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR1_NVIC_EXTI1_IP1    NVIC_IPR_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR1_NVIC_EXTI1_IP2    NVIC_IPR_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR1_NVIC_EXTI1_IP3    NVIC_IPR_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR1_NVIC_EXTI1_IP4    NVIC_IPR_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR1_NVIC_EXTI1_IP5    NVIC_IPR_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR1_NVIC_EXTI1_IP6    NVIC_IPR_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR1_NVIC_EXTI1_IP7    NVIC_IPR_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR1_NVIC_EXTI1_IP8    NVIC_IPR_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR1_NVIC_EXTI1_IP9    NVIC_IPR_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR1_NVIC_EXTI1_IP10    NVIC_IPR_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR1_NVIC_EXTI1_IP11    NVIC_IPR_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR1_NVIC_EXTI1_IP12    NVIC_IPR_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR1_NVIC_EXTI1_IP13    NVIC_IPR_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR1_NVIC_EXTI1_IP14    NVIC_IPR_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR1_NVIC_EXTI1_IP15    NVIC_IPR_NVIC_PERIPHERAL3_IP15

#define NVIC_IPR1_R_NVIC_EXTI1_BIT    NVIC_IPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IPR1_R_NVIC_EXTI1_MASK    NVIC_IPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR1_R_NVIC_EXTI1_IP0    NVIC_IPR_R_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR1_R_NVIC_EXTI1_IP1    NVIC_IPR_R_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR1_R_NVIC_EXTI1_IP2    NVIC_IPR_R_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR1_R_NVIC_EXTI1_IP3    NVIC_IPR_R_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR1_R_NVIC_EXTI1_IP4    NVIC_IPR_R_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR1_R_NVIC_EXTI1_IP5    NVIC_IPR_R_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR1_R_NVIC_EXTI1_IP6    NVIC_IPR_R_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR1_R_NVIC_EXTI1_IP7    NVIC_IPR_R_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR1_R_NVIC_EXTI1_IP8    NVIC_IPR_R_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR1_R_NVIC_EXTI1_IP9    NVIC_IPR_R_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR1_R_NVIC_EXTI1_IP10    NVIC_IPR_R_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR1_R_NVIC_EXTI1_IP11    NVIC_IPR_R_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR1_R_NVIC_EXTI1_IP12    NVIC_IPR_R_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR1_R_NVIC_EXTI1_IP13    NVIC_IPR_R_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR1_R_NVIC_EXTI1_IP14    NVIC_IPR_R_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR1_R_NVIC_EXTI1_IP15    NVIC_IPR_R_NVIC_PERIPHERAL3_IP15
/*----------*/


#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR1_H_ */
