/**
 *
 * @file NVIC_RegisterDefines_IPR24.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date    Author    Version    Description
 * 22 jun. 2020    vyldram    1.0    initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR24_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR24_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_IPR/xHeader/NVIC_RegisterDefines_IPR_Generic.h>

/********************************************************************************************/
/************************************* IPR24 ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR24_NVIC_I2C4_ER_MASK    NVIC_IPR_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR24_NVIC_I2C4_ER_IP0    NVIC_IPR_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR24_NVIC_I2C4_ER_IP1    NVIC_IPR_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR24_NVIC_I2C4_ER_IP2    NVIC_IPR_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR24_NVIC_I2C4_ER_IP3    NVIC_IPR_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR24_NVIC_I2C4_ER_IP4    NVIC_IPR_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR24_NVIC_I2C4_ER_IP5    NVIC_IPR_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR24_NVIC_I2C4_ER_IP6    NVIC_IPR_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR24_NVIC_I2C4_ER_IP7    NVIC_IPR_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR24_NVIC_I2C4_ER_IP8    NVIC_IPR_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR24_NVIC_I2C4_ER_IP9    NVIC_IPR_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR24_NVIC_I2C4_ER_IP10    NVIC_IPR_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR24_NVIC_I2C4_ER_IP11    NVIC_IPR_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR24_NVIC_I2C4_ER_IP12    NVIC_IPR_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR24_NVIC_I2C4_ER_IP13    NVIC_IPR_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR24_NVIC_I2C4_ER_IP14    NVIC_IPR_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR24_NVIC_I2C4_ER_IP15    NVIC_IPR_NVIC_PERIPHERAL0_IP15

#define NVIC_IPR24_R_NVIC_I2C4_ER_BIT    NVIC_IPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IPR24_R_NVIC_I2C4_ER_MASK    NVIC_IPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP0    NVIC_IPR_R_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP1    NVIC_IPR_R_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP2    NVIC_IPR_R_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP3    NVIC_IPR_R_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP4    NVIC_IPR_R_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP5    NVIC_IPR_R_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP6    NVIC_IPR_R_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP7    NVIC_IPR_R_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP8    NVIC_IPR_R_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP9    NVIC_IPR_R_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP10    NVIC_IPR_R_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP11    NVIC_IPR_R_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP12    NVIC_IPR_R_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP13    NVIC_IPR_R_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP14    NVIC_IPR_R_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR24_R_NVIC_I2C4_ER_IP15    NVIC_IPR_R_NVIC_PERIPHERAL0_IP15
/*----------*/

/*----------*/
#define NVIC_IPR24_NVIC_SPDIF_RX_MASK    NVIC_IPR_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR24_NVIC_SPDIF_RX_IP0    NVIC_IPR_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR24_NVIC_SPDIF_RX_IP1    NVIC_IPR_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR24_NVIC_SPDIF_RX_IP2    NVIC_IPR_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR24_NVIC_SPDIF_RX_IP3    NVIC_IPR_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR24_NVIC_SPDIF_RX_IP4    NVIC_IPR_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR24_NVIC_SPDIF_RX_IP5    NVIC_IPR_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR24_NVIC_SPDIF_RX_IP6    NVIC_IPR_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR24_NVIC_SPDIF_RX_IP7    NVIC_IPR_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR24_NVIC_SPDIF_RX_IP8    NVIC_IPR_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR24_NVIC_SPDIF_RX_IP9    NVIC_IPR_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR24_NVIC_SPDIF_RX_IP10    NVIC_IPR_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR24_NVIC_SPDIF_RX_IP11    NVIC_IPR_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR24_NVIC_SPDIF_RX_IP12    NVIC_IPR_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR24_NVIC_SPDIF_RX_IP13    NVIC_IPR_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR24_NVIC_SPDIF_RX_IP14    NVIC_IPR_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR24_NVIC_SPDIF_RX_IP15    NVIC_IPR_NVIC_PERIPHERAL1_IP15

#define NVIC_IPR24_R_NVIC_SPDIF_RX_BIT    NVIC_IPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IPR24_R_NVIC_SPDIF_RX_MASK    NVIC_IPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP0    NVIC_IPR_R_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP1    NVIC_IPR_R_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP2    NVIC_IPR_R_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP3    NVIC_IPR_R_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP4    NVIC_IPR_R_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP5    NVIC_IPR_R_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP6    NVIC_IPR_R_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP7    NVIC_IPR_R_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP8    NVIC_IPR_R_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP9    NVIC_IPR_R_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP10    NVIC_IPR_R_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP11    NVIC_IPR_R_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP12    NVIC_IPR_R_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP13    NVIC_IPR_R_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP14    NVIC_IPR_R_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR24_R_NVIC_SPDIF_RX_IP15    NVIC_IPR_R_NVIC_PERIPHERAL1_IP15
/*----------*/

/*----------*/
#define NVIC_IPR24_NVIC_DSI_HOST_MASK    NVIC_IPR_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR24_NVIC_DSI_HOST_IP0    NVIC_IPR_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR24_NVIC_DSI_HOST_IP1    NVIC_IPR_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR24_NVIC_DSI_HOST_IP2    NVIC_IPR_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR24_NVIC_DSI_HOST_IP3    NVIC_IPR_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR24_NVIC_DSI_HOST_IP4    NVIC_IPR_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR24_NVIC_DSI_HOST_IP5    NVIC_IPR_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR24_NVIC_DSI_HOST_IP6    NVIC_IPR_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR24_NVIC_DSI_HOST_IP7    NVIC_IPR_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR24_NVIC_DSI_HOST_IP8    NVIC_IPR_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR24_NVIC_DSI_HOST_IP9    NVIC_IPR_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR24_NVIC_DSI_HOST_IP10    NVIC_IPR_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR24_NVIC_DSI_HOST_IP11    NVIC_IPR_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR24_NVIC_DSI_HOST_IP12    NVIC_IPR_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR24_NVIC_DSI_HOST_IP13    NVIC_IPR_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR24_NVIC_DSI_HOST_IP14    NVIC_IPR_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR24_NVIC_DSI_HOST_IP15    NVIC_IPR_NVIC_PERIPHERAL2_IP15

#define NVIC_IPR24_R_NVIC_DSI_HOST_BIT    NVIC_IPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IPR24_R_NVIC_DSI_HOST_MASK    NVIC_IPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP0    NVIC_IPR_R_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP1    NVIC_IPR_R_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP2    NVIC_IPR_R_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP3    NVIC_IPR_R_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP4    NVIC_IPR_R_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP5    NVIC_IPR_R_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP6    NVIC_IPR_R_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP7    NVIC_IPR_R_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP8    NVIC_IPR_R_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP9    NVIC_IPR_R_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP10    NVIC_IPR_R_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP11    NVIC_IPR_R_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP12    NVIC_IPR_R_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP13    NVIC_IPR_R_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP14    NVIC_IPR_R_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR24_R_NVIC_DSI_HOST_IP15    NVIC_IPR_R_NVIC_PERIPHERAL2_IP15
/*----------*/

/*----------*/
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_MASK    NVIC_IPR_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP0    NVIC_IPR_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP1    NVIC_IPR_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP2    NVIC_IPR_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP3    NVIC_IPR_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP4    NVIC_IPR_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP5    NVIC_IPR_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP6    NVIC_IPR_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP7    NVIC_IPR_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP8    NVIC_IPR_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP9    NVIC_IPR_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP10    NVIC_IPR_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP11    NVIC_IPR_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP12    NVIC_IPR_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP13    NVIC_IPR_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP14    NVIC_IPR_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR24_NVIC_DFSDM1_FLT0_IP15    NVIC_IPR_NVIC_PERIPHERAL3_IP15

#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_BIT    NVIC_IPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_MASK    NVIC_IPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP0    NVIC_IPR_R_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP1    NVIC_IPR_R_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP2    NVIC_IPR_R_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP3    NVIC_IPR_R_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP4    NVIC_IPR_R_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP5    NVIC_IPR_R_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP6    NVIC_IPR_R_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP7    NVIC_IPR_R_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP8    NVIC_IPR_R_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP9    NVIC_IPR_R_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP10    NVIC_IPR_R_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP11    NVIC_IPR_R_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP12    NVIC_IPR_R_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP13    NVIC_IPR_R_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP14    NVIC_IPR_R_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR24_R_NVIC_DFSDM1_FLT0_IP15    NVIC_IPR_R_NVIC_PERIPHERAL3_IP15
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR24_H_ */
