/**
 *
 * @file NVIC_RegisterDefines_IPR27.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date    Author    Version    Description
 * 22 jun. 2020    vyldram    1.0    initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR27_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR27_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_IPR/xHeader/NVIC_RegisterDefines_IPR_Generic.h>

/********************************************************************************************/
/************************************* IPR27 ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR27_NVIC_JPEG_MASK    NVIC_IPR_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR27_NVIC_JPEG_IP0    NVIC_IPR_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR27_NVIC_JPEG_IP1    NVIC_IPR_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR27_NVIC_JPEG_IP2    NVIC_IPR_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR27_NVIC_JPEG_IP3    NVIC_IPR_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR27_NVIC_JPEG_IP4    NVIC_IPR_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR27_NVIC_JPEG_IP5    NVIC_IPR_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR27_NVIC_JPEG_IP6    NVIC_IPR_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR27_NVIC_JPEG_IP7    NVIC_IPR_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR27_NVIC_JPEG_IP8    NVIC_IPR_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR27_NVIC_JPEG_IP9    NVIC_IPR_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR27_NVIC_JPEG_IP10    NVIC_IPR_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR27_NVIC_JPEG_IP11    NVIC_IPR_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR27_NVIC_JPEG_IP12    NVIC_IPR_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR27_NVIC_JPEG_IP13    NVIC_IPR_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR27_NVIC_JPEG_IP14    NVIC_IPR_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR27_NVIC_JPEG_IP15    NVIC_IPR_NVIC_PERIPHERAL0_IP15

#define NVIC_IPR27_R_NVIC_JPEG_BIT    NVIC_IPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IPR27_R_NVIC_JPEG_MASK    NVIC_IPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR27_R_NVIC_JPEG_IP0    NVIC_IPR_R_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR27_R_NVIC_JPEG_IP1    NVIC_IPR_R_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR27_R_NVIC_JPEG_IP2    NVIC_IPR_R_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR27_R_NVIC_JPEG_IP3    NVIC_IPR_R_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR27_R_NVIC_JPEG_IP4    NVIC_IPR_R_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR27_R_NVIC_JPEG_IP5    NVIC_IPR_R_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR27_R_NVIC_JPEG_IP6    NVIC_IPR_R_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR27_R_NVIC_JPEG_IP7    NVIC_IPR_R_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR27_R_NVIC_JPEG_IP8    NVIC_IPR_R_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR27_R_NVIC_JPEG_IP9    NVIC_IPR_R_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR27_R_NVIC_JPEG_IP10    NVIC_IPR_R_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR27_R_NVIC_JPEG_IP11    NVIC_IPR_R_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR27_R_NVIC_JPEG_IP12    NVIC_IPR_R_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR27_R_NVIC_JPEG_IP13    NVIC_IPR_R_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR27_R_NVIC_JPEG_IP14    NVIC_IPR_R_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR27_R_NVIC_JPEG_IP15    NVIC_IPR_R_NVIC_PERIPHERAL0_IP15
/*----------*/

/*----------*/
#define NVIC_IPR27_NVIC_MDIO_SLAVE_MASK    NVIC_IPR_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP0    NVIC_IPR_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP1    NVIC_IPR_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP2    NVIC_IPR_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP3    NVIC_IPR_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP4    NVIC_IPR_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP5    NVIC_IPR_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP6    NVIC_IPR_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP7    NVIC_IPR_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP8    NVIC_IPR_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP9    NVIC_IPR_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP10    NVIC_IPR_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP11    NVIC_IPR_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP12    NVIC_IPR_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP13    NVIC_IPR_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP14    NVIC_IPR_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR27_NVIC_MDIO_SLAVE_IP15    NVIC_IPR_NVIC_PERIPHERAL1_IP15

#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_BIT    NVIC_IPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_MASK    NVIC_IPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP0    NVIC_IPR_R_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP1    NVIC_IPR_R_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP2    NVIC_IPR_R_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP3    NVIC_IPR_R_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP4    NVIC_IPR_R_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP5    NVIC_IPR_R_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP6    NVIC_IPR_R_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP7    NVIC_IPR_R_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP8    NVIC_IPR_R_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP9    NVIC_IPR_R_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP10    NVIC_IPR_R_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP11    NVIC_IPR_R_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP12    NVIC_IPR_R_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP13    NVIC_IPR_R_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP14    NVIC_IPR_R_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR27_R_NVIC_MDIO_SLAVE_IP15    NVIC_IPR_R_NVIC_PERIPHERAL1_IP15
/*----------*/

/*----------*/
#define NVIC_IPR27_NVIC_RES126_MASK    NVIC_IPR_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR27_NVIC_RES126_IP0    NVIC_IPR_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR27_NVIC_RES126_IP1    NVIC_IPR_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR27_NVIC_RES126_IP2    NVIC_IPR_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR27_NVIC_RES126_IP3    NVIC_IPR_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR27_NVIC_RES126_IP4    NVIC_IPR_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR27_NVIC_RES126_IP5    NVIC_IPR_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR27_NVIC_RES126_IP6    NVIC_IPR_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR27_NVIC_RES126_IP7    NVIC_IPR_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR27_NVIC_RES126_IP8    NVIC_IPR_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR27_NVIC_RES126_IP9    NVIC_IPR_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR27_NVIC_RES126_IP10    NVIC_IPR_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR27_NVIC_RES126_IP11    NVIC_IPR_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR27_NVIC_RES126_IP12    NVIC_IPR_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR27_NVIC_RES126_IP13    NVIC_IPR_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR27_NVIC_RES126_IP14    NVIC_IPR_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR27_NVIC_RES126_IP15    NVIC_IPR_NVIC_PERIPHERAL2_IP15

#define NVIC_IPR27_R_NVIC_RES126_BIT    NVIC_IPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IPR27_R_NVIC_RES126_MASK    NVIC_IPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR27_R_NVIC_RES126_IP0    NVIC_IPR_R_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR27_R_NVIC_RES126_IP1    NVIC_IPR_R_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR27_R_NVIC_RES126_IP2    NVIC_IPR_R_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR27_R_NVIC_RES126_IP3    NVIC_IPR_R_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR27_R_NVIC_RES126_IP4    NVIC_IPR_R_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR27_R_NVIC_RES126_IP5    NVIC_IPR_R_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR27_R_NVIC_RES126_IP6    NVIC_IPR_R_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR27_R_NVIC_RES126_IP7    NVIC_IPR_R_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR27_R_NVIC_RES126_IP8    NVIC_IPR_R_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR27_R_NVIC_RES126_IP9    NVIC_IPR_R_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR27_R_NVIC_RES126_IP10    NVIC_IPR_R_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR27_R_NVIC_RES126_IP11    NVIC_IPR_R_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR27_R_NVIC_RES126_IP12    NVIC_IPR_R_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR27_R_NVIC_RES126_IP13    NVIC_IPR_R_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR27_R_NVIC_RES126_IP14    NVIC_IPR_R_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR27_R_NVIC_RES126_IP15    NVIC_IPR_R_NVIC_PERIPHERAL2_IP15
/*----------*/

/*----------*/
#define NVIC_IPR27_NVIC_RES127_MASK    NVIC_IPR_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR27_NVIC_RES127_IP0    NVIC_IPR_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR27_NVIC_RES127_IP1    NVIC_IPR_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR27_NVIC_RES127_IP2    NVIC_IPR_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR27_NVIC_RES127_IP3    NVIC_IPR_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR27_NVIC_RES127_IP4    NVIC_IPR_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR27_NVIC_RES127_IP5    NVIC_IPR_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR27_NVIC_RES127_IP6    NVIC_IPR_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR27_NVIC_RES127_IP7    NVIC_IPR_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR27_NVIC_RES127_IP8    NVIC_IPR_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR27_NVIC_RES127_IP9    NVIC_IPR_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR27_NVIC_RES127_IP10    NVIC_IPR_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR27_NVIC_RES127_IP11    NVIC_IPR_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR27_NVIC_RES127_IP12    NVIC_IPR_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR27_NVIC_RES127_IP13    NVIC_IPR_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR27_NVIC_RES127_IP14    NVIC_IPR_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR27_NVIC_RES127_IP15    NVIC_IPR_NVIC_PERIPHERAL3_IP15

#define NVIC_IPR27_R_NVIC_RES127_BIT    NVIC_IPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IPR27_R_NVIC_RES127_MASK    NVIC_IPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR27_R_NVIC_RES127_IP0    NVIC_IPR_R_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR27_R_NVIC_RES127_IP1    NVIC_IPR_R_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR27_R_NVIC_RES127_IP2    NVIC_IPR_R_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR27_R_NVIC_RES127_IP3    NVIC_IPR_R_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR27_R_NVIC_RES127_IP4    NVIC_IPR_R_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR27_R_NVIC_RES127_IP5    NVIC_IPR_R_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR27_R_NVIC_RES127_IP6    NVIC_IPR_R_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR27_R_NVIC_RES127_IP7    NVIC_IPR_R_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR27_R_NVIC_RES127_IP8    NVIC_IPR_R_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR27_R_NVIC_RES127_IP9    NVIC_IPR_R_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR27_R_NVIC_RES127_IP10    NVIC_IPR_R_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR27_R_NVIC_RES127_IP11    NVIC_IPR_R_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR27_R_NVIC_RES127_IP12    NVIC_IPR_R_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR27_R_NVIC_RES127_IP13    NVIC_IPR_R_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR27_R_NVIC_RES127_IP14    NVIC_IPR_R_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR27_R_NVIC_RES127_IP15    NVIC_IPR_R_NVIC_PERIPHERAL3_IP15
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR27_H_ */
