/**
 *
 * @file NVIC_RegisterDefines_IPR10.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date    Author    Version    Description
 * 22 jun. 2020    vyldram    1.0    initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR10_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR10_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_IPR/xHeader/NVIC_RegisterDefines_IPR_Generic.h>

/********************************************************************************************/
/************************************* IPR10 ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR10_NVIC_EXTI15_10_MASK    NVIC_IPR_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR10_NVIC_EXTI15_10_IP0    NVIC_IPR_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR10_NVIC_EXTI15_10_IP1    NVIC_IPR_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR10_NVIC_EXTI15_10_IP2    NVIC_IPR_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR10_NVIC_EXTI15_10_IP3    NVIC_IPR_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR10_NVIC_EXTI15_10_IP4    NVIC_IPR_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR10_NVIC_EXTI15_10_IP5    NVIC_IPR_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR10_NVIC_EXTI15_10_IP6    NVIC_IPR_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR10_NVIC_EXTI15_10_IP7    NVIC_IPR_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR10_NVIC_EXTI15_10_IP8    NVIC_IPR_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR10_NVIC_EXTI15_10_IP9    NVIC_IPR_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR10_NVIC_EXTI15_10_IP10    NVIC_IPR_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR10_NVIC_EXTI15_10_IP11    NVIC_IPR_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR10_NVIC_EXTI15_10_IP12    NVIC_IPR_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR10_NVIC_EXTI15_10_IP13    NVIC_IPR_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR10_NVIC_EXTI15_10_IP14    NVIC_IPR_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR10_NVIC_EXTI15_10_IP15    NVIC_IPR_NVIC_PERIPHERAL0_IP15

#define NVIC_IPR10_R_NVIC_EXTI15_10_BIT    NVIC_IPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IPR10_R_NVIC_EXTI15_10_MASK    NVIC_IPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP0    NVIC_IPR_R_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP1    NVIC_IPR_R_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP2    NVIC_IPR_R_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP3    NVIC_IPR_R_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP4    NVIC_IPR_R_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP5    NVIC_IPR_R_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP6    NVIC_IPR_R_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP7    NVIC_IPR_R_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP8    NVIC_IPR_R_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP9    NVIC_IPR_R_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP10    NVIC_IPR_R_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP11    NVIC_IPR_R_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP12    NVIC_IPR_R_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP13    NVIC_IPR_R_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP14    NVIC_IPR_R_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR10_R_NVIC_EXTI15_10_IP15    NVIC_IPR_R_NVIC_PERIPHERAL0_IP15
/*----------*/

/*----------*/
#define NVIC_IPR10_NVIC_RTC_ALARM_MASK    NVIC_IPR_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR10_NVIC_RTC_ALARM_IP0    NVIC_IPR_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR10_NVIC_RTC_ALARM_IP1    NVIC_IPR_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR10_NVIC_RTC_ALARM_IP2    NVIC_IPR_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR10_NVIC_RTC_ALARM_IP3    NVIC_IPR_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR10_NVIC_RTC_ALARM_IP4    NVIC_IPR_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR10_NVIC_RTC_ALARM_IP5    NVIC_IPR_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR10_NVIC_RTC_ALARM_IP6    NVIC_IPR_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR10_NVIC_RTC_ALARM_IP7    NVIC_IPR_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR10_NVIC_RTC_ALARM_IP8    NVIC_IPR_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR10_NVIC_RTC_ALARM_IP9    NVIC_IPR_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR10_NVIC_RTC_ALARM_IP10    NVIC_IPR_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR10_NVIC_RTC_ALARM_IP11    NVIC_IPR_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR10_NVIC_RTC_ALARM_IP12    NVIC_IPR_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR10_NVIC_RTC_ALARM_IP13    NVIC_IPR_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR10_NVIC_RTC_ALARM_IP14    NVIC_IPR_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR10_NVIC_RTC_ALARM_IP15    NVIC_IPR_NVIC_PERIPHERAL1_IP15

#define NVIC_IPR10_R_NVIC_RTC_ALARM_BIT    NVIC_IPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IPR10_R_NVIC_RTC_ALARM_MASK    NVIC_IPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP0    NVIC_IPR_R_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP1    NVIC_IPR_R_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP2    NVIC_IPR_R_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP3    NVIC_IPR_R_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP4    NVIC_IPR_R_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP5    NVIC_IPR_R_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP6    NVIC_IPR_R_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP7    NVIC_IPR_R_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP8    NVIC_IPR_R_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP9    NVIC_IPR_R_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP10    NVIC_IPR_R_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP11    NVIC_IPR_R_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP12    NVIC_IPR_R_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP13    NVIC_IPR_R_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP14    NVIC_IPR_R_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR10_R_NVIC_RTC_ALARM_IP15    NVIC_IPR_R_NVIC_PERIPHERAL1_IP15
/*----------*/

/*----------*/
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_MASK    NVIC_IPR_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP0    NVIC_IPR_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP1    NVIC_IPR_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP2    NVIC_IPR_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP3    NVIC_IPR_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP4    NVIC_IPR_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP5    NVIC_IPR_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP6    NVIC_IPR_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP7    NVIC_IPR_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP8    NVIC_IPR_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP9    NVIC_IPR_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP10    NVIC_IPR_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP11    NVIC_IPR_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP12    NVIC_IPR_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP13    NVIC_IPR_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP14    NVIC_IPR_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR10_NVIC_OTG_FS_WKUP_IP15    NVIC_IPR_NVIC_PERIPHERAL2_IP15

#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_BIT    NVIC_IPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_MASK    NVIC_IPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP0    NVIC_IPR_R_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP1    NVIC_IPR_R_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP2    NVIC_IPR_R_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP3    NVIC_IPR_R_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP4    NVIC_IPR_R_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP5    NVIC_IPR_R_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP6    NVIC_IPR_R_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP7    NVIC_IPR_R_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP8    NVIC_IPR_R_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP9    NVIC_IPR_R_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP10    NVIC_IPR_R_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP11    NVIC_IPR_R_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP12    NVIC_IPR_R_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP13    NVIC_IPR_R_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP14    NVIC_IPR_R_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR10_R_NVIC_OTG_FS_WKUP_IP15    NVIC_IPR_R_NVIC_PERIPHERAL2_IP15
/*----------*/

/*----------*/
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_MASK    NVIC_IPR_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP0    NVIC_IPR_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP1    NVIC_IPR_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP2    NVIC_IPR_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP3    NVIC_IPR_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP4    NVIC_IPR_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP5    NVIC_IPR_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP6    NVIC_IPR_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP7    NVIC_IPR_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP8    NVIC_IPR_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP9    NVIC_IPR_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP10    NVIC_IPR_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP11    NVIC_IPR_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP12    NVIC_IPR_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP13    NVIC_IPR_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP14    NVIC_IPR_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR10_NVIC_TIM8_BRK_TIM12_IP15    NVIC_IPR_NVIC_PERIPHERAL3_IP15

#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_BIT    NVIC_IPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_MASK    NVIC_IPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP0    NVIC_IPR_R_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP1    NVIC_IPR_R_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP2    NVIC_IPR_R_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP3    NVIC_IPR_R_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP4    NVIC_IPR_R_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP5    NVIC_IPR_R_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP6    NVIC_IPR_R_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP7    NVIC_IPR_R_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP8    NVIC_IPR_R_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP9    NVIC_IPR_R_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP10    NVIC_IPR_R_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP11    NVIC_IPR_R_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP12    NVIC_IPR_R_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP13    NVIC_IPR_R_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP14    NVIC_IPR_R_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR10_R_NVIC_TIM8_BRK_TIM12_IP15    NVIC_IPR_R_NVIC_PERIPHERAL3_IP15
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR10_H_ */
