/**
 *
 * @file NVIC_RegisterDefines_IPR23.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date    Author    Version    Description
 * 22 jun. 2020    vyldram    1.0    initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR23_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR23_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_IPR/xHeader/NVIC_RegisterDefines_IPR_Generic.h>

/********************************************************************************************/
/************************************* IPR23 ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR23_NVIC_QSPI_MASK    NVIC_IPR_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR23_NVIC_QSPI_IP0    NVIC_IPR_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR23_NVIC_QSPI_IP1    NVIC_IPR_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR23_NVIC_QSPI_IP2    NVIC_IPR_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR23_NVIC_QSPI_IP3    NVIC_IPR_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR23_NVIC_QSPI_IP4    NVIC_IPR_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR23_NVIC_QSPI_IP5    NVIC_IPR_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR23_NVIC_QSPI_IP6    NVIC_IPR_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR23_NVIC_QSPI_IP7    NVIC_IPR_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR23_NVIC_QSPI_IP8    NVIC_IPR_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR23_NVIC_QSPI_IP9    NVIC_IPR_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR23_NVIC_QSPI_IP10    NVIC_IPR_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR23_NVIC_QSPI_IP11    NVIC_IPR_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR23_NVIC_QSPI_IP12    NVIC_IPR_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR23_NVIC_QSPI_IP13    NVIC_IPR_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR23_NVIC_QSPI_IP14    NVIC_IPR_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR23_NVIC_QSPI_IP15    NVIC_IPR_NVIC_PERIPHERAL0_IP15

#define NVIC_IPR23_R_NVIC_QSPI_BIT    NVIC_IPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IPR23_R_NVIC_QSPI_MASK    NVIC_IPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR23_R_NVIC_QSPI_IP0    NVIC_IPR_R_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR23_R_NVIC_QSPI_IP1    NVIC_IPR_R_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR23_R_NVIC_QSPI_IP2    NVIC_IPR_R_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR23_R_NVIC_QSPI_IP3    NVIC_IPR_R_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR23_R_NVIC_QSPI_IP4    NVIC_IPR_R_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR23_R_NVIC_QSPI_IP5    NVIC_IPR_R_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR23_R_NVIC_QSPI_IP6    NVIC_IPR_R_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR23_R_NVIC_QSPI_IP7    NVIC_IPR_R_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR23_R_NVIC_QSPI_IP8    NVIC_IPR_R_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR23_R_NVIC_QSPI_IP9    NVIC_IPR_R_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR23_R_NVIC_QSPI_IP10    NVIC_IPR_R_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR23_R_NVIC_QSPI_IP11    NVIC_IPR_R_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR23_R_NVIC_QSPI_IP12    NVIC_IPR_R_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR23_R_NVIC_QSPI_IP13    NVIC_IPR_R_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR23_R_NVIC_QSPI_IP14    NVIC_IPR_R_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR23_R_NVIC_QSPI_IP15    NVIC_IPR_R_NVIC_PERIPHERAL0_IP15
/*----------*/

/*----------*/
#define NVIC_IPR23_NVIC_LPTIM1_MASK    NVIC_IPR_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR23_NVIC_LPTIM1_IP0    NVIC_IPR_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR23_NVIC_LPTIM1_IP1    NVIC_IPR_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR23_NVIC_LPTIM1_IP2    NVIC_IPR_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR23_NVIC_LPTIM1_IP3    NVIC_IPR_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR23_NVIC_LPTIM1_IP4    NVIC_IPR_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR23_NVIC_LPTIM1_IP5    NVIC_IPR_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR23_NVIC_LPTIM1_IP6    NVIC_IPR_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR23_NVIC_LPTIM1_IP7    NVIC_IPR_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR23_NVIC_LPTIM1_IP8    NVIC_IPR_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR23_NVIC_LPTIM1_IP9    NVIC_IPR_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR23_NVIC_LPTIM1_IP10    NVIC_IPR_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR23_NVIC_LPTIM1_IP11    NVIC_IPR_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR23_NVIC_LPTIM1_IP12    NVIC_IPR_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR23_NVIC_LPTIM1_IP13    NVIC_IPR_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR23_NVIC_LPTIM1_IP14    NVIC_IPR_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR23_NVIC_LPTIM1_IP15    NVIC_IPR_NVIC_PERIPHERAL1_IP15

#define NVIC_IPR23_R_NVIC_LPTIM1_BIT    NVIC_IPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IPR23_R_NVIC_LPTIM1_MASK    NVIC_IPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR23_R_NVIC_LPTIM1_IP0    NVIC_IPR_R_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR23_R_NVIC_LPTIM1_IP1    NVIC_IPR_R_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR23_R_NVIC_LPTIM1_IP2    NVIC_IPR_R_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR23_R_NVIC_LPTIM1_IP3    NVIC_IPR_R_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR23_R_NVIC_LPTIM1_IP4    NVIC_IPR_R_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR23_R_NVIC_LPTIM1_IP5    NVIC_IPR_R_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR23_R_NVIC_LPTIM1_IP6    NVIC_IPR_R_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR23_R_NVIC_LPTIM1_IP7    NVIC_IPR_R_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR23_R_NVIC_LPTIM1_IP8    NVIC_IPR_R_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR23_R_NVIC_LPTIM1_IP9    NVIC_IPR_R_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR23_R_NVIC_LPTIM1_IP10    NVIC_IPR_R_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR23_R_NVIC_LPTIM1_IP11    NVIC_IPR_R_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR23_R_NVIC_LPTIM1_IP12    NVIC_IPR_R_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR23_R_NVIC_LPTIM1_IP13    NVIC_IPR_R_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR23_R_NVIC_LPTIM1_IP14    NVIC_IPR_R_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR23_R_NVIC_LPTIM1_IP15    NVIC_IPR_R_NVIC_PERIPHERAL1_IP15
/*----------*/

/*----------*/
#define NVIC_IPR23_NVIC_HDMI_CEC_MASK    NVIC_IPR_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR23_NVIC_HDMI_CEC_IP0    NVIC_IPR_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR23_NVIC_HDMI_CEC_IP1    NVIC_IPR_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR23_NVIC_HDMI_CEC_IP2    NVIC_IPR_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR23_NVIC_HDMI_CEC_IP3    NVIC_IPR_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR23_NVIC_HDMI_CEC_IP4    NVIC_IPR_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR23_NVIC_HDMI_CEC_IP5    NVIC_IPR_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR23_NVIC_HDMI_CEC_IP6    NVIC_IPR_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR23_NVIC_HDMI_CEC_IP7    NVIC_IPR_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR23_NVIC_HDMI_CEC_IP8    NVIC_IPR_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR23_NVIC_HDMI_CEC_IP9    NVIC_IPR_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR23_NVIC_HDMI_CEC_IP10    NVIC_IPR_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR23_NVIC_HDMI_CEC_IP11    NVIC_IPR_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR23_NVIC_HDMI_CEC_IP12    NVIC_IPR_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR23_NVIC_HDMI_CEC_IP13    NVIC_IPR_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR23_NVIC_HDMI_CEC_IP14    NVIC_IPR_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR23_NVIC_HDMI_CEC_IP15    NVIC_IPR_NVIC_PERIPHERAL2_IP15

#define NVIC_IPR23_R_NVIC_HDMI_CEC_BIT    NVIC_IPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IPR23_R_NVIC_HDMI_CEC_MASK    NVIC_IPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP0    NVIC_IPR_R_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP1    NVIC_IPR_R_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP2    NVIC_IPR_R_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP3    NVIC_IPR_R_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP4    NVIC_IPR_R_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP5    NVIC_IPR_R_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP6    NVIC_IPR_R_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP7    NVIC_IPR_R_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP8    NVIC_IPR_R_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP9    NVIC_IPR_R_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP10    NVIC_IPR_R_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP11    NVIC_IPR_R_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP12    NVIC_IPR_R_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP13    NVIC_IPR_R_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP14    NVIC_IPR_R_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR23_R_NVIC_HDMI_CEC_IP15    NVIC_IPR_R_NVIC_PERIPHERAL2_IP15
/*----------*/

/*----------*/
#define NVIC_IPR23_NVIC_I2C4_EV_MASK    NVIC_IPR_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR23_NVIC_I2C4_EV_IP0    NVIC_IPR_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR23_NVIC_I2C4_EV_IP1    NVIC_IPR_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR23_NVIC_I2C4_EV_IP2    NVIC_IPR_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR23_NVIC_I2C4_EV_IP3    NVIC_IPR_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR23_NVIC_I2C4_EV_IP4    NVIC_IPR_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR23_NVIC_I2C4_EV_IP5    NVIC_IPR_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR23_NVIC_I2C4_EV_IP6    NVIC_IPR_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR23_NVIC_I2C4_EV_IP7    NVIC_IPR_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR23_NVIC_I2C4_EV_IP8    NVIC_IPR_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR23_NVIC_I2C4_EV_IP9    NVIC_IPR_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR23_NVIC_I2C4_EV_IP10    NVIC_IPR_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR23_NVIC_I2C4_EV_IP11    NVIC_IPR_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR23_NVIC_I2C4_EV_IP12    NVIC_IPR_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR23_NVIC_I2C4_EV_IP13    NVIC_IPR_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR23_NVIC_I2C4_EV_IP14    NVIC_IPR_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR23_NVIC_I2C4_EV_IP15    NVIC_IPR_NVIC_PERIPHERAL3_IP15

#define NVIC_IPR23_R_NVIC_I2C4_EV_BIT    NVIC_IPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IPR23_R_NVIC_I2C4_EV_MASK    NVIC_IPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP0    NVIC_IPR_R_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP1    NVIC_IPR_R_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP2    NVIC_IPR_R_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP3    NVIC_IPR_R_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP4    NVIC_IPR_R_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP5    NVIC_IPR_R_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP6    NVIC_IPR_R_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP7    NVIC_IPR_R_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP8    NVIC_IPR_R_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP9    NVIC_IPR_R_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP10    NVIC_IPR_R_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP11    NVIC_IPR_R_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP12    NVIC_IPR_R_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP13    NVIC_IPR_R_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP14    NVIC_IPR_R_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR23_R_NVIC_I2C4_EV_IP15    NVIC_IPR_R_NVIC_PERIPHERAL3_IP15
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR23_H_ */
