/**
 *
 * @file NVIC_RegisterDefines_IPR20.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 22 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date    Author    Version    Description
 * 22 jun. 2020    vyldram    1.0    initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR20_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR20_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_IPR/xHeader/NVIC_RegisterDefines_IPR_Generic.h>

/********************************************************************************************/
/************************************* IPR20 ***********************************************/
/******************************************************************************************/

/*----------*/
#define NVIC_IPR20_NVIC_HASH_RNG_MASK    NVIC_IPR_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR20_NVIC_HASH_RNG_IP0    NVIC_IPR_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR20_NVIC_HASH_RNG_IP1    NVIC_IPR_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR20_NVIC_HASH_RNG_IP2    NVIC_IPR_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR20_NVIC_HASH_RNG_IP3    NVIC_IPR_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR20_NVIC_HASH_RNG_IP4    NVIC_IPR_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR20_NVIC_HASH_RNG_IP5    NVIC_IPR_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR20_NVIC_HASH_RNG_IP6    NVIC_IPR_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR20_NVIC_HASH_RNG_IP7    NVIC_IPR_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR20_NVIC_HASH_RNG_IP8    NVIC_IPR_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR20_NVIC_HASH_RNG_IP9    NVIC_IPR_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR20_NVIC_HASH_RNG_IP10    NVIC_IPR_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR20_NVIC_HASH_RNG_IP11    NVIC_IPR_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR20_NVIC_HASH_RNG_IP12    NVIC_IPR_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR20_NVIC_HASH_RNG_IP13    NVIC_IPR_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR20_NVIC_HASH_RNG_IP14    NVIC_IPR_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR20_NVIC_HASH_RNG_IP15    NVIC_IPR_NVIC_PERIPHERAL0_IP15

#define NVIC_IPR20_R_NVIC_HASH_RNG_BIT    NVIC_IPR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IPR20_R_NVIC_HASH_RNG_MASK    NVIC_IPR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP0    NVIC_IPR_R_NVIC_PERIPHERAL0_IP0
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP1    NVIC_IPR_R_NVIC_PERIPHERAL0_IP1
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP2    NVIC_IPR_R_NVIC_PERIPHERAL0_IP2
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP3    NVIC_IPR_R_NVIC_PERIPHERAL0_IP3
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP4    NVIC_IPR_R_NVIC_PERIPHERAL0_IP4
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP5    NVIC_IPR_R_NVIC_PERIPHERAL0_IP5
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP6    NVIC_IPR_R_NVIC_PERIPHERAL0_IP6
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP7    NVIC_IPR_R_NVIC_PERIPHERAL0_IP7
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP8    NVIC_IPR_R_NVIC_PERIPHERAL0_IP8
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP9    NVIC_IPR_R_NVIC_PERIPHERAL0_IP9
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP10    NVIC_IPR_R_NVIC_PERIPHERAL0_IP10
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP11    NVIC_IPR_R_NVIC_PERIPHERAL0_IP11
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP12    NVIC_IPR_R_NVIC_PERIPHERAL0_IP12
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP13    NVIC_IPR_R_NVIC_PERIPHERAL0_IP13
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP14    NVIC_IPR_R_NVIC_PERIPHERAL0_IP14
#define NVIC_IPR20_R_NVIC_HASH_RNG_IP15    NVIC_IPR_R_NVIC_PERIPHERAL0_IP15
/*----------*/

/*----------*/
#define NVIC_IPR20_NVIC_FPU_MASK    NVIC_IPR_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR20_NVIC_FPU_IP0    NVIC_IPR_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR20_NVIC_FPU_IP1    NVIC_IPR_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR20_NVIC_FPU_IP2    NVIC_IPR_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR20_NVIC_FPU_IP3    NVIC_IPR_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR20_NVIC_FPU_IP4    NVIC_IPR_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR20_NVIC_FPU_IP5    NVIC_IPR_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR20_NVIC_FPU_IP6    NVIC_IPR_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR20_NVIC_FPU_IP7    NVIC_IPR_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR20_NVIC_FPU_IP8    NVIC_IPR_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR20_NVIC_FPU_IP9    NVIC_IPR_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR20_NVIC_FPU_IP10    NVIC_IPR_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR20_NVIC_FPU_IP11    NVIC_IPR_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR20_NVIC_FPU_IP12    NVIC_IPR_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR20_NVIC_FPU_IP13    NVIC_IPR_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR20_NVIC_FPU_IP14    NVIC_IPR_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR20_NVIC_FPU_IP15    NVIC_IPR_NVIC_PERIPHERAL1_IP15

#define NVIC_IPR20_R_NVIC_FPU_BIT    NVIC_IPR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IPR20_R_NVIC_FPU_MASK    NVIC_IPR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IPR20_R_NVIC_FPU_IP0    NVIC_IPR_R_NVIC_PERIPHERAL1_IP0
#define NVIC_IPR20_R_NVIC_FPU_IP1    NVIC_IPR_R_NVIC_PERIPHERAL1_IP1
#define NVIC_IPR20_R_NVIC_FPU_IP2    NVIC_IPR_R_NVIC_PERIPHERAL1_IP2
#define NVIC_IPR20_R_NVIC_FPU_IP3    NVIC_IPR_R_NVIC_PERIPHERAL1_IP3
#define NVIC_IPR20_R_NVIC_FPU_IP4    NVIC_IPR_R_NVIC_PERIPHERAL1_IP4
#define NVIC_IPR20_R_NVIC_FPU_IP5    NVIC_IPR_R_NVIC_PERIPHERAL1_IP5
#define NVIC_IPR20_R_NVIC_FPU_IP6    NVIC_IPR_R_NVIC_PERIPHERAL1_IP6
#define NVIC_IPR20_R_NVIC_FPU_IP7    NVIC_IPR_R_NVIC_PERIPHERAL1_IP7
#define NVIC_IPR20_R_NVIC_FPU_IP8    NVIC_IPR_R_NVIC_PERIPHERAL1_IP8
#define NVIC_IPR20_R_NVIC_FPU_IP9    NVIC_IPR_R_NVIC_PERIPHERAL1_IP9
#define NVIC_IPR20_R_NVIC_FPU_IP10    NVIC_IPR_R_NVIC_PERIPHERAL1_IP10
#define NVIC_IPR20_R_NVIC_FPU_IP11    NVIC_IPR_R_NVIC_PERIPHERAL1_IP11
#define NVIC_IPR20_R_NVIC_FPU_IP12    NVIC_IPR_R_NVIC_PERIPHERAL1_IP12
#define NVIC_IPR20_R_NVIC_FPU_IP13    NVIC_IPR_R_NVIC_PERIPHERAL1_IP13
#define NVIC_IPR20_R_NVIC_FPU_IP14    NVIC_IPR_R_NVIC_PERIPHERAL1_IP14
#define NVIC_IPR20_R_NVIC_FPU_IP15    NVIC_IPR_R_NVIC_PERIPHERAL1_IP15
/*----------*/

/*----------*/
#define NVIC_IPR20_NVIC_UART7_MASK    NVIC_IPR_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR20_NVIC_UART7_IP0    NVIC_IPR_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR20_NVIC_UART7_IP1    NVIC_IPR_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR20_NVIC_UART7_IP2    NVIC_IPR_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR20_NVIC_UART7_IP3    NVIC_IPR_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR20_NVIC_UART7_IP4    NVIC_IPR_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR20_NVIC_UART7_IP5    NVIC_IPR_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR20_NVIC_UART7_IP6    NVIC_IPR_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR20_NVIC_UART7_IP7    NVIC_IPR_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR20_NVIC_UART7_IP8    NVIC_IPR_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR20_NVIC_UART7_IP9    NVIC_IPR_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR20_NVIC_UART7_IP10    NVIC_IPR_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR20_NVIC_UART7_IP11    NVIC_IPR_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR20_NVIC_UART7_IP12    NVIC_IPR_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR20_NVIC_UART7_IP13    NVIC_IPR_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR20_NVIC_UART7_IP14    NVIC_IPR_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR20_NVIC_UART7_IP15    NVIC_IPR_NVIC_PERIPHERAL2_IP15

#define NVIC_IPR20_R_NVIC_UART7_BIT    NVIC_IPR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IPR20_R_NVIC_UART7_MASK    NVIC_IPR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IPR20_R_NVIC_UART7_IP0    NVIC_IPR_R_NVIC_PERIPHERAL2_IP0
#define NVIC_IPR20_R_NVIC_UART7_IP1    NVIC_IPR_R_NVIC_PERIPHERAL2_IP1
#define NVIC_IPR20_R_NVIC_UART7_IP2    NVIC_IPR_R_NVIC_PERIPHERAL2_IP2
#define NVIC_IPR20_R_NVIC_UART7_IP3    NVIC_IPR_R_NVIC_PERIPHERAL2_IP3
#define NVIC_IPR20_R_NVIC_UART7_IP4    NVIC_IPR_R_NVIC_PERIPHERAL2_IP4
#define NVIC_IPR20_R_NVIC_UART7_IP5    NVIC_IPR_R_NVIC_PERIPHERAL2_IP5
#define NVIC_IPR20_R_NVIC_UART7_IP6    NVIC_IPR_R_NVIC_PERIPHERAL2_IP6
#define NVIC_IPR20_R_NVIC_UART7_IP7    NVIC_IPR_R_NVIC_PERIPHERAL2_IP7
#define NVIC_IPR20_R_NVIC_UART7_IP8    NVIC_IPR_R_NVIC_PERIPHERAL2_IP8
#define NVIC_IPR20_R_NVIC_UART7_IP9    NVIC_IPR_R_NVIC_PERIPHERAL2_IP9
#define NVIC_IPR20_R_NVIC_UART7_IP10    NVIC_IPR_R_NVIC_PERIPHERAL2_IP10
#define NVIC_IPR20_R_NVIC_UART7_IP11    NVIC_IPR_R_NVIC_PERIPHERAL2_IP11
#define NVIC_IPR20_R_NVIC_UART7_IP12    NVIC_IPR_R_NVIC_PERIPHERAL2_IP12
#define NVIC_IPR20_R_NVIC_UART7_IP13    NVIC_IPR_R_NVIC_PERIPHERAL2_IP13
#define NVIC_IPR20_R_NVIC_UART7_IP14    NVIC_IPR_R_NVIC_PERIPHERAL2_IP14
#define NVIC_IPR20_R_NVIC_UART7_IP15    NVIC_IPR_R_NVIC_PERIPHERAL2_IP15
/*----------*/

/*----------*/
#define NVIC_IPR20_NVIC_UART8_MASK    NVIC_IPR_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR20_NVIC_UART8_IP0    NVIC_IPR_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR20_NVIC_UART8_IP1    NVIC_IPR_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR20_NVIC_UART8_IP2    NVIC_IPR_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR20_NVIC_UART8_IP3    NVIC_IPR_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR20_NVIC_UART8_IP4    NVIC_IPR_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR20_NVIC_UART8_IP5    NVIC_IPR_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR20_NVIC_UART8_IP6    NVIC_IPR_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR20_NVIC_UART8_IP7    NVIC_IPR_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR20_NVIC_UART8_IP8    NVIC_IPR_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR20_NVIC_UART8_IP9    NVIC_IPR_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR20_NVIC_UART8_IP10    NVIC_IPR_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR20_NVIC_UART8_IP11    NVIC_IPR_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR20_NVIC_UART8_IP12    NVIC_IPR_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR20_NVIC_UART8_IP13    NVIC_IPR_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR20_NVIC_UART8_IP14    NVIC_IPR_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR20_NVIC_UART8_IP15    NVIC_IPR_NVIC_PERIPHERAL3_IP15

#define NVIC_IPR20_R_NVIC_UART8_BIT    NVIC_IPR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IPR20_R_NVIC_UART8_MASK    NVIC_IPR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IPR20_R_NVIC_UART8_IP0    NVIC_IPR_R_NVIC_PERIPHERAL3_IP0
#define NVIC_IPR20_R_NVIC_UART8_IP1    NVIC_IPR_R_NVIC_PERIPHERAL3_IP1
#define NVIC_IPR20_R_NVIC_UART8_IP2    NVIC_IPR_R_NVIC_PERIPHERAL3_IP2
#define NVIC_IPR20_R_NVIC_UART8_IP3    NVIC_IPR_R_NVIC_PERIPHERAL3_IP3
#define NVIC_IPR20_R_NVIC_UART8_IP4    NVIC_IPR_R_NVIC_PERIPHERAL3_IP4
#define NVIC_IPR20_R_NVIC_UART8_IP5    NVIC_IPR_R_NVIC_PERIPHERAL3_IP5
#define NVIC_IPR20_R_NVIC_UART8_IP6    NVIC_IPR_R_NVIC_PERIPHERAL3_IP6
#define NVIC_IPR20_R_NVIC_UART8_IP7    NVIC_IPR_R_NVIC_PERIPHERAL3_IP7
#define NVIC_IPR20_R_NVIC_UART8_IP8    NVIC_IPR_R_NVIC_PERIPHERAL3_IP8
#define NVIC_IPR20_R_NVIC_UART8_IP9    NVIC_IPR_R_NVIC_PERIPHERAL3_IP9
#define NVIC_IPR20_R_NVIC_UART8_IP10    NVIC_IPR_R_NVIC_PERIPHERAL3_IP10
#define NVIC_IPR20_R_NVIC_UART8_IP11    NVIC_IPR_R_NVIC_PERIPHERAL3_IP11
#define NVIC_IPR20_R_NVIC_UART8_IP12    NVIC_IPR_R_NVIC_PERIPHERAL3_IP12
#define NVIC_IPR20_R_NVIC_UART8_IP13    NVIC_IPR_R_NVIC_PERIPHERAL3_IP13
#define NVIC_IPR20_R_NVIC_UART8_IP14    NVIC_IPR_R_NVIC_PERIPHERAL3_IP14
#define NVIC_IPR20_R_NVIC_UART8_IP15    NVIC_IPR_R_NVIC_PERIPHERAL3_IP15
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_IPR_NVIC_REGISTERDEFINES_IPR20_H_ */
