/**
 *
 * @file NVIC_RegisterDefines_Set3_IABR.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET3_NVIC_REGISTERDEFINES_SET3_IABR_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET3_NVIC_REGISTERDEFINES_SET3_IABR_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_Set/RegisterDefines_Set_Generic/NVIC_RegisterDefines_Set_Generic.h>

/********************************************************************************************/
/************************************* IABR3 ***********************************************/
/********************************************************************************************/

/*----------*/
#define NVIC_IABR3_NVIC_I2C4_ER_MASK    NVIC_IABR_NVIC_PERIPHERAL0_MASK
#define NVIC_IABR3_NVIC_I2C4_ER_DIS    NVIC_IABR_NVIC_PERIPHERAL0_DIS
#define NVIC_IABR3_NVIC_I2C4_ER_ENA    NVIC_IABR_NVIC_PERIPHERAL0_ENA

#define NVIC_IABR3_R_NVIC_I2C4_ER_BIT    NVIC_IABR_R_NVIC_PERIPHERAL0_BIT
#define NVIC_IABR3_R_NVIC_I2C4_ER_MASK    NVIC_IABR_R_NVIC_PERIPHERAL0_MASK
#define NVIC_IABR3_R_NVIC_I2C4_ER_DIS    NVIC_IABR_R_NVIC_PERIPHERAL0_DIS
#define NVIC_IABR3_R_NVIC_I2C4_ER_ENA    NVIC_IABR_R_NVIC_PERIPHERAL0_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_SPDIF_RX_MASK    NVIC_IABR_NVIC_PERIPHERAL1_MASK
#define NVIC_IABR3_NVIC_SPDIF_RX_DIS    NVIC_IABR_NVIC_PERIPHERAL1_DIS
#define NVIC_IABR3_NVIC_SPDIF_RX_ENA    NVIC_IABR_NVIC_PERIPHERAL1_ENA

#define NVIC_IABR3_R_NVIC_SPDIF_RX_BIT    NVIC_IABR_R_NVIC_PERIPHERAL1_BIT
#define NVIC_IABR3_R_NVIC_SPDIF_RX_MASK    NVIC_IABR_R_NVIC_PERIPHERAL1_MASK
#define NVIC_IABR3_R_NVIC_SPDIF_RX_DIS    NVIC_IABR_R_NVIC_PERIPHERAL1_DIS
#define NVIC_IABR3_R_NVIC_SPDIF_RX_ENA    NVIC_IABR_R_NVIC_PERIPHERAL1_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_DSI_HOST_MASK    NVIC_IABR_NVIC_PERIPHERAL2_MASK
#define NVIC_IABR3_NVIC_DSI_HOST_DIS    NVIC_IABR_NVIC_PERIPHERAL2_DIS
#define NVIC_IABR3_NVIC_DSI_HOST_ENA    NVIC_IABR_NVIC_PERIPHERAL2_ENA

#define NVIC_IABR3_R_NVIC_DSI_HOST_BIT    NVIC_IABR_R_NVIC_PERIPHERAL2_BIT
#define NVIC_IABR3_R_NVIC_DSI_HOST_MASK    NVIC_IABR_R_NVIC_PERIPHERAL2_MASK
#define NVIC_IABR3_R_NVIC_DSI_HOST_DIS    NVIC_IABR_R_NVIC_PERIPHERAL2_DIS
#define NVIC_IABR3_R_NVIC_DSI_HOST_ENA    NVIC_IABR_R_NVIC_PERIPHERAL2_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_DFSDM1_FLT0_MASK    NVIC_IABR_NVIC_PERIPHERAL3_MASK
#define NVIC_IABR3_NVIC_DFSDM1_FLT0_DIS    NVIC_IABR_NVIC_PERIPHERAL3_DIS
#define NVIC_IABR3_NVIC_DFSDM1_FLT0_ENA    NVIC_IABR_NVIC_PERIPHERAL3_ENA

#define NVIC_IABR3_R_NVIC_DFSDM1_FLT0_BIT    NVIC_IABR_R_NVIC_PERIPHERAL3_BIT
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT0_MASK    NVIC_IABR_R_NVIC_PERIPHERAL3_MASK
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT0_DIS    NVIC_IABR_R_NVIC_PERIPHERAL3_DIS
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT0_ENA    NVIC_IABR_R_NVIC_PERIPHERAL3_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_DFSDM1_FLT1_MASK    NVIC_IABR_NVIC_PERIPHERAL4_MASK
#define NVIC_IABR3_NVIC_DFSDM1_FLT1_DIS    NVIC_IABR_NVIC_PERIPHERAL4_DIS
#define NVIC_IABR3_NVIC_DFSDM1_FLT1_ENA    NVIC_IABR_NVIC_PERIPHERAL4_ENA

#define NVIC_IABR3_R_NVIC_DFSDM1_FLT1_BIT    NVIC_IABR_R_NVIC_PERIPHERAL4_BIT
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT1_MASK    NVIC_IABR_R_NVIC_PERIPHERAL4_MASK
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT1_DIS    NVIC_IABR_R_NVIC_PERIPHERAL4_DIS
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT1_ENA    NVIC_IABR_R_NVIC_PERIPHERAL4_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_DFSDM1_FLT2_MASK    NVIC_IABR_NVIC_PERIPHERAL5_MASK
#define NVIC_IABR3_NVIC_DFSDM1_FLT2_DIS    NVIC_IABR_NVIC_PERIPHERAL5_DIS
#define NVIC_IABR3_NVIC_DFSDM1_FLT2_ENA    NVIC_IABR_NVIC_PERIPHERAL5_ENA

#define NVIC_IABR3_R_NVIC_DFSDM1_FLT2_BIT    NVIC_IABR_R_NVIC_PERIPHERAL5_BIT
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT2_MASK    NVIC_IABR_R_NVIC_PERIPHERAL5_MASK
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT2_DIS    NVIC_IABR_R_NVIC_PERIPHERAL5_DIS
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT2_ENA    NVIC_IABR_R_NVIC_PERIPHERAL5_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_DFSDM1_FLT3_MASK    NVIC_IABR_NVIC_PERIPHERAL6_MASK
#define NVIC_IABR3_NVIC_DFSDM1_FLT3_DIS    NVIC_IABR_NVIC_PERIPHERAL6_DIS
#define NVIC_IABR3_NVIC_DFSDM1_FLT3_ENA    NVIC_IABR_NVIC_PERIPHERAL6_ENA

#define NVIC_IABR3_R_NVIC_DFSDM1_FLT3_BIT    NVIC_IABR_R_NVIC_PERIPHERAL6_BIT
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT3_MASK    NVIC_IABR_R_NVIC_PERIPHERAL6_MASK
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT3_DIS    NVIC_IABR_R_NVIC_PERIPHERAL6_DIS
#define NVIC_IABR3_R_NVIC_DFSDM1_FLT3_ENA    NVIC_IABR_R_NVIC_PERIPHERAL6_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_SDMMC2_MASK    NVIC_IABR_NVIC_PERIPHERAL7_MASK
#define NVIC_IABR3_NVIC_SDMMC2_DIS    NVIC_IABR_NVIC_PERIPHERAL7_DIS
#define NVIC_IABR3_NVIC_SDMMC2_ENA    NVIC_IABR_NVIC_PERIPHERAL7_ENA

#define NVIC_IABR3_R_NVIC_SDMMC2_BIT    NVIC_IABR_R_NVIC_PERIPHERAL7_BIT
#define NVIC_IABR3_R_NVIC_SDMMC2_MASK    NVIC_IABR_R_NVIC_PERIPHERAL7_MASK
#define NVIC_IABR3_R_NVIC_SDMMC2_DIS    NVIC_IABR_R_NVIC_PERIPHERAL7_DIS
#define NVIC_IABR3_R_NVIC_SDMMC2_ENA    NVIC_IABR_R_NVIC_PERIPHERAL7_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_CAN3_TX_MASK    NVIC_IABR_NVIC_PERIPHERAL8_MASK
#define NVIC_IABR3_NVIC_CAN3_TX_DIS    NVIC_IABR_NVIC_PERIPHERAL8_DIS
#define NVIC_IABR3_NVIC_CAN3_TX_ENA    NVIC_IABR_NVIC_PERIPHERAL8_ENA

#define NVIC_IABR3_R_NVIC_CAN3_TX_BIT    NVIC_IABR_R_NVIC_PERIPHERAL8_BIT
#define NVIC_IABR3_R_NVIC_CAN3_TX_MASK    NVIC_IABR_R_NVIC_PERIPHERAL8_MASK
#define NVIC_IABR3_R_NVIC_CAN3_TX_DIS    NVIC_IABR_R_NVIC_PERIPHERAL8_DIS
#define NVIC_IABR3_R_NVIC_CAN3_TX_ENA    NVIC_IABR_R_NVIC_PERIPHERAL8_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_CAN3_RX0_MASK    NVIC_IABR_NVIC_PERIPHERAL9_MASK
#define NVIC_IABR3_NVIC_CAN3_RX0_DIS    NVIC_IABR_NVIC_PERIPHERAL9_DIS
#define NVIC_IABR3_NVIC_CAN3_RX0_ENA    NVIC_IABR_NVIC_PERIPHERAL9_ENA

#define NVIC_IABR3_R_NVIC_CAN3_RX0_BIT    NVIC_IABR_R_NVIC_PERIPHERAL9_BIT
#define NVIC_IABR3_R_NVIC_CAN3_RX0_MASK    NVIC_IABR_R_NVIC_PERIPHERAL9_MASK
#define NVIC_IABR3_R_NVIC_CAN3_RX0_DIS    NVIC_IABR_R_NVIC_PERIPHERAL9_DIS
#define NVIC_IABR3_R_NVIC_CAN3_RX0_ENA    NVIC_IABR_R_NVIC_PERIPHERAL9_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_CAN3_RX1_MASK    NVIC_IABR_NVIC_PERIPHERAL10_MASK
#define NVIC_IABR3_NVIC_CAN3_RX1_DIS    NVIC_IABR_NVIC_PERIPHERAL10_DIS
#define NVIC_IABR3_NVIC_CAN3_RX1_ENA    NVIC_IABR_NVIC_PERIPHERAL10_ENA

#define NVIC_IABR3_R_NVIC_CAN3_RX1_BIT    NVIC_IABR_R_NVIC_PERIPHERAL10_BIT
#define NVIC_IABR3_R_NVIC_CAN3_RX1_MASK    NVIC_IABR_R_NVIC_PERIPHERAL10_MASK
#define NVIC_IABR3_R_NVIC_CAN3_RX1_DIS    NVIC_IABR_R_NVIC_PERIPHERAL10_DIS
#define NVIC_IABR3_R_NVIC_CAN3_RX1_ENA    NVIC_IABR_R_NVIC_PERIPHERAL10_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_CAN3_SCE_MASK    NVIC_IABR_NVIC_PERIPHERAL11_MASK
#define NVIC_IABR3_NVIC_CAN3_SCE_DIS    NVIC_IABR_NVIC_PERIPHERAL11_DIS
#define NVIC_IABR3_NVIC_CAN3_SCE_ENA    NVIC_IABR_NVIC_PERIPHERAL11_ENA

#define NVIC_IABR3_R_NVIC_CAN3_SCE_BIT    NVIC_IABR_R_NVIC_PERIPHERAL11_BIT
#define NVIC_IABR3_R_NVIC_CAN3_SCE_MASK    NVIC_IABR_R_NVIC_PERIPHERAL11_MASK
#define NVIC_IABR3_R_NVIC_CAN3_SCE_DIS    NVIC_IABR_R_NVIC_PERIPHERAL11_DIS
#define NVIC_IABR3_R_NVIC_CAN3_SCE_ENA    NVIC_IABR_R_NVIC_PERIPHERAL11_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_JPEG_MASK    NVIC_IABR_NVIC_PERIPHERAL12_MASK
#define NVIC_IABR3_NVIC_JPEG_DIS    NVIC_IABR_NVIC_PERIPHERAL12_DIS
#define NVIC_IABR3_NVIC_JPEG_ENA    NVIC_IABR_NVIC_PERIPHERAL12_ENA

#define NVIC_IABR3_R_NVIC_JPEG_BIT    NVIC_IABR_R_NVIC_PERIPHERAL12_BIT
#define NVIC_IABR3_R_NVIC_JPEG_MASK    NVIC_IABR_R_NVIC_PERIPHERAL12_MASK
#define NVIC_IABR3_R_NVIC_JPEG_DIS    NVIC_IABR_R_NVIC_PERIPHERAL12_DIS
#define NVIC_IABR3_R_NVIC_JPEG_ENA    NVIC_IABR_R_NVIC_PERIPHERAL12_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_MDIO_SLAVE_MASK    NVIC_IABR_NVIC_PERIPHERAL13_MASK
#define NVIC_IABR3_NVIC_MDIO_SLAVE_DIS    NVIC_IABR_NVIC_PERIPHERAL13_DIS
#define NVIC_IABR3_NVIC_MDIO_SLAVE_ENA    NVIC_IABR_NVIC_PERIPHERAL13_ENA

#define NVIC_IABR3_R_NVIC_MDIO_SLAVE_BIT    NVIC_IABR_R_NVIC_PERIPHERAL13_BIT
#define NVIC_IABR3_R_NVIC_MDIO_SLAVE_MASK    NVIC_IABR_R_NVIC_PERIPHERAL13_MASK
#define NVIC_IABR3_R_NVIC_MDIO_SLAVE_DIS    NVIC_IABR_R_NVIC_PERIPHERAL13_DIS
#define NVIC_IABR3_R_NVIC_MDIO_SLAVE_ENA    NVIC_IABR_R_NVIC_PERIPHERAL13_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES126_MASK    NVIC_IABR_NVIC_PERIPHERAL14_MASK
#define NVIC_IABR3_NVIC_RES126_DIS    NVIC_IABR_NVIC_PERIPHERAL14_DIS
#define NVIC_IABR3_NVIC_RES126_ENA    NVIC_IABR_NVIC_PERIPHERAL14_ENA

#define NVIC_IABR3_R_NVIC_RES126_BIT    NVIC_IABR_R_NVIC_PERIPHERAL14_BIT
#define NVIC_IABR3_R_NVIC_RES126_MASK    NVIC_IABR_R_NVIC_PERIPHERAL14_MASK
#define NVIC_IABR3_R_NVIC_RES126_DIS    NVIC_IABR_R_NVIC_PERIPHERAL14_DIS
#define NVIC_IABR3_R_NVIC_RES126_ENA    NVIC_IABR_R_NVIC_PERIPHERAL14_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES127_MASK    NVIC_IABR_NVIC_PERIPHERAL15_MASK
#define NVIC_IABR3_NVIC_RES127_DIS    NVIC_IABR_NVIC_PERIPHERAL15_DIS
#define NVIC_IABR3_NVIC_RES127_ENA    NVIC_IABR_NVIC_PERIPHERAL15_ENA

#define NVIC_IABR3_R_NVIC_RES127_BIT    NVIC_IABR_R_NVIC_PERIPHERAL15_BIT
#define NVIC_IABR3_R_NVIC_RES127_MASK    NVIC_IABR_R_NVIC_PERIPHERAL15_MASK
#define NVIC_IABR3_R_NVIC_RES127_DIS    NVIC_IABR_R_NVIC_PERIPHERAL15_DIS
#define NVIC_IABR3_R_NVIC_RES127_ENA    NVIC_IABR_R_NVIC_PERIPHERAL15_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES128_MASK    NVIC_IABR_NVIC_PERIPHERAL16_MASK
#define NVIC_IABR3_NVIC_RES128_DIS    NVIC_IABR_NVIC_PERIPHERAL16_DIS
#define NVIC_IABR3_NVIC_RES128_ENA    NVIC_IABR_NVIC_PERIPHERAL16_ENA

#define NVIC_IABR3_R_NVIC_RES128_BIT    NVIC_IABR_R_NVIC_PERIPHERAL16_BIT
#define NVIC_IABR3_R_NVIC_RES128_MASK    NVIC_IABR_R_NVIC_PERIPHERAL16_MASK
#define NVIC_IABR3_R_NVIC_RES128_DIS    NVIC_IABR_R_NVIC_PERIPHERAL16_DIS
#define NVIC_IABR3_R_NVIC_RES128_ENA    NVIC_IABR_R_NVIC_PERIPHERAL16_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES129_MASK    NVIC_IABR_NVIC_PERIPHERAL17_MASK
#define NVIC_IABR3_NVIC_RES129_DIS    NVIC_IABR_NVIC_PERIPHERAL17_DIS
#define NVIC_IABR3_NVIC_RES129_ENA    NVIC_IABR_NVIC_PERIPHERAL17_ENA

#define NVIC_IABR3_R_NVIC_RES129_BIT    NVIC_IABR_R_NVIC_PERIPHERAL17_BIT
#define NVIC_IABR3_R_NVIC_RES129_MASK    NVIC_IABR_R_NVIC_PERIPHERAL17_MASK
#define NVIC_IABR3_R_NVIC_RES129_DIS    NVIC_IABR_R_NVIC_PERIPHERAL17_DIS
#define NVIC_IABR3_R_NVIC_RES129_ENA    NVIC_IABR_R_NVIC_PERIPHERAL17_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES130_MASK    NVIC_IABR_NVIC_PERIPHERAL18_MASK
#define NVIC_IABR3_NVIC_RES130_DIS    NVIC_IABR_NVIC_PERIPHERAL18_DIS
#define NVIC_IABR3_NVIC_RES130_ENA    NVIC_IABR_NVIC_PERIPHERAL18_ENA

#define NVIC_IABR3_R_NVIC_RES130_BIT    NVIC_IABR_R_NVIC_PERIPHERAL18_BIT
#define NVIC_IABR3_R_NVIC_RES130_MASK    NVIC_IABR_R_NVIC_PERIPHERAL18_MASK
#define NVIC_IABR3_R_NVIC_RES130_DIS    NVIC_IABR_R_NVIC_PERIPHERAL18_DIS
#define NVIC_IABR3_R_NVIC_RES130_ENA    NVIC_IABR_R_NVIC_PERIPHERAL18_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES131_MASK    NVIC_IABR_NVIC_PERIPHERAL19_MASK
#define NVIC_IABR3_NVIC_RES131_DIS    NVIC_IABR_NVIC_PERIPHERAL19_DIS
#define NVIC_IABR3_NVIC_RES131_ENA    NVIC_IABR_NVIC_PERIPHERAL19_ENA

#define NVIC_IABR3_R_NVIC_RES131_BIT    NVIC_IABR_R_NVIC_PERIPHERAL19_BIT
#define NVIC_IABR3_R_NVIC_RES131_MASK    NVIC_IABR_R_NVIC_PERIPHERAL19_MASK
#define NVIC_IABR3_R_NVIC_RES131_DIS    NVIC_IABR_R_NVIC_PERIPHERAL19_DIS
#define NVIC_IABR3_R_NVIC_RES131_ENA    NVIC_IABR_R_NVIC_PERIPHERAL19_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES132_MASK    NVIC_IABR_NVIC_PERIPHERAL20_MASK
#define NVIC_IABR3_NVIC_RES132_DIS    NVIC_IABR_NVIC_PERIPHERAL20_DIS
#define NVIC_IABR3_NVIC_RES132_ENA    NVIC_IABR_NVIC_PERIPHERAL20_ENA

#define NVIC_IABR3_R_NVIC_RES132_BIT    NVIC_IABR_R_NVIC_PERIPHERAL20_BIT
#define NVIC_IABR3_R_NVIC_RES132_MASK    NVIC_IABR_R_NVIC_PERIPHERAL20_MASK
#define NVIC_IABR3_R_NVIC_RES132_DIS    NVIC_IABR_R_NVIC_PERIPHERAL20_DIS
#define NVIC_IABR3_R_NVIC_RES132_ENA    NVIC_IABR_R_NVIC_PERIPHERAL20_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES133_MASK    NVIC_IABR_NVIC_PERIPHERAL21_MASK
#define NVIC_IABR3_NVIC_RES133_DIS    NVIC_IABR_NVIC_PERIPHERAL21_DIS
#define NVIC_IABR3_NVIC_RES133_ENA    NVIC_IABR_NVIC_PERIPHERAL21_ENA

#define NVIC_IABR3_R_NVIC_RES133_BIT    NVIC_IABR_R_NVIC_PERIPHERAL21_BIT
#define NVIC_IABR3_R_NVIC_RES133_MASK    NVIC_IABR_R_NVIC_PERIPHERAL21_MASK
#define NVIC_IABR3_R_NVIC_RES133_DIS    NVIC_IABR_R_NVIC_PERIPHERAL21_DIS
#define NVIC_IABR3_R_NVIC_RES133_ENA    NVIC_IABR_R_NVIC_PERIPHERAL21_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES134_MASK    NVIC_IABR_NVIC_PERIPHERAL22_MASK
#define NVIC_IABR3_NVIC_RES134_DIS    NVIC_IABR_NVIC_PERIPHERAL22_DIS
#define NVIC_IABR3_NVIC_RES134_ENA    NVIC_IABR_NVIC_PERIPHERAL22_ENA

#define NVIC_IABR3_R_NVIC_RES134_BIT    NVIC_IABR_R_NVIC_PERIPHERAL22_BIT
#define NVIC_IABR3_R_NVIC_RES134_MASK    NVIC_IABR_R_NVIC_PERIPHERAL22_MASK
#define NVIC_IABR3_R_NVIC_RES134_DIS    NVIC_IABR_R_NVIC_PERIPHERAL22_DIS
#define NVIC_IABR3_R_NVIC_RES134_ENA    NVIC_IABR_R_NVIC_PERIPHERAL22_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES135_MASK    NVIC_IABR_NVIC_PERIPHERAL23_MASK
#define NVIC_IABR3_NVIC_RES135_DIS    NVIC_IABR_NVIC_PERIPHERAL23_DIS
#define NVIC_IABR3_NVIC_RES135_ENA    NVIC_IABR_NVIC_PERIPHERAL23_ENA

#define NVIC_IABR3_R_NVIC_RES135_BIT    NVIC_IABR_R_NVIC_PERIPHERAL23_BIT
#define NVIC_IABR3_R_NVIC_RES135_MASK    NVIC_IABR_R_NVIC_PERIPHERAL23_MASK
#define NVIC_IABR3_R_NVIC_RES135_DIS    NVIC_IABR_R_NVIC_PERIPHERAL23_DIS
#define NVIC_IABR3_R_NVIC_RES135_ENA    NVIC_IABR_R_NVIC_PERIPHERAL23_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES136_MASK    NVIC_IABR_NVIC_PERIPHERAL24_MASK
#define NVIC_IABR3_NVIC_RES136_DIS    NVIC_IABR_NVIC_PERIPHERAL24_DIS
#define NVIC_IABR3_NVIC_RES136_ENA    NVIC_IABR_NVIC_PERIPHERAL24_ENA

#define NVIC_IABR3_R_NVIC_RES136_BIT    NVIC_IABR_R_NVIC_PERIPHERAL24_BIT
#define NVIC_IABR3_R_NVIC_RES136_MASK    NVIC_IABR_R_NVIC_PERIPHERAL24_MASK
#define NVIC_IABR3_R_NVIC_RES136_DIS    NVIC_IABR_R_NVIC_PERIPHERAL24_DIS
#define NVIC_IABR3_R_NVIC_RES136_ENA    NVIC_IABR_R_NVIC_PERIPHERAL24_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES137_MASK    NVIC_IABR_NVIC_PERIPHERAL25_MASK
#define NVIC_IABR3_NVIC_RES137_DIS    NVIC_IABR_NVIC_PERIPHERAL25_DIS
#define NVIC_IABR3_NVIC_RES137_ENA    NVIC_IABR_NVIC_PERIPHERAL25_ENA

#define NVIC_IABR3_R_NVIC_RES137_BIT    NVIC_IABR_R_NVIC_PERIPHERAL25_BIT
#define NVIC_IABR3_R_NVIC_RES137_MASK    NVIC_IABR_R_NVIC_PERIPHERAL25_MASK
#define NVIC_IABR3_R_NVIC_RES137_DIS    NVIC_IABR_R_NVIC_PERIPHERAL25_DIS
#define NVIC_IABR3_R_NVIC_RES137_ENA    NVIC_IABR_R_NVIC_PERIPHERAL25_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES138_MASK    NVIC_IABR_NVIC_PERIPHERAL26_MASK
#define NVIC_IABR3_NVIC_RES138_DIS    NVIC_IABR_NVIC_PERIPHERAL26_DIS
#define NVIC_IABR3_NVIC_RES138_ENA    NVIC_IABR_NVIC_PERIPHERAL26_ENA

#define NVIC_IABR3_R_NVIC_RES138_BIT    NVIC_IABR_R_NVIC_PERIPHERAL26_BIT
#define NVIC_IABR3_R_NVIC_RES138_MASK    NVIC_IABR_R_NVIC_PERIPHERAL26_MASK
#define NVIC_IABR3_R_NVIC_RES138_DIS    NVIC_IABR_R_NVIC_PERIPHERAL26_DIS
#define NVIC_IABR3_R_NVIC_RES138_ENA    NVIC_IABR_R_NVIC_PERIPHERAL26_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES139_MASK    NVIC_IABR_NVIC_PERIPHERAL27_MASK
#define NVIC_IABR3_NVIC_RES139_DIS    NVIC_IABR_NVIC_PERIPHERAL27_DIS
#define NVIC_IABR3_NVIC_RES139_ENA    NVIC_IABR_NVIC_PERIPHERAL27_ENA

#define NVIC_IABR3_R_NVIC_RES139_BIT    NVIC_IABR_R_NVIC_PERIPHERAL27_BIT
#define NVIC_IABR3_R_NVIC_RES139_MASK    NVIC_IABR_R_NVIC_PERIPHERAL27_MASK
#define NVIC_IABR3_R_NVIC_RES139_DIS    NVIC_IABR_R_NVIC_PERIPHERAL27_DIS
#define NVIC_IABR3_R_NVIC_RES139_ENA    NVIC_IABR_R_NVIC_PERIPHERAL27_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES140_MASK    NVIC_IABR_NVIC_PERIPHERAL28_MASK
#define NVIC_IABR3_NVIC_RES140_DIS    NVIC_IABR_NVIC_PERIPHERAL28_DIS
#define NVIC_IABR3_NVIC_RES140_ENA    NVIC_IABR_NVIC_PERIPHERAL28_ENA

#define NVIC_IABR3_R_NVIC_RES140_BIT    NVIC_IABR_R_NVIC_PERIPHERAL28_BIT
#define NVIC_IABR3_R_NVIC_RES140_MASK    NVIC_IABR_R_NVIC_PERIPHERAL28_MASK
#define NVIC_IABR3_R_NVIC_RES140_DIS    NVIC_IABR_R_NVIC_PERIPHERAL28_DIS
#define NVIC_IABR3_R_NVIC_RES140_ENA    NVIC_IABR_R_NVIC_PERIPHERAL28_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES141_MASK    NVIC_IABR_NVIC_PERIPHERAL29_MASK
#define NVIC_IABR3_NVIC_RES141_DIS    NVIC_IABR_NVIC_PERIPHERAL29_DIS
#define NVIC_IABR3_NVIC_RES141_ENA    NVIC_IABR_NVIC_PERIPHERAL29_ENA

#define NVIC_IABR3_R_NVIC_RES141_BIT    NVIC_IABR_R_NVIC_PERIPHERAL29_BIT
#define NVIC_IABR3_R_NVIC_RES141_MASK    NVIC_IABR_R_NVIC_PERIPHERAL29_MASK
#define NVIC_IABR3_R_NVIC_RES141_DIS    NVIC_IABR_R_NVIC_PERIPHERAL29_DIS
#define NVIC_IABR3_R_NVIC_RES141_ENA    NVIC_IABR_R_NVIC_PERIPHERAL29_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES142_MASK    NVIC_IABR_NVIC_PERIPHERAL30_MASK
#define NVIC_IABR3_NVIC_RES142_DIS    NVIC_IABR_NVIC_PERIPHERAL30_DIS
#define NVIC_IABR3_NVIC_RES142_ENA    NVIC_IABR_NVIC_PERIPHERAL30_ENA

#define NVIC_IABR3_R_NVIC_RES142_BIT    NVIC_IABR_R_NVIC_PERIPHERAL30_BIT
#define NVIC_IABR3_R_NVIC_RES142_MASK    NVIC_IABR_R_NVIC_PERIPHERAL30_MASK
#define NVIC_IABR3_R_NVIC_RES142_DIS    NVIC_IABR_R_NVIC_PERIPHERAL30_DIS
#define NVIC_IABR3_R_NVIC_RES142_ENA    NVIC_IABR_R_NVIC_PERIPHERAL30_ENA
/*----------*/

/*----------*/
#define NVIC_IABR3_NVIC_RES143_MASK    NVIC_IABR_NVIC_PERIPHERAL31_MASK
#define NVIC_IABR3_NVIC_RES143_DIS    NVIC_IABR_NVIC_PERIPHERAL31_DIS
#define NVIC_IABR3_NVIC_RES143_ENA    NVIC_IABR_NVIC_PERIPHERAL31_ENA

#define NVIC_IABR3_R_NVIC_RES143_BIT    NVIC_IABR_R_NVIC_PERIPHERAL31_BIT
#define NVIC_IABR3_R_NVIC_RES143_MASK    NVIC_IABR_R_NVIC_PERIPHERAL31_MASK
#define NVIC_IABR3_R_NVIC_RES143_DIS    NVIC_IABR_R_NVIC_PERIPHERAL31_DIS
#define NVIC_IABR3_R_NVIC_RES143_ENA    NVIC_IABR_R_NVIC_PERIPHERAL31_ENA
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET3_NVIC_REGISTERDEFINES_SET3_IABR_H_ */
