/**
 *
 * @file NVIC_RegisterDefines_Set0_ISER.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET0_NVIC_REGISTERDEFINES_SET0_ISER_H_
#define XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET0_NVIC_REGISTERDEFINES_SET0_ISER_H_

#include <xDriver_MCU/Core/NVIC/Peripheral/Register/RegisterDefines/RegisterDefines_Set/RegisterDefines_Set_Generic/NVIC_RegisterDefines_Set_Generic.h>

/********************************************************************************************/
/************************************* ISER0 ***********************************************/
/********************************************************************************************/

/*----------*/
#define NVIC_ISER0_NVIC_WWDT_MASK    NVIC_ISER_NVIC_PERIPHERAL0_MASK
#define NVIC_ISER0_NVIC_WWDT_DIS    NVIC_ISER_NVIC_PERIPHERAL0_DIS
#define NVIC_ISER0_NVIC_WWDT_ENA    NVIC_ISER_NVIC_PERIPHERAL0_ENA

#define NVIC_ISER0_R_NVIC_WWDT_BIT    NVIC_ISER_R_NVIC_PERIPHERAL0_BIT
#define NVIC_ISER0_R_NVIC_WWDT_MASK    NVIC_ISER_R_NVIC_PERIPHERAL0_MASK
#define NVIC_ISER0_R_NVIC_WWDT_DIS    NVIC_ISER_R_NVIC_PERIPHERAL0_DIS
#define NVIC_ISER0_R_NVIC_WWDT_ENA    NVIC_ISER_R_NVIC_PERIPHERAL0_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_PVD_MASK    NVIC_ISER_NVIC_PERIPHERAL1_MASK
#define NVIC_ISER0_NVIC_PVD_DIS    NVIC_ISER_NVIC_PERIPHERAL1_DIS
#define NVIC_ISER0_NVIC_PVD_ENA    NVIC_ISER_NVIC_PERIPHERAL1_ENA

#define NVIC_ISER0_R_NVIC_PVD_BIT    NVIC_ISER_R_NVIC_PERIPHERAL1_BIT
#define NVIC_ISER0_R_NVIC_PVD_MASK    NVIC_ISER_R_NVIC_PERIPHERAL1_MASK
#define NVIC_ISER0_R_NVIC_PVD_DIS    NVIC_ISER_R_NVIC_PERIPHERAL1_DIS
#define NVIC_ISER0_R_NVIC_PVD_ENA    NVIC_ISER_R_NVIC_PERIPHERAL1_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TAMP_STAMP_MASK    NVIC_ISER_NVIC_PERIPHERAL2_MASK
#define NVIC_ISER0_NVIC_TAMP_STAMP_DIS    NVIC_ISER_NVIC_PERIPHERAL2_DIS
#define NVIC_ISER0_NVIC_TAMP_STAMP_ENA    NVIC_ISER_NVIC_PERIPHERAL2_ENA

#define NVIC_ISER0_R_NVIC_TAMP_STAMP_BIT    NVIC_ISER_R_NVIC_PERIPHERAL2_BIT
#define NVIC_ISER0_R_NVIC_TAMP_STAMP_MASK    NVIC_ISER_R_NVIC_PERIPHERAL2_MASK
#define NVIC_ISER0_R_NVIC_TAMP_STAMP_DIS    NVIC_ISER_R_NVIC_PERIPHERAL2_DIS
#define NVIC_ISER0_R_NVIC_TAMP_STAMP_ENA    NVIC_ISER_R_NVIC_PERIPHERAL2_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_RTC_WKUP_MASK    NVIC_ISER_NVIC_PERIPHERAL3_MASK
#define NVIC_ISER0_NVIC_RTC_WKUP_DIS    NVIC_ISER_NVIC_PERIPHERAL3_DIS
#define NVIC_ISER0_NVIC_RTC_WKUP_ENA    NVIC_ISER_NVIC_PERIPHERAL3_ENA

#define NVIC_ISER0_R_NVIC_RTC_WKUP_BIT    NVIC_ISER_R_NVIC_PERIPHERAL3_BIT
#define NVIC_ISER0_R_NVIC_RTC_WKUP_MASK    NVIC_ISER_R_NVIC_PERIPHERAL3_MASK
#define NVIC_ISER0_R_NVIC_RTC_WKUP_DIS    NVIC_ISER_R_NVIC_PERIPHERAL3_DIS
#define NVIC_ISER0_R_NVIC_RTC_WKUP_ENA    NVIC_ISER_R_NVIC_PERIPHERAL3_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_FLASH_MASK    NVIC_ISER_NVIC_PERIPHERAL4_MASK
#define NVIC_ISER0_NVIC_FLASH_DIS    NVIC_ISER_NVIC_PERIPHERAL4_DIS
#define NVIC_ISER0_NVIC_FLASH_ENA    NVIC_ISER_NVIC_PERIPHERAL4_ENA

#define NVIC_ISER0_R_NVIC_FLASH_BIT    NVIC_ISER_R_NVIC_PERIPHERAL4_BIT
#define NVIC_ISER0_R_NVIC_FLASH_MASK    NVIC_ISER_R_NVIC_PERIPHERAL4_MASK
#define NVIC_ISER0_R_NVIC_FLASH_DIS    NVIC_ISER_R_NVIC_PERIPHERAL4_DIS
#define NVIC_ISER0_R_NVIC_FLASH_ENA    NVIC_ISER_R_NVIC_PERIPHERAL4_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_RCC_MASK    NVIC_ISER_NVIC_PERIPHERAL5_MASK
#define NVIC_ISER0_NVIC_RCC_DIS    NVIC_ISER_NVIC_PERIPHERAL5_DIS
#define NVIC_ISER0_NVIC_RCC_ENA    NVIC_ISER_NVIC_PERIPHERAL5_ENA

#define NVIC_ISER0_R_NVIC_RCC_BIT    NVIC_ISER_R_NVIC_PERIPHERAL5_BIT
#define NVIC_ISER0_R_NVIC_RCC_MASK    NVIC_ISER_R_NVIC_PERIPHERAL5_MASK
#define NVIC_ISER0_R_NVIC_RCC_DIS    NVIC_ISER_R_NVIC_PERIPHERAL5_DIS
#define NVIC_ISER0_R_NVIC_RCC_ENA    NVIC_ISER_R_NVIC_PERIPHERAL5_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_EXTI0_MASK    NVIC_ISER_NVIC_PERIPHERAL6_MASK
#define NVIC_ISER0_NVIC_EXTI0_DIS    NVIC_ISER_NVIC_PERIPHERAL6_DIS
#define NVIC_ISER0_NVIC_EXTI0_ENA    NVIC_ISER_NVIC_PERIPHERAL6_ENA

#define NVIC_ISER0_R_NVIC_EXTI0_BIT    NVIC_ISER_R_NVIC_PERIPHERAL6_BIT
#define NVIC_ISER0_R_NVIC_EXTI0_MASK    NVIC_ISER_R_NVIC_PERIPHERAL6_MASK
#define NVIC_ISER0_R_NVIC_EXTI0_DIS    NVIC_ISER_R_NVIC_PERIPHERAL6_DIS
#define NVIC_ISER0_R_NVIC_EXTI0_ENA    NVIC_ISER_R_NVIC_PERIPHERAL6_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_EXTI1_MASK    NVIC_ISER_NVIC_PERIPHERAL7_MASK
#define NVIC_ISER0_NVIC_EXTI1_DIS    NVIC_ISER_NVIC_PERIPHERAL7_DIS
#define NVIC_ISER0_NVIC_EXTI1_ENA    NVIC_ISER_NVIC_PERIPHERAL7_ENA

#define NVIC_ISER0_R_NVIC_EXTI1_BIT    NVIC_ISER_R_NVIC_PERIPHERAL7_BIT
#define NVIC_ISER0_R_NVIC_EXTI1_MASK    NVIC_ISER_R_NVIC_PERIPHERAL7_MASK
#define NVIC_ISER0_R_NVIC_EXTI1_DIS    NVIC_ISER_R_NVIC_PERIPHERAL7_DIS
#define NVIC_ISER0_R_NVIC_EXTI1_ENA    NVIC_ISER_R_NVIC_PERIPHERAL7_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_EXTI2_MASK    NVIC_ISER_NVIC_PERIPHERAL8_MASK
#define NVIC_ISER0_NVIC_EXTI2_DIS    NVIC_ISER_NVIC_PERIPHERAL8_DIS
#define NVIC_ISER0_NVIC_EXTI2_ENA    NVIC_ISER_NVIC_PERIPHERAL8_ENA

#define NVIC_ISER0_R_NVIC_EXTI2_BIT    NVIC_ISER_R_NVIC_PERIPHERAL8_BIT
#define NVIC_ISER0_R_NVIC_EXTI2_MASK    NVIC_ISER_R_NVIC_PERIPHERAL8_MASK
#define NVIC_ISER0_R_NVIC_EXTI2_DIS    NVIC_ISER_R_NVIC_PERIPHERAL8_DIS
#define NVIC_ISER0_R_NVIC_EXTI2_ENA    NVIC_ISER_R_NVIC_PERIPHERAL8_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_EXTI3_MASK    NVIC_ISER_NVIC_PERIPHERAL9_MASK
#define NVIC_ISER0_NVIC_EXTI3_DIS    NVIC_ISER_NVIC_PERIPHERAL9_DIS
#define NVIC_ISER0_NVIC_EXTI3_ENA    NVIC_ISER_NVIC_PERIPHERAL9_ENA

#define NVIC_ISER0_R_NVIC_EXTI3_BIT    NVIC_ISER_R_NVIC_PERIPHERAL9_BIT
#define NVIC_ISER0_R_NVIC_EXTI3_MASK    NVIC_ISER_R_NVIC_PERIPHERAL9_MASK
#define NVIC_ISER0_R_NVIC_EXTI3_DIS    NVIC_ISER_R_NVIC_PERIPHERAL9_DIS
#define NVIC_ISER0_R_NVIC_EXTI3_ENA    NVIC_ISER_R_NVIC_PERIPHERAL9_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_EXTI4_MASK    NVIC_ISER_NVIC_PERIPHERAL10_MASK
#define NVIC_ISER0_NVIC_EXTI4_DIS    NVIC_ISER_NVIC_PERIPHERAL10_DIS
#define NVIC_ISER0_NVIC_EXTI4_ENA    NVIC_ISER_NVIC_PERIPHERAL10_ENA

#define NVIC_ISER0_R_NVIC_EXTI4_BIT    NVIC_ISER_R_NVIC_PERIPHERAL10_BIT
#define NVIC_ISER0_R_NVIC_EXTI4_MASK    NVIC_ISER_R_NVIC_PERIPHERAL10_MASK
#define NVIC_ISER0_R_NVIC_EXTI4_DIS    NVIC_ISER_R_NVIC_PERIPHERAL10_DIS
#define NVIC_ISER0_R_NVIC_EXTI4_ENA    NVIC_ISER_R_NVIC_PERIPHERAL10_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM0_MASK    NVIC_ISER_NVIC_PERIPHERAL11_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM0_DIS    NVIC_ISER_NVIC_PERIPHERAL11_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM0_ENA    NVIC_ISER_NVIC_PERIPHERAL11_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM0_BIT    NVIC_ISER_R_NVIC_PERIPHERAL11_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM0_MASK    NVIC_ISER_R_NVIC_PERIPHERAL11_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM0_DIS    NVIC_ISER_R_NVIC_PERIPHERAL11_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM0_ENA    NVIC_ISER_R_NVIC_PERIPHERAL11_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM1_MASK    NVIC_ISER_NVIC_PERIPHERAL12_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM1_DIS    NVIC_ISER_NVIC_PERIPHERAL12_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM1_ENA    NVIC_ISER_NVIC_PERIPHERAL12_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM1_BIT    NVIC_ISER_R_NVIC_PERIPHERAL12_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM1_MASK    NVIC_ISER_R_NVIC_PERIPHERAL12_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM1_DIS    NVIC_ISER_R_NVIC_PERIPHERAL12_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM1_ENA    NVIC_ISER_R_NVIC_PERIPHERAL12_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM2_MASK    NVIC_ISER_NVIC_PERIPHERAL13_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM2_DIS    NVIC_ISER_NVIC_PERIPHERAL13_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM2_ENA    NVIC_ISER_NVIC_PERIPHERAL13_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM2_BIT    NVIC_ISER_R_NVIC_PERIPHERAL13_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM2_MASK    NVIC_ISER_R_NVIC_PERIPHERAL13_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM2_DIS    NVIC_ISER_R_NVIC_PERIPHERAL13_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM2_ENA    NVIC_ISER_R_NVIC_PERIPHERAL13_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM3_MASK    NVIC_ISER_NVIC_PERIPHERAL14_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM3_DIS    NVIC_ISER_NVIC_PERIPHERAL14_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM3_ENA    NVIC_ISER_NVIC_PERIPHERAL14_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM3_BIT    NVIC_ISER_R_NVIC_PERIPHERAL14_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM3_MASK    NVIC_ISER_R_NVIC_PERIPHERAL14_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM3_DIS    NVIC_ISER_R_NVIC_PERIPHERAL14_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM3_ENA    NVIC_ISER_R_NVIC_PERIPHERAL14_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM4_MASK    NVIC_ISER_NVIC_PERIPHERAL15_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM4_DIS    NVIC_ISER_NVIC_PERIPHERAL15_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM4_ENA    NVIC_ISER_NVIC_PERIPHERAL15_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM4_BIT    NVIC_ISER_R_NVIC_PERIPHERAL15_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM4_MASK    NVIC_ISER_R_NVIC_PERIPHERAL15_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM4_DIS    NVIC_ISER_R_NVIC_PERIPHERAL15_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM4_ENA    NVIC_ISER_R_NVIC_PERIPHERAL15_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM5_MASK    NVIC_ISER_NVIC_PERIPHERAL16_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM5_DIS    NVIC_ISER_NVIC_PERIPHERAL16_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM5_ENA    NVIC_ISER_NVIC_PERIPHERAL16_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM5_BIT    NVIC_ISER_R_NVIC_PERIPHERAL16_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM5_MASK    NVIC_ISER_R_NVIC_PERIPHERAL16_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM5_DIS    NVIC_ISER_R_NVIC_PERIPHERAL16_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM5_ENA    NVIC_ISER_R_NVIC_PERIPHERAL16_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_DMA1_STREAM6_MASK    NVIC_ISER_NVIC_PERIPHERAL17_MASK
#define NVIC_ISER0_NVIC_DMA1_STREAM6_DIS    NVIC_ISER_NVIC_PERIPHERAL17_DIS
#define NVIC_ISER0_NVIC_DMA1_STREAM6_ENA    NVIC_ISER_NVIC_PERIPHERAL17_ENA

#define NVIC_ISER0_R_NVIC_DMA1_STREAM6_BIT    NVIC_ISER_R_NVIC_PERIPHERAL17_BIT
#define NVIC_ISER0_R_NVIC_DMA1_STREAM6_MASK    NVIC_ISER_R_NVIC_PERIPHERAL17_MASK
#define NVIC_ISER0_R_NVIC_DMA1_STREAM6_DIS    NVIC_ISER_R_NVIC_PERIPHERAL17_DIS
#define NVIC_ISER0_R_NVIC_DMA1_STREAM6_ENA    NVIC_ISER_R_NVIC_PERIPHERAL17_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_ADC_MASK    NVIC_ISER_NVIC_PERIPHERAL18_MASK
#define NVIC_ISER0_NVIC_ADC_DIS    NVIC_ISER_NVIC_PERIPHERAL18_DIS
#define NVIC_ISER0_NVIC_ADC_ENA    NVIC_ISER_NVIC_PERIPHERAL18_ENA

#define NVIC_ISER0_R_NVIC_ADC_BIT    NVIC_ISER_R_NVIC_PERIPHERAL18_BIT
#define NVIC_ISER0_R_NVIC_ADC_MASK    NVIC_ISER_R_NVIC_PERIPHERAL18_MASK
#define NVIC_ISER0_R_NVIC_ADC_DIS    NVIC_ISER_R_NVIC_PERIPHERAL18_DIS
#define NVIC_ISER0_R_NVIC_ADC_ENA    NVIC_ISER_R_NVIC_PERIPHERAL18_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_CAN1_TX_MASK    NVIC_ISER_NVIC_PERIPHERAL19_MASK
#define NVIC_ISER0_NVIC_CAN1_TX_DIS    NVIC_ISER_NVIC_PERIPHERAL19_DIS
#define NVIC_ISER0_NVIC_CAN1_TX_ENA    NVIC_ISER_NVIC_PERIPHERAL19_ENA

#define NVIC_ISER0_R_NVIC_CAN1_TX_BIT    NVIC_ISER_R_NVIC_PERIPHERAL19_BIT
#define NVIC_ISER0_R_NVIC_CAN1_TX_MASK    NVIC_ISER_R_NVIC_PERIPHERAL19_MASK
#define NVIC_ISER0_R_NVIC_CAN1_TX_DIS    NVIC_ISER_R_NVIC_PERIPHERAL19_DIS
#define NVIC_ISER0_R_NVIC_CAN1_TX_ENA    NVIC_ISER_R_NVIC_PERIPHERAL19_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_CAN1_RX0_MASK    NVIC_ISER_NVIC_PERIPHERAL20_MASK
#define NVIC_ISER0_NVIC_CAN1_RX0_DIS    NVIC_ISER_NVIC_PERIPHERAL20_DIS
#define NVIC_ISER0_NVIC_CAN1_RX0_ENA    NVIC_ISER_NVIC_PERIPHERAL20_ENA

#define NVIC_ISER0_R_NVIC_CAN1_RX0_BIT    NVIC_ISER_R_NVIC_PERIPHERAL20_BIT
#define NVIC_ISER0_R_NVIC_CAN1_RX0_MASK    NVIC_ISER_R_NVIC_PERIPHERAL20_MASK
#define NVIC_ISER0_R_NVIC_CAN1_RX0_DIS    NVIC_ISER_R_NVIC_PERIPHERAL20_DIS
#define NVIC_ISER0_R_NVIC_CAN1_RX0_ENA    NVIC_ISER_R_NVIC_PERIPHERAL20_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_CAN1_RX1_MASK    NVIC_ISER_NVIC_PERIPHERAL21_MASK
#define NVIC_ISER0_NVIC_CAN1_RX1_DIS    NVIC_ISER_NVIC_PERIPHERAL21_DIS
#define NVIC_ISER0_NVIC_CAN1_RX1_ENA    NVIC_ISER_NVIC_PERIPHERAL21_ENA

#define NVIC_ISER0_R_NVIC_CAN1_RX1_BIT    NVIC_ISER_R_NVIC_PERIPHERAL21_BIT
#define NVIC_ISER0_R_NVIC_CAN1_RX1_MASK    NVIC_ISER_R_NVIC_PERIPHERAL21_MASK
#define NVIC_ISER0_R_NVIC_CAN1_RX1_DIS    NVIC_ISER_R_NVIC_PERIPHERAL21_DIS
#define NVIC_ISER0_R_NVIC_CAN1_RX1_ENA    NVIC_ISER_R_NVIC_PERIPHERAL21_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_CAN1_SCE_MASK    NVIC_ISER_NVIC_PERIPHERAL22_MASK
#define NVIC_ISER0_NVIC_CAN1_SCE_DIS    NVIC_ISER_NVIC_PERIPHERAL22_DIS
#define NVIC_ISER0_NVIC_CAN1_SCE_ENA    NVIC_ISER_NVIC_PERIPHERAL22_ENA

#define NVIC_ISER0_R_NVIC_CAN1_SCE_BIT    NVIC_ISER_R_NVIC_PERIPHERAL22_BIT
#define NVIC_ISER0_R_NVIC_CAN1_SCE_MASK    NVIC_ISER_R_NVIC_PERIPHERAL22_MASK
#define NVIC_ISER0_R_NVIC_CAN1_SCE_DIS    NVIC_ISER_R_NVIC_PERIPHERAL22_DIS
#define NVIC_ISER0_R_NVIC_CAN1_SCE_ENA    NVIC_ISER_R_NVIC_PERIPHERAL22_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_EXT9_5_MASK    NVIC_ISER_NVIC_PERIPHERAL23_MASK
#define NVIC_ISER0_NVIC_EXT9_5_DIS    NVIC_ISER_NVIC_PERIPHERAL23_DIS
#define NVIC_ISER0_NVIC_EXT9_5_ENA    NVIC_ISER_NVIC_PERIPHERAL23_ENA

#define NVIC_ISER0_R_NVIC_EXT9_5_BIT    NVIC_ISER_R_NVIC_PERIPHERAL23_BIT
#define NVIC_ISER0_R_NVIC_EXT9_5_MASK    NVIC_ISER_R_NVIC_PERIPHERAL23_MASK
#define NVIC_ISER0_R_NVIC_EXT9_5_DIS    NVIC_ISER_R_NVIC_PERIPHERAL23_DIS
#define NVIC_ISER0_R_NVIC_EXT9_5_ENA    NVIC_ISER_R_NVIC_PERIPHERAL23_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM1_BRK_TIM9_MASK    NVIC_ISER_NVIC_PERIPHERAL24_MASK
#define NVIC_ISER0_NVIC_TIM1_BRK_TIM9_DIS    NVIC_ISER_NVIC_PERIPHERAL24_DIS
#define NVIC_ISER0_NVIC_TIM1_BRK_TIM9_ENA    NVIC_ISER_NVIC_PERIPHERAL24_ENA

#define NVIC_ISER0_R_NVIC_TIM1_BRK_TIM9_BIT    NVIC_ISER_R_NVIC_PERIPHERAL24_BIT
#define NVIC_ISER0_R_NVIC_TIM1_BRK_TIM9_MASK    NVIC_ISER_R_NVIC_PERIPHERAL24_MASK
#define NVIC_ISER0_R_NVIC_TIM1_BRK_TIM9_DIS    NVIC_ISER_R_NVIC_PERIPHERAL24_DIS
#define NVIC_ISER0_R_NVIC_TIM1_BRK_TIM9_ENA    NVIC_ISER_R_NVIC_PERIPHERAL24_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM1_UP_TIM10_MASK    NVIC_ISER_NVIC_PERIPHERAL25_MASK
#define NVIC_ISER0_NVIC_TIM1_UP_TIM10_DIS    NVIC_ISER_NVIC_PERIPHERAL25_DIS
#define NVIC_ISER0_NVIC_TIM1_UP_TIM10_ENA    NVIC_ISER_NVIC_PERIPHERAL25_ENA

#define NVIC_ISER0_R_NVIC_TIM1_UP_TIM10_BIT    NVIC_ISER_R_NVIC_PERIPHERAL25_BIT
#define NVIC_ISER0_R_NVIC_TIM1_UP_TIM10_MASK    NVIC_ISER_R_NVIC_PERIPHERAL25_MASK
#define NVIC_ISER0_R_NVIC_TIM1_UP_TIM10_DIS    NVIC_ISER_R_NVIC_PERIPHERAL25_DIS
#define NVIC_ISER0_R_NVIC_TIM1_UP_TIM10_ENA    NVIC_ISER_R_NVIC_PERIPHERAL25_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM1_TRG_COM_TIM11_MASK    NVIC_ISER_NVIC_PERIPHERAL26_MASK
#define NVIC_ISER0_NVIC_TIM1_TRG_COM_TIM11_DIS    NVIC_ISER_NVIC_PERIPHERAL26_DIS
#define NVIC_ISER0_NVIC_TIM1_TRG_COM_TIM11_ENA    NVIC_ISER_NVIC_PERIPHERAL26_ENA

#define NVIC_ISER0_R_NVIC_TIM1_TRG_COM_TIM11_BIT    NVIC_ISER_R_NVIC_PERIPHERAL26_BIT
#define NVIC_ISER0_R_NVIC_TIM1_TRG_COM_TIM11_MASK    NVIC_ISER_R_NVIC_PERIPHERAL26_MASK
#define NVIC_ISER0_R_NVIC_TIM1_TRG_COM_TIM11_DIS    NVIC_ISER_R_NVIC_PERIPHERAL26_DIS
#define NVIC_ISER0_R_NVIC_TIM1_TRG_COM_TIM11_ENA    NVIC_ISER_R_NVIC_PERIPHERAL26_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM1_CC_MASK    NVIC_ISER_NVIC_PERIPHERAL27_MASK
#define NVIC_ISER0_NVIC_TIM1_CC_DIS    NVIC_ISER_NVIC_PERIPHERAL27_DIS
#define NVIC_ISER0_NVIC_TIM1_CC_ENA    NVIC_ISER_NVIC_PERIPHERAL27_ENA

#define NVIC_ISER0_R_NVIC_TIM1_CC_BIT    NVIC_ISER_R_NVIC_PERIPHERAL27_BIT
#define NVIC_ISER0_R_NVIC_TIM1_CC_MASK    NVIC_ISER_R_NVIC_PERIPHERAL27_MASK
#define NVIC_ISER0_R_NVIC_TIM1_CC_DIS    NVIC_ISER_R_NVIC_PERIPHERAL27_DIS
#define NVIC_ISER0_R_NVIC_TIM1_CC_ENA    NVIC_ISER_R_NVIC_PERIPHERAL27_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM2_MASK    NVIC_ISER_NVIC_PERIPHERAL28_MASK
#define NVIC_ISER0_NVIC_TIM2_DIS    NVIC_ISER_NVIC_PERIPHERAL28_DIS
#define NVIC_ISER0_NVIC_TIM2_ENA    NVIC_ISER_NVIC_PERIPHERAL28_ENA

#define NVIC_ISER0_R_NVIC_TIM2_BIT    NVIC_ISER_R_NVIC_PERIPHERAL28_BIT
#define NVIC_ISER0_R_NVIC_TIM2_MASK    NVIC_ISER_R_NVIC_PERIPHERAL28_MASK
#define NVIC_ISER0_R_NVIC_TIM2_DIS    NVIC_ISER_R_NVIC_PERIPHERAL28_DIS
#define NVIC_ISER0_R_NVIC_TIM2_ENA    NVIC_ISER_R_NVIC_PERIPHERAL28_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM3_MASK    NVIC_ISER_NVIC_PERIPHERAL29_MASK
#define NVIC_ISER0_NVIC_TIM3_DIS    NVIC_ISER_NVIC_PERIPHERAL29_DIS
#define NVIC_ISER0_NVIC_TIM3_ENA    NVIC_ISER_NVIC_PERIPHERAL29_ENA

#define NVIC_ISER0_R_NVIC_TIM3_BIT    NVIC_ISER_R_NVIC_PERIPHERAL29_BIT
#define NVIC_ISER0_R_NVIC_TIM3_MASK    NVIC_ISER_R_NVIC_PERIPHERAL29_MASK
#define NVIC_ISER0_R_NVIC_TIM3_DIS    NVIC_ISER_R_NVIC_PERIPHERAL29_DIS
#define NVIC_ISER0_R_NVIC_TIM3_ENA    NVIC_ISER_R_NVIC_PERIPHERAL29_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_TIM4_MASK    NVIC_ISER_NVIC_PERIPHERAL30_MASK
#define NVIC_ISER0_NVIC_TIM4_DIS    NVIC_ISER_NVIC_PERIPHERAL30_DIS
#define NVIC_ISER0_NVIC_TIM4_ENA    NVIC_ISER_NVIC_PERIPHERAL30_ENA

#define NVIC_ISER0_R_NVIC_TIM4_BIT    NVIC_ISER_R_NVIC_PERIPHERAL30_BIT
#define NVIC_ISER0_R_NVIC_TIM4_MASK    NVIC_ISER_R_NVIC_PERIPHERAL30_MASK
#define NVIC_ISER0_R_NVIC_TIM4_DIS    NVIC_ISER_R_NVIC_PERIPHERAL30_DIS
#define NVIC_ISER0_R_NVIC_TIM4_ENA    NVIC_ISER_R_NVIC_PERIPHERAL30_ENA
/*----------*/

/*----------*/
#define NVIC_ISER0_NVIC_I2C1_EV_MASK    NVIC_ISER_NVIC_PERIPHERAL31_MASK
#define NVIC_ISER0_NVIC_I2C1_EV_DIS    NVIC_ISER_NVIC_PERIPHERAL31_DIS
#define NVIC_ISER0_NVIC_I2C1_EV_ENA    NVIC_ISER_NVIC_PERIPHERAL31_ENA

#define NVIC_ISER0_R_NVIC_I2C1_EV_BIT    NVIC_ISER_R_NVIC_PERIPHERAL31_BIT
#define NVIC_ISER0_R_NVIC_I2C1_EV_MASK    NVIC_ISER_R_NVIC_PERIPHERAL31_MASK
#define NVIC_ISER0_R_NVIC_I2C1_EV_DIS    NVIC_ISER_R_NVIC_PERIPHERAL31_DIS
#define NVIC_ISER0_R_NVIC_I2C1_EV_ENA    NVIC_ISER_R_NVIC_PERIPHERAL31_ENA
/*----------*/

#endif /* XDRIVER_MCU_DRIVER_HEADER_NVIC_NVIC_PERIPHERAL_NVIC_REGISTER_NVIC_REGISTERDEFINES_NVIC_REGISTERDEFINES_SET0_NVIC_REGISTERDEFINES_SET0_ISER_H_ */
