/**
 *
 * @file SCB_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 19 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 19 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Enum.h>

#define SCB_VECTOR_TABLE_SIZE ((UBase_t) 0x00000100UL)

typedef enum
{
    SCB_enERROR_OK = (UBase_t) MCU_enERROR_OK,
    SCB_enERROR_POINTER = (UBase_t) MCU_enERROR_POINTER,
    SCB_enERROR_VALUE = (UBase_t) MCU_enERROR_VALUE,
    SCB_enERROR_RANGE = (UBase_t) MCU_enERROR_RANGE,
    SCB_enERROR_UNDEF = (UBase_t) MCU_enERROR_UNDEF,
}SCB_nERROR;

typedef enum
{
    SCB_enPRI0 = (UBase_t) MCU_enPRI0,
    SCB_enPRI1 = (UBase_t) MCU_enPRI1,
    SCB_enPRI2 = (UBase_t) MCU_enPRI2,
    SCB_enPRI3 = (UBase_t) MCU_enPRI3,
    SCB_enPRI4 = (UBase_t) MCU_enPRI4,
    SCB_enPRI5 = (UBase_t) MCU_enPRI5,
    SCB_enPRI6 = (UBase_t) MCU_enPRI6,
    SCB_enPRI7 = (UBase_t) MCU_enPRI7,
    SCB_enPRI8 = (UBase_t) MCU_enPRI8,
    SCB_enPRI9 = (UBase_t) MCU_enPRI9,
    SCB_enPRI10 = (UBase_t) MCU_enPRI10,
    SCB_enPRI11 = (UBase_t) MCU_enPRI11,
    SCB_enPRI12 = (UBase_t) MCU_enPRI12,
    SCB_enPRI13 = (UBase_t) MCU_enPRI13,
    SCB_enPRI14 = (UBase_t) MCU_enPRI14,
    SCB_enPRI15 = (UBase_t) MCU_enPRI15,
    SCB_enPRIMAX = (UBase_t) MCU_enPRIMAX,
    SCB_enDEFAULT = (UBase_t) MCU_enDEFAULT,
    SCB_enPRI_UNDEF = (UBase_t) MCU_enDEFAULT,
}SCB_nPRIORITY;

typedef enum
{
    SCB_enFALSE = (UBase_t) FALSE,
    SCB_enTRUE = (UBase_t) TRUE,
    SCB_enBOOLEAN_UNDEF = UNDEF_VALUE,
}SCB_nBOOLEAN;

typedef enum
{
    SCB_enSTATE_DIS = (UBase_t) MCU_enSTATE_DIS,
    SCB_enSTATE_ENA = (UBase_t) MCU_enSTATE_ENA,
    SCB_enSTATE_UNDEF = UNDEF_VALUE,
}SCB_nSTATE;

typedef enum
{
    SCB_enMODULE_0 = 0UL,
    SCB_enMODULE_MAX = 1UL,
    SCB_enMODULE_UNDEF = UNDEF_VALUE,
}SCB_nMODULE;

typedef enum
{
    SCB_enPRIGROUP_XXXX = 3UL,
    SCB_enPRIGROUP_XXXY = 4UL,
    SCB_enPRIGROUP_XXYY = 5UL,
    SCB_enPRIGROUP_XYYY = 6UL,
    SCB_enPRIGROUP_YYYY = 7UL,
    SCB_enPRIGROUP_MAX  = 8UL,
    SCB_enPRIGROUP_ERROR = UNDEF_VALUE,
}SCB_nPRIGROUP;

typedef enum
{
    SCB_enNOPENDING = 0UL,
    SCB_enPENDING = 1UL,
    SCB_enPENDSTATE_UNDEF = UNDEF_VALUE,
}SCB_nPENDSTATE;

typedef enum
{
    SCB_enFAULT_USAGE = 0UL,
    SCB_enFAULT_BUS = 1UL,
    SCB_enFAULT_MEMORY = 2UL,
    SCB_enFAULT_NMI = 3UL,
    SCB_enFAULT_MAX = 4UL,
    SCB_enFAULT_UNDEF = UNDEF_VALUE,
}SCB_nFAULT;

typedef enum
{
    SCB_enNMI_NONE = 0x00UL,
    SCB_enNMI_EXTERNAL = 0x01UL,
    SCB_enNMI_POWER = 0x04UL,
    SCB_enNMI_WDT0 = 0x08UL,
    SCB_enNMI_WDT1 = 0x20UL,
    SCB_enNMI_TAMPER = 0x200UL,
    SCB_enNMI_MOSC_FAILURE = 0x10000UL,
    SCB_enNMI_ALL = 0x1022DUL,
    SCB_enNMI_UNDEF = UNDEF_VALUE,
}SCB_nNMI;

typedef enum
{
    SCB_enNMI_BIT_EXTERNAL = 0UL,
    SCB_enNMI_BIT_POWER = 1UL,
    SCB_enNMI_BIT_WDT0 = 2UL,
    SCB_enNMI_BIT_WDT1 = 3UL,
    SCB_enNMI_BIT_TAMPER = 4UL,
    SCB_enNMI_BIT_MOSC_FAILURE = 5UL,
    SCB_enNMI_BIT_SW = 6UL,
    SCB_enNMI_BIT_MAX = 7UL,
    SCB_enNMI_BIT_UNDEF = UNDEF_VALUE,
}SCB_nNMI_BIT;

typedef enum
{
    SCB_enHARD_NONE = 0x00UL,
    SCB_enHARD_VECT = 0x02UL,
    SCB_enHARD_ALL = 0x02UL,
    SCB_enHARD_UNDEF = UNDEF_VALUE,
}SCB_nHARD;

typedef enum
{
    SCB_enHARD_BIT_VECT = 0UL,
    SCB_enHARD_BIT_SW = 1UL,
    SCB_enHARD_BIT_MAX = 2UL,
    SCB_enHARD_BIT_UNDEF = UNDEF_VALUE,
}SCB_nHARD_BIT;

typedef enum
{
    SCB_enUSAGE_NONE = 0x0000UL,
    SCB_enUSAGE_UNDEFINSTR = 0x0001UL,
    SCB_enUSAGE_INVSTATE = 0x0002UL,
    SCB_enUSAGE_INVPC = 0x0004UL,
    SCB_enUSAGE_NOCP = 0x0008UL,
    SCB_enUSAGE_UNALIGNED = 0x0100UL,
    SCB_enUSAGE_DIVBYZERO = 0x0200UL,
    SCB_enUSAGE_ALL = 0x030FUL,
    SCB_enUSAGE_UNDEF = UNDEF_VALUE,
}SCB_nUSAGE;

typedef enum
{
    SCB_enUSAGE_BIT_UNDEFINSTR = 0UL,
    SCB_enUSAGE_BIT_INVSTATE = 1UL,
    SCB_enUSAGE_BIT_INVPC = 2UL,
    SCB_enUSAGE_BIT_NOCP = 3UL,
    SCB_enUSAGE_BIT_UNALIGNED = 4UL,
    SCB_enUSAGE_BIT_DIVBYZERO = 5UL,
    SCB_enUSAGE_BIT_SW = 6UL,
    SCB_enUSAGE_BIT_MAX = 7UL,
    SCB_enUSAGE_BIT_UNDEF = UNDEF_VALUE,
}SCB_nUSAGE_BIT;

typedef enum
{
    SCB_enBUS_NONE = 0x00UL,
    SCB_enBUS_IBUSERR = 0x01UL,
    SCB_enBUS_PRECISERR = 0x02UL,
    SCB_enBUS_IMPRECISERR = 0x04UL,
    SCB_enBUS_UNSTKERR = 0x08UL,
    SCB_enBUS_STKERR = 0x10UL,
    SCB_enBUS_LSPERR = 0x20UL,
    SCB_enBUS_BFARVALID = 0x80UL,
    SCB_enBUS_ALL = 0xBFUL,
    SCB_enBUS_UNDEF = UNDEF_VALUE,
}SCB_nBUS;

typedef enum
{
    SCB_enBUS_BIT_IBUSERR = 0UL,
    SCB_enBUS_BIT_PRECISERR = 1UL,
    SCB_enBUS_BIT_IMPRECISERR = 2UL,
    SCB_enBUS_BIT_UNSTKERR = 3UL,
    SCB_enBUS_BIT_STKERR = 4UL,
    SCB_enBUS_BIT_LSPERR = 5UL,
    SCB_enBUS_BIT_BFARVALID = 6UL,
    SCB_enBUS_BIT_SW = 7UL,
    SCB_enBUS_BIT_MAX = 8UL,
    SCB_enBUS_BIT_UNDEF = UNDEF_VALUE,
}SCB_nBUS_BIT;

typedef enum
{
    SCB_enMEMORY_NONE = 0x00UL,
    SCB_enMEMORY_IACCVIOL = 0x01UL,
    SCB_enMEMORY_DACCVIOL = 0x02UL,
    SCB_enMEMORY_MUNSTKERR = 0x08UL,
    SCB_enMEMORY_MSTKERR = 0x10UL,
    SCB_enMEMORY_MLSPERR = 0x20UL,
    SCB_enMEMORY_MMARVALID = 0x80UL,
    SCB_enMEMORY_ALL = 0xBBUL,
    SCB_enMEMORY_UNDEF = UNDEF_VALUE,
}SCB_nMEMORY;

typedef enum
{
    SCB_enMEMORY_BIT_IACCVIOL = 0UL,
    SCB_enMEMORY_BIT_DACCVIOL = 1UL,
    SCB_enMEMORY_BIT_MUNSTKERR = 2UL,
    SCB_enMEMORY_BIT_MSTKERR = 3UL,
    SCB_enMEMORY_BIT_MLSPERR = 4UL,
    SCB_enMEMORY_BIT_MMARVALID = 5UL,
    SCB_enMEMORY_BIT_SW = 6UL,
    SCB_enMEMORY_BIT_MAX = 7UL,
    SCB_enMEMORY_BIT_UNDEF = UNDEF_VALUE,
}SCB_nMEMORY_BIT;

typedef enum
{
    SCB_enALIGN_8BYTE = 1UL,
    SCB_enALIGN_ERROR = UNDEF_VALUE,
}SCB_nALIGN;

typedef enum
{
    SCB_enWAKEUP_ENABLE_ISR = 0UL,
    SCB_enWAKEUP_ALL_ISR = 1UL,
    SCB_enWAKEUP_UNDEF = UNDEF_VALUE,
}SCB_nWAKEUP;

typedef enum
{
    SCB_enSLEEPONEXIT_RUN = 0UL,
    SCB_enSLEEPONEXIT_SLEEP = 1UL,
    SCB_enSLEEPONEXIT_UNDEF = UNDEF_VALUE,
}SCB_nSLEEPONEXIT;

typedef enum
{
    SCB_enSLEEPMODE_SLEEP = 0UL,
    SCB_enSLEEPMODE_DEEPSLEEP = 1UL,
    SCB_enSLEEPMODE_UNDEF = UNDEF_VALUE,
}SCB_nSLEEPMODE;

typedef enum
{
    SCB_enVECISR_THREAD = 0UL,
    SCB_enVECISR_RESET = 1UL,
    SCB_enVECISR_NMI = 2UL,
    SCB_enVECISR_HARDFAULT = 3UL,
    SCB_enVECISR_MEMMANAGE = 4UL,
    SCB_enVECISR_BUSFAULT = 5UL,
    SCB_enVECISR_USAGEFAULT = 6UL,
    SCB_enVECISR_RES7 = 7UL,
    SCB_enVECISR_RES8 = 8UL,
    SCB_enVECISR_RES9 = 9UL,
    SCB_enVECISR_RES10 = 10UL,
    SCB_enVECISR_SVCALL = 11UL,
    SCB_enVECISR_DEBUGMON = 12UL,
    SCB_enVECISR_RES13 = 13UL,
    SCB_enVECISR_PENDSV = 14UL,
    SCB_enVECISR_SYSTICK = 15UL,
    SCB_enVECISR_WWDT = 0UL + 16UL,
    SCB_enVECISR_PVD = 1UL + 16UL,
    SCB_enVECISR_TAMP_STAMP = 2UL + 16UL,
    SCB_enVECISR_RTC_WKUP = 3UL + 16UL,
    SCB_enVECISR_FLASH = 4UL + 16UL,
    SCB_enVECISR_RCC = 5UL + 16UL,
    SCB_enVECISR_EXTI0 = 6UL + 16UL,
    SCB_enVECISR_EXTI1 = 7UL + 16UL,
    SCB_enVECISR_EXTI2 = 8UL + 16UL,
    SCB_enVECISR_EXTI3 = 9UL + 16UL,
    SCB_enVECISR_EXTI4 = 10UL + 16UL,
    SCB_enVECISR_DMA1_STREAM0 = 11UL + 16UL,
    SCB_enVECISR_DMA1_STREAM1 = 12UL + 16UL,
    SCB_enVECISR_DMA1_STREAM2 = 13UL + 16UL,
    SCB_enVECISR_DMA1_STREAM3 = 14UL + 16UL,
    SCB_enVECISR_DMA1_STREAM4 = 15UL + 16UL,
    SCB_enVECISR_DMA1_STREAM5 = 16UL + 16UL,
    SCB_enVECISR_DMA1_STREAM6 = 17UL + 16UL,
    SCB_enVECISR_ADC = 18UL + 16UL,
    SCB_enVECISR_CAN1_TX = 19UL + 16UL,
    SCB_enVECISR_CAN1_RX0 = 20UL + 16UL,
    SCB_enVECISR_CAN1_RX1 = 21UL + 16UL,
    SCB_enVECISR_CAN1_SCE = 22UL + 16UL,
    SCB_enVECISR_EXTI9_5 = 23UL + 16UL,
    SCB_enVECISR_TIM1_BRK_TIM9 = 24UL + 16UL,
    SCB_enVECISR_TIM1_UP_TIM10 = 25UL + 16UL,
    SCB_enVECISR_TIM1_TRG_COM_TIM11 = 26UL + 16UL,
    SCB_enVECISR_TIM1_CC = 27UL + 16UL,
    SCB_enVECISR_TIM2 = 28UL + 16UL,
    SCB_enVECISR_TIM3 = 29UL + 16UL,
    SCB_enVECISR_TIM4 = 30UL + 16UL,
    SCB_enVECISR_I2C1_EV = 31UL + 16UL,
    SCB_enVECISR_I2C1_ER = 32UL + 16UL,
    SCB_enVECISR_I2C2_EV = 33UL + 16UL,
    SCB_enVECISR_I2C2_ER = 34UL + 16UL,
    SCB_enVECISR_SPI1 = 35UL + 16UL,
    SCB_enVECISR_SPI2 = 36UL + 16UL,
    SCB_enVECISR_USART1 = 37UL + 16UL,
    SCB_enVECISR_USART2 = 38UL + 16UL,
    SCB_enVECISR_USART3 = 39UL + 16UL,
    SCB_enVECISR_EXTI15_10 = 40UL + 16UL,
    SCB_enVECISR_RTC_ALARM = 41UL + 16UL,
    SCB_enVECISR_OTG_FS_WKUP = 42UL + 16UL,
    SCB_enVECISR_TIM8_BRK_TIM12 = 43UL + 16UL,
    SCB_enVECISR_TIM8_UP_TIM13 = 44UL + 16UL,
    SCB_enVECISR_TIM8_TRG_COM_TIM14 = 45UL + 16UL,
    SCB_enVECISR_TIM8_CC = 46UL + 16UL,
    SCB_enVECISR_DMA1_STREAM7 = 47UL + 16UL,
    SCB_enVECISR_FMC = 48UL + 16UL,
    SCB_enVECISR_SDMMC1 = 49UL + 16UL,
    SCB_enVECISR_TIM5 = 50UL + 16UL,
    SCB_enVECISR_SPI3 = 51UL + 16UL,
    SCB_enVECISR_UART4 = 52UL + 16UL,
    SCB_enVECISR_UART5 = 53UL + 16UL,
    SCB_enVECISR_TIM6_DAC = 54UL + 16UL,
    SCB_enVECISR_TIM7 = 55UL + 16UL,
    SCB_enVECISR_DMA2_STREAM0 = 56UL + 16UL,
    SCB_enVECISR_DMA2_STREAM1 = 57UL + 16UL,
    SCB_enVECISR_DMA2_STREAM2 = 58UL + 16UL,
    SCB_enVECISR_DMA2_STREAM3 = 59UL + 16UL,
    SCB_enVECISR_DMA2_STREAM4 = 60UL + 16UL,
    SCB_enVECISR_ETH = 61UL + 16UL,
    SCB_enVECISR_ETH_WKUP = 62UL + 16UL,
    SCB_enVECISR_CAN2_TX = 63UL + 16UL,
    SCB_enVECISR_CAN2_RX0 = 64UL + 16UL,
    SCB_enVECISR_CAN2_RX1 = 65UL + 16UL,
    SCB_enVECISR_CAN2_SCE = 66UL + 16UL,
    SCB_enVECISR_OTG_FS = 67UL + 16UL,
    SCB_enVECISR_DMA2_STREAM5 = 68UL + 16UL,
    SCB_enVECISR_DMA2_STREAM6 = 69UL + 16UL,
    SCB_enVECISR_DMA2_STREAM7 = 70UL + 16UL,
    SCB_enVECISR_USART6 = 71UL + 16UL,
    SCB_enVECISR_I2C3_EV = 72UL + 16UL,
    SCB_enVECISR_I2C3_ER = 73UL + 16UL,
    SCB_enVECISR_OTG_HS_EP1_OUT = 74UL + 16UL,
    SCB_enVECISR_OTG_HS_EP1_IN = 75UL + 16UL,
    SCB_enVECISR_OTG_HS_WKUP = 76UL + 16UL,
    SCB_enVECISR_OTG_HS = 77UL + 16UL,
    SCB_enVECISR_DCMI = 78UL + 16UL,
    SCB_enVECISR_CRYP = 79UL + 16UL,
    SCB_enVECISR_HASH_RNG = 80UL + 16UL,
    SCB_enVECISR_FPU = 81UL + 16UL,
    SCB_enVECISR_UART7 = 82UL + 16UL,
    SCB_enVECISR_UART8 = 83UL + 16UL,
    SCB_enVECISR_SPI4 = 84UL + 16UL,
    SCB_enVECISR_SPI5 = 85UL + 16UL,
    SCB_enVECISR_SPI6 = 86UL + 16UL,
    SCB_enVECISR_SAI1 = 87UL + 16UL,
    SCB_enVECISR_LCD_TFT = 88UL + 16UL,
    SCB_enVECISR_LCD_TFT_ER = 89UL + 16UL,
    SCB_enVECISR_DMA2D = 90UL + 16UL,
    SCB_enVECISR_SAI2 = 91UL + 16UL,
    SCB_enVECISR_QSPI = 92UL + 16UL,
    SCB_enVECISR_LPTIM1 = 93UL + 16UL,
    SCB_enVECISR_HDMI_CEC = 94UL + 16UL,
    SCB_enVECISR_I2C4_EV = 95UL + 16UL,
    SCB_enVECISR_I2C4_ER = 96UL + 16UL,
    SCB_enVECISR_SPDIF_RX = 97UL + 16UL,
    SCB_enVECISR_DSI_HOST = 98UL + 16UL,
    SCB_enVECISR_DFSDM1_FLT0 = 99UL + 16UL,
    SCB_enVECISR_DFSDM1_FLT1 = 100UL + 16UL,
    SCB_enVECISR_DFSDM1_FLT2 = 101UL + 16UL,
    SCB_enVECISR_DFSDM1_FLT3 = 102UL + 16UL,
    SCB_enVECISR_SDMMC2 = 103UL + 16UL,
    SCB_enVECISR_CAN3_TX = 104UL + 16UL,
    SCB_enVECISR_CAN3_RX0 = 105UL + 16UL,
    SCB_enVECISR_CAN3_RX1 = 106UL + 16UL,
    SCB_enVECISR_CAN3_SCE = 107UL + 16UL,
    SCB_enVECISR_JPEG = 108UL + 16UL,
    SCB_enVECISR_MDIO_SLAVE = 109UL + 16UL,
    SCB_enVECISR_MAX = 110UL + 16UL,
    SCB_enVECISR_UNDEF = UNDEF_VALUE,
}SCB_nVECISR;

typedef MCU_Register_t SCB_Register_t;
typedef MCU_pvfIRQVectorHandler_t SCB_pvfIRQVectorHandler_t;
typedef MCU_pvfIRQSourceHandler_t SCB_pvfIRQSourceHandler_t;

#endif /* XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_ */
